### ISSUE TITLE
Worker dies often

### ISSUE THREAD

**Issue by silvenon** [AtomLinter/linter-eslint#341] opened 2015-11-29 20:48 UTC
<img width="462" alt="screenshot 2015-11-29 21 48 25" src="https://cloud.githubusercontent.com/assets/471278/11459956/f3a46f2e-96e2-11e5-8094-b389cc370caf.png">

I haven't noticed a pattern, unfortunately. It fails with the following message:

```js
{
  "stdout": "",
  "stderr": "(34771,0x7fff76b61000) malloc: *** error for object 0x7fed7bc110c0: pointer being freed was not allocated\n*** set a breakpoint in malloc_error_break to debug\n"
}
```

Is anyone else experiencing this?

**Comment by steelbrain** [comment] 2015-11-29 20:49
Dupe of #326 #303 #302 #301 #295 #290 and #278

**Closed by steelbrain** 2015-11-29 20:49 UTC

**Comment by silvenon** [comment] 2015-11-29 21:09
Holy dupe.

**Comment by steelbrain** [comment] 2015-11-29 21:10
To answer your question, see [this](https://github.com/AtomLinter/linter-eslint/issues/278#issuecomment-157892974)
