### ISSUE TITLE
Wrong position(column & line) on "Fix" function execution

### ISSUE THREAD

**Issue by vpiskunov** [AtomLinter/linter-eslint#1126] opened 2018-04-11 19:11 UTC
## Issue Type
Bug

#### "Fix" function in editor: wrong column(offset)
e.g. on fixable issue, such as "there should not be a space inside function parenthesis", instead of removing the space, removes the char which follows the space.

Occurs randomly, but often. When the glitch is noticed, if you undo the change(Cmd+Z), and click "Fix" again - it works correctly.

This also is the case with wrong-line: the replaced part of the "fixed" string is being inserted at a wrong line(often 2 lines above the correct one)

#### Also notices sometimes this relates to file-edit-history:
Another appearance has shown to restore the inside-content of multi-line part of file being fixed to an older(a few edits back) version.

#### Another case: Spaces inserted unnecessarily into "no-concat" fix
`print( " > via " + converted_value + " " + first_available )`
"fixes" to:
``print( ` > via ${    converted_value     } ${     first_available}` )``

## Bug Checklist
- [ + ] Restart Atom
- [ N/A ] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [ N/A ] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: N/A
```

**Comment by vpiskunov** [comment] 2018-04-11 19:33
I guess you’re right about the fix-all taking care of extra spaces etc. But what about the fix being inserted at wrong line / column? 

With this I can’t trust it to run on all files on its own, no way am I going to spot these errors later on, meaning hours of debug lost. 

The config is bare minimum: extends Airbnb-base, 1 rule disabled(camelase), empty plugins: []. 

Not at my desk right now.

**Comment by vpiskunov** [comment] 2018-04-11 19:34
If this may have any relevance - I had Fast-eslint installed previously.

**Comment by rugk** [comment] 2018-04-22 14:47
I can also reproduce this. It seems to always insert it to the position where I have (or just had) my cursor.

Note: As for that I only ever ran it for a single function/individual fix instead of the whole file as I fear that it may break some more.

The code in my test is: https://github.com/rugk/offline-qr-code (eslintrc config will soon be pushed there)

**Comment by rugk** [comment] 2018-04-22 14:59
Okay, in another file it now seems to work… strange…

**Comment by rugk** [comment] 2018-04-22 15:00
But sometimes now, when I fixed something, I cannot move the cursor in Atom anymore with my keyboard… :laughing: (so when I click somewhere else and go back, it works again)

**Comment by michaelauderer** [comment] 2018-11-07 21:53
I am also having this issue. It appears that after I perform a fix in a file, if I perform a second fix afterwards it edits the code in the completely wrong line. It seems as though it is "caching" the line position of the error and not updating it after I fix.

So, if the first fix affects the line numbers of the code, i.e. refactoring a long line into multiple lines, then subsequent fixes will be in the wrong place. It seems to be remembering the line numbers before the fix was performed, not re-checking after a fix.

So, steps to reproduce: 
- make 2 errors in a file on different lines. the first error should be something like a line that goes past the config's line-length
- fix the first one (hover over and click Fix)
- fix the second one (hover over and click Fix)

the second fix will be applied in the wrong position.

**Comment by Arcanemagus** [comment] 2018-11-07 22:33
As [already stated](https://github.com/AtomLinter/linter-eslint/issues/1126#issuecomment-380567191) the individual fixes are _not recommended_ for exactly the reasons you are posting:

1. Document is linted, sending back messages with fixes
2. Individually fix issue 1
3. Code is changed
4. Before the managing program notifies `linter-eslint` about this and it can provide updated results, you request an individual fix for issue 2
5. Since the diff was based on the state from step 1, it now applies something that may be _entirely wrong_ for the current state of the document.

You can really only use individual fixes if:
* **No** changes have been made to the document between the last update of the results and the request for the fix
* The fix doesn't conflict with a different rule you also have enabled

In general that first condition is going to mess up most fixes, which is why we have the `Linter Eslint: Fix File` command, also accessible as a right click option. This requests ESLint to run a full fix pass on the document, fixing everything that it can in one go preventing conflicts like this among other issues with automated fixing of the code.

If you can find a way to reproduce fixes going to the wrong location, and provide an example environment where we can reproduce this we can take a look at it, but so far everything described here seems like a misunderstanding of what individual fixes are and when they can actually be used. As such I'm going to close this but we would be happy to fix any actual issues with our translation of ESLint's individual diffs to something understood by the Linter API!

**Closed by Arcanemagus** 2018-11-07 22:33 UTC
Labels: unable to reproduce
