### ISSUE TITLE
2.4.1 also not working properly

### ISSUE THREAD

**Issue by wwwsevolod** [AtomLinter/linter-eslint#151] opened 2015-07-10 12:09 UTC
Now installed `v1.0.18` with `apm install linter-eslint@1.0.18`, and can't say what output exactly was, but it said there is no output from eslint, and it can't find eslint in project folder, and bundled eslint not worked. I set eslint path in settings, and it produced same output too.

Thank you for this plugin, hope you'll fix it soon!

**Comment by iam4x** [comment] 2015-07-10 12:10
@wwwsevolod Are you starting Atom from CLI? If no try `$ atom .`

**Comment by 7rulnik** [comment] 2015-07-10 12:12
@iam4x yes, it works by this way

**Comment by iam4x** [comment] 2015-07-10 12:12
Okey it's dupe of #149 let's continue discussion there, trying to fix :+1:

**Closed by iam4x** 2015-07-10 12:12 UTC
