### ISSUE TITLE
Invalid position given by 'no-multiple-empty-lines'

### ISSUE THREAD

**Issue by rromanw** [AtomLinter/linter-eslint#802] opened 2017-02-02 12:50 UTC
ESLint returned a point that did not exist in the document being edited.
Rule: `no-multiple-empty-lines`
Requested range: 196:1

This seems to happen, when there are more than 3 empty lines next to each other. It underscores the first line of the file and prompts for reporting the bug.

Debug information:
```json
{
  "atomVersion": "1.13.1",
  "linterEslintVersion": "8.1.0",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 36.5,
  "platform": "win32",
  "eslintType": "local project",
  "eslintPath": "X:\\projects\\project\\node_modules\\eslint"
}
```

**Comment by ummahusla** [comment] 2017-02-03 11:23
## I have the same issue

ESLint returned a point that did not exist in the document being edited.
Rule: `no-multiple-empty-lines`
Requested range: 179:1





Debug information:
```json
{
  "atomVersion": "1.13.1",
  "linterEslintVersion": "8.1.0",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 24.8,
  "platform": "win32",
  "eslintType": "local project",
  "eslintPath": "D:\\repos\\CallParents\\CG.CallParents.Web\\Areas\\Beta\\App\\node_modules\\eslint"
}
```

**Comment by ctxhou** [comment] 2017-02-03 15:13
The same issue too.

<hr/>

ESLint returned a point that did not exist in the document being edited.
Rule: `no-multiple-empty-lines`
Requested range: 11:1

Debug information:
```json
{
  "atomVersion": "1.12.8",
  "linterEslintVersion": "8.1.0",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 0,
  "platform": "darwin",
  "eslintType": "local project"
}
```

**Comment by IanVS** [comment] 2017-02-03 15:20
This is a duplicate of #687. Please upgrade your version of ESLint to 3.5.0 or above.

**Closed by IanVS** 2017-02-03 15:20 UTC
