### ISSUE TITLE
Error: EPERM: operation not permitted, write

### ISSUE THREAD

**Issue by midascodebreaker** [AtomLinter/linter-eslint#579] opened 2016-05-14 06:34 UTC
```
Error: EPERM: operation not permitted, write
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2059:6)
    at Console.warn (console.js:44:16)
    at Object.module.exports.error (C:\Users\Uriah\Codes\vue-ui\resources\assets\js\vue-ui\node_modules\eslint\lib\logging.js:26:23)
    at printResults (C:\Users\Uriah\Codes\vue-ui\resources\assets\js\vue-ui\node_modules\eslint\lib\cli.js:79:13)
    at Object.cli.execute (C:\Users\Uriah\Codes\vue-ui\resources\assets\js\vue-ui\node_modules\eslint\lib\cli.js:191:17)
    at lintJob (C:\Users\Uriah\.atom\packages\linter-eslint\lib\worker.js:30:10)
    at C:\Users\Uriah\.atom\packages\linter-eslint\lib\worker.js:66:20
    at Emitter.emit (C:\Users\Uriah\.atom\packages\linter-eslint\node_modules\process-communication\node_modules\sb-event-kit\lib\emitter.js:70:19)
```

**Comment by Arcanemagus** [comment] 2016-05-17 17:20
What version of `eslint` do you have installed in that project?

**Comment by mikecousins** [comment] 2016-08-02 21:05
I'm getting this with:

    "eslint": "3.2.2",
    "eslint-config-airbnb": "10.0.0",
    "eslint-plugin-import": "1.12.0",
    "eslint-plugin-jsx-a11y": "2.0.1",
    "eslint-plugin-react": "6.0.0",

**Comment by mikecousins** [comment] 2016-08-03 22:14
![image](https://cloud.githubusercontent.com/assets/725614/17383827/4e4e9600-5995-11e6-87af-56ed9508f207.png)

Are you guys seeing this too? It's pretty unusable right now.

**Comment by IanVS** [comment] 2016-08-04 11:50
No, I have not seen that and am having trouble thinking about what might be causing it.  I know it sounds crazy, but have you tried restarting Atom lately?  Sometimes that solves strange problems like this (for some unknown reason).

**Comment by snowcxt** [comment] 2016-08-04 17:56
experiencing same issue here since I updated eslint from `3.1.1` yesterday

```json
    "eslint": "3.2.2",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-import": "^1.12.0",
    "eslint-plugin-jsx-a11y": "^2.0.1",
    "eslint-plugin-react": "^6.0.0",

```

![image](https://cloud.githubusercontent.com/assets/1463415/17412464/ac8b4906-5a31-11e6-99de-4d1c210cf49d.png)

**Comment by IanVS** [comment] 2016-08-04 17:58
Interesting, seems to perhaps be a change in ESLint `3.2.2`.  Thanks for the tip, I'll do some investigating tonight.

**Comment by mikecousins** [comment] 2016-08-04 18:59
Yup, it only started happening after the eslint upgrade.

**Comment by mikecousins** [comment] 2016-08-05 16:52
Any luck?

**Comment by IanVS** [comment] 2016-08-05 17:03
Not so far, I didn't have a chance last night like I hoped.  It's high on my list, and I'll let you know if/when I figure out what's going on.

**Comment by mikecousins** [comment] 2016-08-05 17:13
Cool, no problem. Thanks for your efforts!

**Comment by akash87** [comment] 2016-08-07 18:18
I am facing same issue as @mikecousins. Please look into this.

**Comment by FurryFur** [comment] 2016-08-08 09:26
Same

**Comment by pavlin99th** [comment] 2016-08-08 15:45
The breaking change seems to be in **eslint-plugin-react** v6.0.0, released on 2016-08-01. The note reads 

> Deprecate require-extension rule, use the eslint-plugin-import extensions rule instead. require-extension still works but will trigger a warning

At the same time **eslint-config-airbnb** v10.0.0 uses that rule. There is an open issue for [that](https://github.com/airbnb/javascript/issues/978).

**Comment by mikecousins** [comment] 2016-08-08 15:51
That shows up as a minor warning when running it via the command-line. It's pretty in your face in Atom.

**Comment by IanVS** [comment] 2016-08-08 16:32
@akash87, I am not paid for this work and do it in my spare time. Making demands will not help.  I am in the middle of a renovation on my house and dealing with family health problems, in addition to tight deadlines at work.

This is open-source, and you're free to investigate and fix the problem if it is causing you pain.  I'd be happy to review and merge a PR.

**Comment by MirPresT** [comment] 2016-08-10 19:40
@IanVS I've run into the same issue. As I respect your time, do you know of a fix I can do in the mean time to continue using this in atom? Do I need to install a different version of a certain es-lint package or install a different version of this atom package? I know this might be obvious for some but I'm not entirely sure what the immediate work around is.

**Comment by mikecousins** [comment] 2016-08-10 19:42
I just disabled the linter-eslint plugin for now and an instead running it on the command line.

On 10 Aug 2016 1:41 pm, Terrell <notifications@github.com> wrote:

@IanVS<https://github.com/IanVS> I've run into the same issue. As I respect your time, do you know of a fix I can do in the mean time to continue using this in atom? Do I need to install a different version of a certain es-lint package or install a different version of this atom package? I know this might be obvious for some but I'm not entirely sure what the immediate work around is.

-

**Comment by IanVS** [comment] 2016-08-10 19:43
There have been reports of ESLint `3.1.x` working without errors, so you could try downgrading to that version.

**Comment by MirPresT** [comment] 2016-08-10 21:48
Thank you for the quick response. I reverted back to eslint 3.1.1 and 3.1.0 and neither seemed to solve the problem. Did the classic restarts as well. No luck.

### Error in Atom
```
Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2064:6)
    at Console.log (console.js:39:16)
    at EventEmitter.Program (C:\Users\Terrell BigT Vest\Projects\terrellvest.com\node_modules\eslint-plugin-react\lib\rules\require-extension.js:103:17)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (C:\Users\Terrell BigT Vest\Projects\terrellvest.com\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Users\Terrell BigT Vest\Projects\terrellvest.com\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (C:\Users\Terrell BigT Vest\Projects\terrellvest.com\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
```

### versions
node: 6.1.0
atom: 1.9.8
linter-eslint: 7.2.4

```json
    "eslint": "^3.1.0",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-import-resolver-webpack": "^0.4.0",
    "eslint-plugin-import": "^1.12.0",
    "eslint-plugin-jsx-a11y": "^2.1.0",
    "eslint-plugin-react": "^6.0.0",
```

### eslintrc.json file I was testing with

```json
{
  "extends": "airbnb",
  "rules": {
    "jsx-quotes": 1,
    "react/jsx-": 0
  }
}
```

**Comment by IanVS** [comment] 2016-08-10 22:14
`"eslint": "^3.1.0",` will grab the latest eslint until `4.0.0`.  You can verify which version is installed with `npm ls eslint`.  You should remove the `^` if you want to specify the version exactly.

**Comment by MirPresT** [comment] 2016-08-10 22:44
Thanks. I went back to  eslint3.1.0 but all the other related dependencies didn't quite like that so after resolving the many UNMET PEER DEPENDENCY, the following versions are working with the eslint atom plugin.

```sh
eslint@2.9.0
eslint-config-airbnb@9.0.1
eslint-import-resolver-webpack@0.4.0
eslint-plugin-import@1.12.0
eslint-plugin-jsx-a11y@1.2.0
eslint-plugin-react@5.0.1
```

**Comment by mikecousins** [comment] 2016-08-10 22:53
Yeah, that's why I just disabled it for now. You have to downgrade quite a few packages to get it working.

**Comment by IanVS** [comment] 2016-08-10 23:12
Had to go all the way back to eslint@2.9.0?

**Comment by MirPresT** [comment] 2016-08-11 00:32
@IanVS I wasn't able to get eslint@3.1.x to work. Yes, had to go back to 2.9 to get things working again.

**Comment by IanVS** [comment] 2016-08-11 01:09
I can't reproduce this so far.  I'm on a mac, though, and it looks like maybe everyone having this problem is using windows?  Can those on this issue give this comment a 👍 reaction if you're using windows and 👎 if using mac or linux?

**Comment by FurryFur** [comment] 2016-08-11 01:34
Easiest fix for me was to just to remove the eslint dependencies from package.json and remove the eslint packages from the node modules folder, change eslint config file so it doesn't use any plugins (make sure it extends recommended only).

**Comment by pavlin99th** [comment] 2016-08-11 06:38
I'm pretty sure it's the problem described in https://github.com/AtomLinter/linter-eslint/issues/418#issuecomment-175908103
All screenshots show `console.log` and Windows platform.
I didn't get this error on a Mac. Commenting out rule's deprecation console.log helped me on Windows. You can see which rule causes the error by scrolling the red error popup. Hope this info helps!

**Comment by ssimunic** [comment] 2016-08-11 09:54
Seems like **eslint-config-airbnb** is causing problems, other styles work fine.

**Comment by IanVS** [comment] 2016-08-11 11:56
@pavlin99th Yes I think it is something like the issue you linked to, although it looks like airbnb does not use any of the deprecated eslint-plugin-react rules.  

Can everyone make sure they are not enabling any of:

- `react/no-comment-textnodes`
- `react/wrap-multilines`
- `react/require-extension`

**Comment by IanVS** [comment] 2016-08-11 12:02
Ah, I missed it the first time, but it looks like they do use `require-extension`: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L173  which [is deprecated](https://github.com/yannickcr/eslint-plugin-react/blob/e84af68a3bf48c9a34f14e73a8b4dc1ed7488bab/lib/rules/require-extension.js#L103) I bet that's the problem.  I'll open a PR with them to remove it.

**Comment by pavlin99th** [comment] 2016-08-11 12:03
@IanVS , take a look: https://github.com/AtomLinter/linter-eslint/issues/579#issuecomment-238279074

**Comment by IanVS** [comment] 2016-08-11 12:12
@pavlin99th Ah, sorry I missed that.  You're absolutely right!  

So, it seems for now you should be able to add this to your `.eslintrc`:

```json
"rules": {
    "react/require-extension": 'off'
}
```

Could someone try this and see if it solves the error?

**Comment by pavlin99th** [comment] 2016-08-11 12:46
> Could someone try this and see if it solves the error?

I confirm, this solves the error. So, the solution for now is to disable the rules which use `console.log` (for deprecation warnings) until the issue with `stdout` on windows is resolved.

**Comment by IanVS** [comment] 2016-08-11 13:02
>until the issue with stdout on windows is resolved

That seems more like an atom bug, do you agree, @Arcanemagus?

**Comment by Arcanemagus** [comment] 2016-08-11 17:11
If I remember correctly it's actually a Node.js bug with older versions (like the one embedded within and used by Atom), either way it's not something that we can really deal with in this package so I'm marking this as closed.

**Closed by Arcanemagus** 2016-08-11 17:11 UTC

**Comment by oksas** [comment] 2016-08-15 00:23
@IanVS, your solution above (setting `"react/require-extension": "off"`) worked perfectly for me :D

Thanks so much for all your hard work on the project, and for the workaround on this particular issue.

**Comment by sompylasar** [comment] 2016-08-23 15:19
If anyone interested in the fix, please vote for the culprit issue here: https://github.com/yannickcr/eslint-plugin-react/issues/783

**Comment by sompylasar** [comment] 2016-09-22 21:56
Update: it's an issue of Atom itself not handling certain inter-process communications correctly.
https://github.com/atom/atom/issues/12504
