### ISSUE TITLE
LinterEslint crashed while opening compressed JS source code

### ISSUE THREAD

**Issue by nwanglu** [AtomLinter/linter-eslint#783] opened 2017-01-13 02:56 UTC
## Issue Type
Bug

## Issue Description
ESLINT crashed after opening compressed source code with about 30000 characters in single line.
Atom: v1.12.7
Linter: 1.11.18
Linter-eslint: 8.0.0 

## Bug Checklist
- import project folder contains attached .eslintrc and index3.js
- open index3.js
- Got error notification and error in console
- Sometimes atom will be crashed without any response
- I can understand checking compressed js code is not designed as expected, but is there any way to disable checking compressed js code by default to avoid this issue? thanks!

```
Linter Eslint: Debug output here
```

[.eslintrc.txt](https://github.com/AtomLinter/linter-eslint/files/703407/default.eslintrc.txt)

[index3.js.txt](https://github.com/AtomLinter/linter-eslint/files/703409/index3.js.txt)

![error](https://cloud.githubusercontent.com/assets/11607990/21916865/4ead655e-d97e-11e6-9bb0-2cdc6d071138.png)

**Comment by Arcanemagus** [comment] 2017-01-30 20:07
I'm going to mark this as a duplicate of #755 as I suspect they are really the same issue. Once a fix for that is figured out we can revisit this to see if it is still a problem.

**Closed by Arcanemagus** 2017-01-30 20:07 UTC
