### ISSUE TITLE
No longer picks up extended local config

### ISSUE THREAD

**Issue by scriptjs** [AtomLinter/linter-eslint#296] opened 2015-11-17 18:02 UTC
I use, as many do, eslint rules extended with my own.  I have this in my own package. It is no longer picking up rules in the scoped packages after the upgrade from 4.x.x to 5.2.0 This is very disruptive.

The module containing my config is referenced in my eslintConfg in my package.json

The config looks like the following:

```
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
    mocha: true
  },
  extends: [
    'eslint:recommended',
    'airbnb',
    '@scoped/mypackage/rules/base',
    '@scoped/mypackage/rules/react'
  ]
};
```

Note that I have replaced my actual scope and name with @scoped/myname for illustration.

This works properly in 4.0.0. It looks like you've pushed a lot of releases in a few days without any tests. I would say it is imperative to make that a focus since eslint is currently the goto linter. With so many folks using eslint and atom both, its bound to spell trouble if code is not subject to any tests before being pushed out to users for upgrades.

**Comment by steelbrain** [comment] 2015-11-17 18:06
While I do agree that our `v5.0.0` and `v5.1.0` releases had some bugs, and we need unit tests, but we fixed them all within hours and within one day, `linter-eslint` was quite stable again despite the complete rewrite.

It's on my todo list to write unit tests for this package. About your bug report, I and @Arcanemagus have been using extends in my package, we have confirmed that they work on both linux and windows and some community members also confirmed they work on OSX too. Can you please give us an example of the dir structure in which you have organized your modules and `.eslintrc`

**Comment by SpainTrain** [comment] 2015-11-17 18:12
PRs are welcomed and encouraged.  They are reviewed and merged quickly.

**Comment by scriptjs** [comment] 2015-11-17 19:28
@steelbrain @SpainTrain Hi guys.  I'm happy to contribute as I have time. I am on OSX. The structure of my eslint package is as follows.

├── CHANGES.md
├── LICENSE
├── README.md
├── index.js
├── node_modules
├── package.json
├── rules
│   ├── base.js
│   └── react.js
└── test
    ├── base-test.js
    └── react-test.js

My config is within my package.json in my eslintConfig, with a reference to my package. I don't like dotted files cluttering the root of my projects. 

ie.
  "eslintConfig": {
    "extends": "@scoped/mypackage"
  }

I have given you the contents of my index.js previously.

**Comment by scriptjs** [comment] 2015-11-17 21:16
@SpainTrain It seems to lint against 'eslint:recommended' and 'airbnb' but ignores rules referenced the in the extends within my package:
    '@scoped/mypackage/rules/base',
    '@scoped/mypackage/rules/react'

For me these rules modify what is available in eslint:recommended and airbnb, making the linting more strict. As an example, airbnb likes dangling commas. For me not so much :/ Anyway I have a number of rules within base and react there to tailor the rules.

In the interim, I have moved back to 4.0.0. Haven't even had time really read your code yet.

**Comment by SpainTrain** [comment] 2015-11-17 22:15
ok, so it sounds like:

* Reading config from package.json works
* The `extends`, referencing a scoped package, in the config in package.json works
* Within that scoped package, `extends` referencing non-scoped packages work
* Within that scoped package, `extends` referencing scoped packages silently fail

Is that an accurate summary?

**Comment by scriptjs** [comment] 2015-11-17 23:18
Yes. That is the behaviour I am experiencing.

**Comment by tschaub** [comment] 2015-11-21 19:16
Let me know if I should open another issue, but including `eslintConfig` with `extends` in `package.json` does not work at all for me.  In my case, there are no scoped packages.

See https://gist.github.com/tschaub/5d2d5f334075ec426e60 for the full setup.  Here is my `package.json`:

```json
{
  "name": "eslint-config",
  "version": "1.0.0",
  "description": "Trying to get Atom linter-eslint to pick up eslintConfig in package.json",
  "main": "index.js",
  "scripts": {
    "test": "eslint index.js"
  },
  "license": "MIT",
  "devDependencies": {
    "eslint": "^1.10.1",
    "eslint-config-planet": "^4.0.0"
  },
  "eslintConfig": {
    "extends": "planet"
  }
}
```

Though `npm test` shows errors, `linter-eslint` reports nothing in Atom.

**Comment by tschaub** [comment] 2015-11-21 23:11
It turns out my issue was related to the `disableWhenNoEslintrcFileInPath` setting (which makes `eslintConfig` in `package.json` not work).  I found #226 and have proposed #318 as a fix.

**Comment by brutalcrozt** [comment] 2016-02-09 18:21
i had same issue on 6.0.0
what's odd is when i open setting the version number show `undefined`

**Comment by scriptjs** [comment] 2016-02-09 19:14
@brutalcrozt I have upgraded to 6.x from 4.x but extending from a config in package.json does not work. Why did you close this?

**Comment by brutalcrozt** [comment] 2016-02-09 19:21
@scriptjs calm down man, i just referenced issue, not closing this issue.
i had same problem :confused:

**Comment by Arcanemagus** [comment] 2016-02-09 19:53
@scriptjs Since it hasn't actually been asked yet as far as I can tell, does `eslint` itself work properly in this setup? I'm assuming so but...

**Comment by isiahmeadows** [comment] 2016-02-10 03:34
@Arcanemagus Yes. Here's the problem I'm experiencing: this config never works, regardless:

```
Directory structure:

project/
    |---- .eslintrc
    |---- test/
              |---- .eslintrc
              |---- test.js
```

Assuming this directory structure and the following contents:

```yml
# project/.eslintrc
rules:
    no-unused-expressions: 2
```

```yml
# project/test/.eslintrc
rules:
    no-unused-expressions: 0
```

The following file would fail to check:

```js
// project/test/test.js
hi; // Error: (no-unused-expressions) ...
```

That is a minimal repro of this bug (which I'm also running into issues with). You remove the top .eslintrc, and it no longer fails.

**Comment by isiahmeadows** [comment] 2016-02-10 03:50
@Arcanemagus I also get the feeling [this line](https://github.com/AtomLinter/linter-eslint/blob/master/src/worker-helpers.js#L115) might be the culprit.

**Comment by scriptjs** [comment] 2016-02-10 03:53
@brutalcrozt sorry man, yeah jumped the gun there. apologies :)

**Comment by brutalcrozt** [comment] 2016-02-10 11:36
@Arcanemagus Did this package need configuration on atom config `config.cson` ? What is look's like? i realize my linter not work at all, even i write rules on `.eslintrc.js`

**Comment by brutalcrozt** [comment] 2016-02-10 13:09
@scriptjs hey try these, 
```
apm install linter
apm install linter-eslint
```
i am not sure about this one but this how i open my atom, not via shortcut
```
atom .
```
it work with extending config.

this may far related but i change the config like these before it work
```
linter:
  gutterPosisition: "Left"
	statusIconScope: "File"
```
details :	
`atom 1.5.0
linter 1.11.3
linter-eslint 6.0.0` :sweat_smile:

**Comment by Arcanemagus** [comment] 2016-02-10 19:21
@isiahmeadows That... does not look right at all :open_mouth:

@steelbrain Do you know what is going on there? Looks like you added that [here](https://github.com/AtomLinter/linter-eslint/commit/4817724349d08ef032443939477082037c45bd1d).

**Comment by Arcanemagus** [comment] 2016-02-10 19:44
@isiahmeadows I'm unable to reproduce your issue with `eslint` 1.10.3:
![image](https://cloud.githubusercontent.com/assets/427137/12959280/9be53a02-cfea-11e5-818a-be7c3f3651ee.png)
![image](https://cloud.githubusercontent.com/assets/427137/12959287/a951241c-cfea-11e5-9847-f08b77d674d8.png)

(I threw another error in there to show that it was actually showing errors).

That line you mention is apparently a dummy value used to spawn the worker, the actual cwd is set [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/src/worker-helpers.js#L87-L92).

**Comment by steelbrain** [comment] 2016-02-10 19:46
@isiahmeadows That was actually an invalid note, fixed it here https://github.com/AtomLinter/linter-eslint/pull/432

**Comment by isiahmeadows** [comment] 2016-02-10 19:49
@Arcanemagus @steelbrain Add `extends: ../.eslintrc` to "test/.eslintrc". I just repro'd it locally that way.

**Comment by Arcanemagus** [comment] 2016-02-10 19:55
@isiahmeadows I still can't reproduce with [this setup](https://drive.google.com/file/d/0BwNHIQX2XG-lbmJQRlVDRm5CWTg/view).

**Comment by isiahmeadows** [comment] 2016-02-10 19:59
I'm actually having trouble reproducing it locally, but I'm running into the same problem.

**Comment by isiahmeadows** [comment] 2016-02-10 20:01
It almost feels like a race condition of sorts, since I only can reproduce it inconsistently.

**Comment by isiahmeadows** [comment] 2016-02-10 20:08
@Arcanemagus @steelbrain And even in an affected project, I can't seem to reproduce it more than 50% of the time.

**Comment by steelbrain** [comment] 2016-02-10 20:10
@isiahmeadows I just tried to repro using the zip provided by @Arcanemagus and was unable to. Also It's very highly unlikely that it's a race condition since the work in worker thread is sync not async

**Comment by Arcanemagus** [comment] 2016-02-10 20:23
So that was a silly example I did... the error up there is a _fatal_ one, after which no other errors are reported :stuck_out_tongue:

That being said, I still can't reproduce this :disappointed:

I've updated the zip file above with the new version:
![image](https://cloud.githubusercontent.com/assets/427137/12960633/1c7453f0-cff1-11e5-959b-510f145a8f9b.png)
![image](https://cloud.githubusercontent.com/assets/427137/12960640/25a5e72c-cff1-11e5-921c-efcffb3fd086.png)

**Comment by adius** [comment] 2016-04-27 13:00
The linter is absolute useless until this issue is fixed.
I'm not going to include a copy of my eslint config file in every repo...

**Comment by IanVS** [comment] 2016-04-27 14:20
@adius it's hard to tell if you're talking about the same issue here.  So far we've had trouble reproducing the issue, perhaps you can help us to consistently reproduce?

**Comment by isiahmeadows** [comment] 2016-04-28 06:30
@adius If you can come up with a minimal repro, that would be awesome! :smile: 

(I tried and failed, as well as a few others here.)

**Comment by adius** [comment] 2016-04-28 09:16
https://gist.github.com/adius/391cdc2e4ba772b3d2ef03c8b825ed7d

**Comment by adius** [comment] 2016-04-28 09:18
https://gist.github.com/adius/391cdc2e4ba772b3d2ef03c8b825ed7d
Clone this repo and run `npm install`.
If you now open `index.js` linter-eslint will not pick up the configuration.
[fast-eslint](https://atom.io/packages/fast-eslint) in comparison correctly does!

**Comment by isiahmeadows** [comment] 2016-04-28 12:10
@adius

Did you forget to include `javascript-styleguide` as a dependency?

**Comment by adius** [comment] 2016-04-28 14:06
Ah yeah, fixed it.
Weird, my shell history confirms that i run `npm i --save-dev`,
but somehow it didn't save it ^^

**Comment by brutalcrozt** [comment] 2016-04-30 03:06
> @Arcanemagus That being said, I still can't reproduce this.

close for now?

**Comment by adius** [comment] 2016-04-30 11:49
Did you check out my minimal example?

**Comment by isiahmeadows** [comment] 2016-04-30 15:40
@Arcanemagus @brutalcrozt Does @adius' repro?

**Comment by isiahmeadows** [comment] 2016-04-30 20:49
@adius I couldn't get a full repro, but I did find that even though the errors are reported correctly, the red lines don't appear. This is with only the builtins + linter-eslint enabled, right after an `apm update` (I disabled the ~30 or so rest).

**Comment by isiahmeadows** [comment] 2016-04-30 20:52
![screenshot](http://s32.postimg.org/rzihymjh1/Screenshot_from_2016_04_30_16_50_22.png)

**Comment by Arcanemagus** [comment] 2016-05-06 18:14
@adius @isiahmeadows I assumed that it wasn't a valid repo case when @adius said that including `javascript-styleguide` fixed it :stuck_out_tongue:

Checking it out now.

@isiahmeadows the "red lines" not showing up is either a style bug or something else, if you file an issue about that we can diagnose that there.

**Comment by Arcanemagus** [comment] 2016-05-06 18:20
@adius I can't reproduce with your Gist either :confused: 

![image](https://cloud.githubusercontent.com/assets/427137/15082420/79cc6bb8-137c-11e6-9ba9-d23e393eb49f.png)

**Comment by adius** [comment] 2016-05-06 18:54
Mh strange. …anyways, fast-eslint works for me at the moment.
If nobody else has this problem, I guess it's not worth the effort.
Feel free to close this issue.

**Comment by isiahmeadows** [comment] 2016-05-08 01:52
@adius What Atom version and linters do you have installed?

**Comment by IanVS** [comment] 2017-01-05 02:56
This issue is very old and it seems that there was difficulty reproducing it.  If anyone is still having problems, please post your versions of `atom`, `linter-eslint`, and `eslint`, and we can reevalutate.

**Closed by IanVS** 2017-01-05 02:56 UTC

**Comment by Yogi2001** [comment] 2018-05-08 04:16
Using linter-eslint 8.4.1
i have a eslintrc.json in my root folder with 
{
"extends": "./docroot/core/.eslintrc.json"
}
but its not picking up the rules
