### ISSUE TITLE
worker keeps dying unexpectedly

### ISSUE THREAD

**Issue by dominicbarnes** [AtomLinter/linter-eslint#308] opened 2015-11-19 20:05 UTC
linter-eslint is consistently crashing on me, it has only gotten worse with subsequent versions since 5.x

<img width="462" alt="screen shot 2015-11-19 at 12 02 55 pm" src="https://cloud.githubusercontent.com/assets/160197/11282710/95e25340-8eb5-11e5-8ac0-62f262afb7ad.png">

I'm also getting a crash report from OSX, I will make sure to include those details next time I get the error.

**Comment by Arcanemagus** [comment] 2015-11-19 20:05
Are you seeing any information in the console like it suggests?

**Comment by steelbrain** [comment] 2015-11-19 20:07
Dupe of #303 #302 #301 #295 #290 and #278

**Comment by dominicbarnes** [comment] 2015-11-19 20:07
Aha, I see an object being output that has `stdout` and `stderr`, `stdout` is empty, here is `stderr`:

```
(1240,0x7fff7a698000) malloc: *** error for object 0x7fdbfbe16550: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Closed by steelbrain** 2015-11-19 20:07 UTC

**Comment by Arcanemagus** [comment] 2015-11-19 20:26
Yep, definitely a dupe then as @steelbrain mentioned. If you update to the v1.3.0 betas it should be fixed.

**Comment by IanVS** [comment] 2015-11-19 21:07
@Arcanemagus, how does one upgrade to the beta?  Atom is telling me I have the latest update at 1.11.2.
