### ISSUE TITLE
linter-eslint stalls on one project in Atom

### ISSUE THREAD

**Issue by codequistador** [AtomLinter/linter-eslint#1059] opened 2017-11-28 23:20 UTC
## Issue Type
Bug

## Issue Description
One of my projects is having trouble using eslint. When I open this project and open a .js file the little icon on the bottom of Atom pulses and is yellow. It never changes and I am unable to get an output from running `Linter Eslint: Debug`. I can run the command in my other project ( see output below ). In the troubled project, the `.eslintrc` file is in the root of the project directory, much like other projects that are working.

Thanks for helping!

## Bug Checklist
- Restart Atom [check]
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not [check, confirmed]
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below [check]

```
Atom version: 1.22.1
linter-eslint version: 8.4.0
ESLint version: 4.11.0
Hours since last Atom restart: 0
Platform: darwin
Using local project ESLint from: /Users/jdaining/Sites/inst/bridge-talent-management/bridge-talent-web/ui/node_modules/eslint
Current file's scopes: [
  "source.js.jsx"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment] 2017-11-28 23:56
Are you able to share this project?

**Comment by codequistador** [comment] 2017-11-29 04:57
Unfortunately no. I can provide more details though.

**Comment by codequistador** [comment] 2017-11-29 16:28
I figured out a way around it, but it is by no means a solution! If I switch from Project A (trouble project) to a different project (Project B) in the same window, quit Atom, restart Atom (eslint now working on Project B) and then switch back to Project A, eslint works on Project A. If I close Atom and then open it again, eslint is no longer working on Project A. So strange!

**Comment by Arcanemagus** [comment] 2017-11-29 17:05
Hmmmmm, can you try rebuilding `node_modules` in Project A? Are A and B both using the same ESLint setup and versions?

**Comment by codequistador** [comment] 2017-11-30 18:15
nuked `node_modules` and rebuilt. Same issue. Both projects are using the same eslint versions and all plugins are the same versions. The setup is very similar apart from two additional rules in `.eslintrc` in Project B. I tried them with the same rules/setup and still the problem.

**Comment by Arcanemagus** [comment] 2017-11-30 20:54
Can you send me a DM on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638)?

**Comment by sillysloft** [comment] 2018-01-01 21:50
@codequistador do you use git in your trouble project?

**Comment by skylize** [comment] 2018-02-01 18:22
@codequistador Is this still giving you problems?

**Comment by skylize** [comment] 2018-02-25 03:31
Closing, since this case has been silent for some time, and so far appears to be not reproducable.

@codequistador Let us know if you think this should be reopened. Would be extremely helpful to have a minimum case to reproduce.

**Closed by skylize** 2018-02-25 03:31 UTC
Labels: Unable to Reproduce, question
