### ISSUE TITLE
Error: Column start (7) greater than line length (2)

### ISSUE THREAD

**Issue by RB-Lab** [AtomLinter/linter-eslint#322] opened 2015-11-22 09:56 UTC
**Version: 5.2.1**

Constantly got this error:
```
Error: Column start (7) greater than line length (2)
    at Object.module.exports.Helpers.rangeFromLineNumber (/home/unnamet/.atom/packages/linter-eslint/node_modules/atom-linter/lib/helpers.coffee:73:17)
    at /home/unnamet/.atom/packages/linter-eslint/lib/main.js:143:35
    at Array.map (native)
    at /home/unnamet/.atom/packages/linter-eslint/lib/main.js:142:27
    at run (/home/unnamet/.atom/packages/recent-projects/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
    at /home/unnamet/.atom/packages/recent-projects/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/home/unnamet/.atom/packages/recent-projects/node_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
It seems that error mostly occurs in two cases:
- when there is missing semicolon in linting file
- when you start a new empty line

Maybe it also caused by my indentation settings (I use tabs instead of spaces). 

Maybe this also somehow connected with #276 and PR in it.

**Comment by Arcanemagus** [comment] 2015-11-23 03:22
Do you have an example file to trigger this with? Your `package.json` (and `.eslintrc`) would be necessary too to duplicate the environment.

**Comment by laddi** [comment] 2015-11-23 14:06
The same happens to me after updating to the latest version.

**Comment by Arcanemagus** [comment] 2015-11-23 18:09
Marking as duplicate of https://github.com/AtomLinter/atom-linter/issues/63, I'm not sure why you are only now seeing this as before it would have been crashing inside an Atom function, we simply added a check to catch this failure before calling the Atom function.

Can you see if your file mixes tabs and spaces for indentation?

**Closed by Arcanemagus** 2015-11-23 18:09 UTC

**Comment by silvenon** [comment] 2015-11-23 23:59
In my case I narrowed it down to [jsx-closing-bracket-location](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md) rule from eslint-plugin-react. It happened to me when I would turn this:

```jsx
<div />
```
into this:
```jsx
<div
  />
```

**Comment by Arcanemagus** [comment] 2015-11-24 00:28
@silvenon are you mixing tabs and spaces in the file by any chance? You can tell Atom to show "invisible" characters by running `Window: Toggle Invisibles` from the command palette.

**Comment by brandondurham** [comment] 2015-11-24 00:54
Happening here and haven't been able to find the culprit. Will report back if I do.

**Comment by silvenon** [comment] 2015-11-24 02:27
@Arcanemagus no, I'm using strictly tabs, I told ESLint to yell at me otherwise. I was hoping the answer is somewhere in [jsx-closing-bracket-location.js](https://github.com/yannickcr/eslint-plugin-react/blob/add052f9d9fdc6dc32051bded1b6339f71b29a0a/lib/rules/jsx-closing-bracket-location.js), I'll see if I can figure it out.

**Comment by silvenon** [comment] 2015-11-24 02:30
After the last atom-lint update it's not happening anymore, not sure if that's a fix or just silencing the error?

**Comment by Arcanemagus** [comment] 2015-11-24 02:53
v3.3.8 of atom-linter would have fixed this.
(v3.3.9 fixes a bug where the last character of the range was cut off)

**Comment by silvenon** [comment] 2015-11-24 03:13
Yeah, v3.3.8 (I missed those last 2 updates). Everything is working perfectly so far, thanks :+1:

**Comment by nadeemja** [comment] 2016-05-06 13:07
Hi,

I'm getting a similar error now with the latest version.

    Error: Column start (29) greater than line length (25)
    Error: Column start (29) greater than line length (25)
        at Object.rangeFromLineNumber (/Users/Nadeem/.atom/packages/linter-eslint/node_modules/atom-linter/lib/index.js:194:11)
        at /Users/Nadeem/.atom/packages/linter-jscs/src/linter-jscs.js:184:33
        at Array.map (native)
        at Object.lint (/Users/Nadeem/.atom/packages/linter-jscs/src/linter-jscs.js:179:39)
        at promises.push.Promise.then._this.emitter.emit.linter (/Users/Nadeem/.atom/packages/linter/lib/linter-registry.js:63:26)
        at /Users/Nadeem/.atom/packages/linter/lib/linter-registry.js:62:23
        at Set.forEach (native)
        at LinterRegistry.lint (/Users/Nadeem/.atom/packages/linter/lib/linter-registry.js:60:18)
        at /Users/Nadeem/.atom/packages/linter/lib/linter.coffee:98:16
        at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
        at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
        at /Users/Nadeem/.atom/packages/linter/lib/editor-linter.js:80:22
        at /Users/Nadeem/.atom/packages/linter/lib/helpers.coffee:23:18

Please advise on how to troubleshoot. 

Thanks,

Nadeem

**Comment by Arcanemagus** [comment] 2016-05-06 17:10
@nadeemja Please file a new issue as that is a generic error that can be caused by a myriad of different issues in `eslint` and it's plugins so each case is unique and there is no point in spamming the other people in this thread with debugging it :wink:

When filing the issue a copy of the file that triggers the error, as well as your `eslint` configuration, and the dependencies + devDependencies section of your `package.json` will be necessary to track this down.
