### ISSUE TITLE
Feature: Allow fixes to be directly applied without resorting to the console

### ISSUE THREAD

**Issue by pke** [AtomLinter/linter-eslint#477] opened 2016-03-09 13:05 UTC
I'd be nice if fixes, when available, could be applied in the linter status bar for each entry (a small wrench icon after the entry could mark such errors/warnings).
Also in the source popup the fix could be made visible.

A keyboard short-cut like `MOD+1` could apply the fix, or `MOD+SHIFT+1` fix all similar errors/warnings.
Much like the Eclipse IDE's Java Dev Tools "QuickFix" works.

**Comment by steelbrain** [comment] 2016-03-09 13:17
Dupe of https://github.com/AtomLinter/linter-ui-default/issues/44 :)

**Closed by steelbrain** 2016-03-09 13:17 UTC

**Comment by pke** [comment] 2016-03-09 14:44
Hmm. Was not clear from the title.

**Comment by Arcanemagus** [comment] 2016-03-09 17:07
@pke are you using Nuclide? Linter (which is what @steelbrain is talking about) doesn't have support for the Fix API released yet.

**Comment by pke** [comment] 2016-03-09 17:11
I am using Atom. I am burned child with Nuclide. It rendered my atom useless once in the past.
So we first need a public API from Linter to display the eslint fixes in the UI?

**Comment by Arcanemagus** [comment] 2016-03-09 17:14
Correct, `linter-eslint` provides the fixes in its messages, but Linter itself (released version) simply ignores them.

**Comment by pke** [comment] 2016-03-09 18:27
Which package is providing the fix command at the moment?

I'd like to put the fix button in the linter-ui and create a PR. Never coded a atom plugin though.

**Comment by steelbrain** [comment] 2016-03-09 18:30
If you wanna add it yourself, have a look at [`lib/ui/message-element.js`](https://github.com/atom-community/linter/blob/35847e4c4893f264861967207570cc51c9ccdabb/lib/ui/message-element.js)

**Comment by pke** [comment] 2016-03-09 18:42
Found it already, thanks
