### ISSUE TITLE
Lint error/warning message sticks if you fix an error too quickly

### ISSUE THREAD

**Issue by OddEssay** [AtomLinter/linter-eslint#627] opened 2016-07-01 13:43 UTC
Very frequently(2 or 3 times an hour), I find that the error raised from ESLint get "stuck" in Atom because I've typed a fix to the problem raise, but the linter hasn't noticed.

When I type in other parts of the file, the message doesn't dismiss.

If I go to where the error is described as existing, and edit the text there (Ie, delete a character, put the same character back) the message closes as expected.

The error occurs on 3 different Macs, all with up to date Atom installs. Happy to provide additional details on request.

![atom-eslint-bug](https://cloud.githubusercontent.com/assets/837227/16523095/83b2a644-3f99-11e6-94a5-00b4af0afcf4.png)

**Comment by Arcanemagus** [comment] 2016-07-01 19:08
Duplicate of https://github.com/steelbrain/linter/issues/1002.

The tl;dr is that the final fix is waiting till the new UI is released.

**Closed by Arcanemagus** 2016-07-01 19:08 UTC
