### ISSUE TITLE
Failed to activate the linter-eslint package - packageName is required

### ISSUE THREAD

**Issue by marcoms** [AtomLinter/linter-eslint#269] opened 2015-11-15 15:34 UTC
```
packageName is required
```

stack trace follows

```
Error: packageName is required
    at Object.install (/home/marcoms/.atom/packages/linter-eslint/node_modules/atom-package-deps/lib/main.js:19:27)
    at Object.activate (/home/marcoms/.atom/packages/linter-eslint/lib/main.js:34:34)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:170:19)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:333:19
    at /usr/share/atom/resources/app.asar/src/config.js:588:20
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:773:29)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:565:19)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:226:14)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:162:14)
    at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by marcoms** [comment] 2015-11-15 15:35
Turns out this happens only after updating. Once the editor is restarted it runs fine

**Comment by steelbrain** [comment] 2015-11-15 15:35
Dupe of #268

**Closed by steelbrain** 2015-11-15 15:36 UTC
