### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by juanmaia** [AtomLinter/linter-eslint#252] opened 2015-10-30 21:29 UTC
I'm getting this error on console.
I'm using global `eslint` and my .eslintrc file has this content:
```
{
  "extends": "airbnb"
}
```

<img width="1440" alt="screen shot 2015-10-30 at 19 27 11" src="https://cloud.githubusercontent.com/assets/638601/10858477/836951e2-7f3c-11e5-90e5-a82bf56fe22b.png">

**Comment by Arcanemagus** [comment] 2015-10-30 21:47
Are you on the latest version of `linter-eslint`? (v3.2.1)

**Comment by juanmaia** [comment] 2015-10-30 22:02
Yes.

**Comment by Arcanemagus** [comment] 2015-10-30 23:37
Looks like `TextEditor.indentationForBufferRow` isn't properly checking return values and attempts to use the results of the TokenizedBuffer before checking if it was actually tokenized properly. This is probably an upstream Atom bug, but just in case do you have a file to reproduce this with?

**Comment by juanmaia** [comment] 2015-10-31 04:21
I pasted all airbnb rules content inside my `.eslintrc` file and the problem persisted.
https://raw.githubusercontent.com/1hella/eslint-config-airbnb-es5/master/.eslintrc

When I removed the `parser` line it works just fine.
```"parser": "babel-eslint", ```

**Comment by juanmaia** [comment] 2015-10-31 04:22
@Arcanemagus It does happen in every file.

**Comment by ksmithut** [comment] 2015-10-31 18:25
Looks like you need to install babel-eslint: `npm install --save-dev babel-eslint`

**Comment by juanmaia** [comment] 2015-10-31 18:31
I have everything installed guys.

**Comment by steelbrain** [comment] 2015-11-14 00:55
Fixed by v5.0.0

**Closed by steelbrain** 2015-11-14 00:55 UTC

**Comment by glued** [comment] 2015-11-14 18:26
This issue started to appear for me in 5.0.0 but didn't happen in 4.0.0

**Comment by steelbrain** [comment] 2015-11-14 18:27
@glued That is very weird, Can you open a separate issue for it?
