### ISSUE TITLE
Invalid position given by 'semi'

### ISSUE THREAD

**Issue by brawner** [AtomLinter/linter-eslint#1315] opened 2020-01-08 00:08 UTC
Encountered this issue when deriving from airbnb-base. Code was just missing a semicolon as shown below.

ESLint returned a point that did not exist in the document being edited.
Rule: `semi`
Requested start point: 6:24 - 6:26

```javascript
/* eslint-disable no-alert, no-console, no-var, linebreak-style, prefer-arrow-callback,
   prefer-template, no-restricted-syntax, quote-props, prefer-destructuring */

var fnName = function () {
  var prefix = ''
  console.log(prefix);
};
```

.eslintrc.js
```javascript
module.exports = {
  env: {
    browser: true,
    es6: true,
    node: true,
  },
  extends: [
    'airbnb-base',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
  },
  parserOptions: {
    ecmaVersion: 2018,
  },
  rules: {
  },
};

```

Debug information:
```json
{
  "atomVersion": "1.42.0",
  "linterEslintVersion": "8.5.5",
  "linterEslintConfig": {
    "autofix": {
      "fixOnSave": false,
      "ignoreFixableRulesWhileTyping": false,
      "rulesToDisableWhileFixing": []
    },
    "global": {
      "eslintrcPath": "\"C:/Users/Stephen Brawmner/.atom/packages/linter-eslint/airbnb.eslintrc\"",
      "globalNodePath": "\"C:/Users/Stephen Brawner/AppData/Roaming/npm\"",
      "useGlobalEslint": false
    },
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.flow",
      "source.babel",
      "source.js-semantic"
    ],
    "lintHtmlFiles": false,
    "disabling": {
      "disableWhenNoEslintConfig": true,
      "rulesToSilenceWhileTyping": []
    },
    "advanced": {
      "disableEslintIgnore": false,
      "disableFSCache": false,
      "showRuleIdInMessage": true,
      "eslintRulesDirs": [],
      "localNodeModules": ""
    }
  },
  "eslintVersion": "6.8.0",
  "hoursSinceRestart": 0.8,
  "platform": "win32",
  "eslintType": "local project",
  "eslintPath": "C:\\Users\\Stephen Brawner\\workspace\\ci\\windows_docker_resources\\node_modules\\eslint",
  "editorScopes": [
    "source.js",
    "comment.block"
  ]
}
```

**Comment by npdev453** [comment] 2020-01-20 22:38
dup
https://github.com/AtomLinter/linter-eslint/issues/1312#issuecomment-576450682

**Comment by Arcanemagus** [comment] 2020-01-23 17:30
Duplicate of #1312

**Closed by Arcanemagus** 2020-01-23 17:30 UTC
