### ISSUE TITLE
Invalid position given by 'no-multiple-empty-lines'

### ISSUE THREAD

**Issue by Nick930826** [AtomLinter/linter-eslint#788] opened 2017-01-20 03:15 UTC
ESLint returned a point that did not exist in the document being edited.
Rule: `no-multiple-empty-lines`
Requested range: 345:1

Debug information:
```json
{
  "atomVersion": "1.11.2",
  "linterEslintVersion": "8.0.0",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDir": "",
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": []
  },
  "eslintVersion": "2.13.1",
  "hoursSinceRestart": 8.3,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "/Users/cxy/code/weixiaobao/VE/node_modules/eslint"
}
```

**Comment by IanVS** [comment] 2017-01-20 03:41
This is a duplicate of https://github.com/AtomLinter/linter-eslint/issues/687.  Please upgrade your version of ESLint to `3.5.0` or above.

**Closed by IanVS** 2017-01-20 03:41 UTC
