### ISSUE TITLE
eslint extends is not working

### ISSUE THREAD

**Issue by dijs** [AtomLinter/linter-eslint#445] opened 2016-02-18 20:26 UTC
Error:
`Error: Cannot find module 'eslint-config-airbnb'`

Seems like it cannot find the locally installed modules for eslint.

Project structure:
```
node_modules
   babel
   babel-eslint
   eslint
   eslint-config-airbnb
   eslint-plugin-react
src
   stuff.js
.eslintignore
.eslintrc.js
package.json
```

**Comment by Arcanemagus** [comment] 2016-02-18 20:35
I am unable to reproduce this with this setup: [linter-eslint_GH445.zip](https://github.com/AtomLinter/linter-eslint/files/136892/linter-eslint_GH445.zip)

**Comment by dijs** [comment] 2016-02-18 20:51
Well this is frustrating... I cannot reproduce it with the test project either. But I am still getting the issue in my other project with that same setup.

Here is my stack trace, do you see anything obvisouly wrong?

```
Error: Cannot read config package: eslint-config-airbnb
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: <User Dir>/projects/<project>/.eslintrc.js
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at loadPackage (<User Dir>/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (<User Dir>/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (<User Dir>/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:385:18)
    at <User Dir>/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (<User Dir>/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:309:28)
```

**Comment by Arcanemagus** [comment] 2016-02-18 21:07
Are you able to share the exact code you are seeing this issue with?

**Comment by dijs** [comment] 2016-02-18 22:03
It is not a specific piece of code, the linter is failing with any javascript file.

**Comment by Arcanemagus** [comment] 2016-02-18 22:16
That's not entirely true, as you said you can't reproduce it with the setup above.

You can start debugging this yourself by placing a breakpoint [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/src/main.js#L128) to see whether it is even being called at all, and [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/src/main.js#L141) to check the output getting returned to `linter-eslint` from `eslint`.

**Comment by IanVS** [comment] 2016-02-18 22:28
I notice that it is using the version of ESLint that comes bundled with linter-eslint, which means it can't find a locally installed version of ESLint and you're not using a global version.

**Comment by dijs** [comment] 2016-02-18 22:30
I thought it was proper to *not* use a global eslint.

**Comment by Arcanemagus** [comment] 2016-02-18 22:31
That's true, but for some reason in your error trace it's failing to find the locally installed version.

If you can't share the whole codebase can you at least share your `eslint` config, and `package.json` dependencies?

**Comment by IanVS** [comment] 2016-02-18 22:31
Normally yes, the ideal is to use the local eslint. Have you run npm
install lately?

**Comment by dijs** [comment] 2016-02-18 22:34
[linter-eslint_GH445.zip](https://github.com/AtomLinter/linter-eslint/files/137081/linter-eslint_GH445.zip)

This new version has what you asked for. The problem is, it does not fail...

**Comment by Arcanemagus** [comment] 2016-02-18 22:44
Silly question, but have you restarted Atom since running `npm install` in your project's folder?

**Comment by dijs** [comment] 2016-02-18 22:47
Yes, a few times.

**Comment by dijs** [comment] 2016-02-18 22:51
Why would linter-eslint need to bundle eslint?

**Comment by Arcanemagus** [comment] 2016-02-18 23:02
Specifically for when a locally installed version can't be found, and use of the global version is disabled. It's meant as a last resort for when a user has only the most basic of `eslint` setups.

**Comment by dijs** [comment] 2016-02-18 23:07
So the problem is that in my project, linter-eslint cannot find my local eslint?

**Comment by IanVS** [comment] 2016-02-19 03:16
Yes, for some reason.

**Comment by qimingweng** [comment] 2016-02-21 20:49
I seem to be getting this too, linter-eslint is not finding the local eslint...

**Comment by Arcanemagus** [comment] 2016-02-22 22:53
@dijs Can you put a `console.log(ESLintDirectory)` above [this line](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/lib/worker-helpers.js#L63), to see what it thinks the path it should try loading from is?

@qimingweng without a folder structure or a zip file with the files to reproduce this it's rather hard to debug from "not working".

**Comment by dijs** [comment] 2016-02-22 23:09
Where would I see the logging?

**Comment by dijs** [comment] 2016-02-22 23:26
It seems that when I install the airbnb module within the linter-eslint directory, all is well...

I cannot figure why this is though.

**Comment by Arcanemagus** [comment] 2016-02-22 23:32
Because it's still failing to use the local project's version, and you don't seem to have a global version, so it's falling back to the embedded version.

**Comment by dijs** [comment] 2016-02-22 23:33
But when I open the dev tools, it is not even logging the directory. It fails before that line.

**Comment by dijs** [comment] 2016-02-22 23:36
```
Error: Cannot find module 'eslint-config-airbnb/base'
Referenced from: /Users/<user>/.atom/packages/linter-eslint/package.json
```

I think it is trying to read/load packages from linter-eslint's package.json which includes airbnb, and is failing since airbnb only gets downloaded in dev mode, not production mode.

**Comment by Arcanemagus** [comment] 2016-02-22 23:44
Correct, but as I said the only reason it is trying to do that is because for some reason it is failing to find the installation local to your project and is falling back on the `eslint` bundled with this package.

**Comment by dijs** [comment] 2016-02-22 23:45
By the way, it is also failing in the linter-eslint project also.

**Comment by dijs** [comment] 2016-02-22 23:46
I am open to debug more, do you have any other ideas/logging I could try?

**Comment by dijs** [comment] 2016-02-22 23:49
Boom. I think I have steps to reproduce the issue.

1. `apm remove linter-eslint`
2. `apm install linter-eslint`
3. restart atom
4. `atom ~/.atom/packages/linter-eslint`
5. Open lib/worker-helpers.js
6. If linter is enabled/running this is where it blows up for me

**Comment by Arcanemagus** [comment] 2016-02-22 23:55
That _should_ fail, since `apm install` doesn't install the `devDependencies`.

**Comment by Arcanemagus** [comment] 2016-02-22 23:56
The `dependencies` of `linter-eslint` have what it needs to _run_, the `devDependencies` have what you also need to _develop_ it, which is what you are essentially trying to do there.

**Comment by Arcanemagus** [comment] 2016-02-22 23:57
Can you put a `console.log` before [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/lib/worker-helpers.js#L68) saying something like "failed to load local installation, falling back to bundled"?

**Comment by Arcanemagus** [comment] 2016-02-23 00:00
Could you possibly PM me a link to the exact folder you are seeing this in on [Atom's Slack](http://atom-slack.herokuapp.com/)?

**Comment by dijs** [comment] 2016-02-23 00:02
Sure, I am waiting for access to that slack.

This doesn't make sense to me. If I install linter-eslint and want to "lint" it's project source code, I feel I should be able to. If it errors out there, it *doesn't* have the dependencies it needs to run.

**Comment by Arcanemagus** [comment] 2016-02-23 00:03
`apm` is only meant to install Atom packages, the fact that it _somewhat_ acts the same as `npm` is just a side effect of them wrapping an old version of `npm` internally.

**Comment by Arcanemagus** [comment] 2016-02-23 01:01
After some back and forth testing, it turns out this is the resurgence of https://github.com/AtomLinter/linter-eslint/issues/294, which is fixed in https://github.com/AtomLinter/linter-eslint/pull/409, which simply hasn't been released yet :stuck_out_tongue:.

**Comment by qimingweng** [comment] 2016-02-23 18:04
Is this is the same as #447?

**Comment by dijs** [comment] 2016-02-23 18:05
Yes, I believe so.

**Comment by Arcanemagus** [comment] 2016-02-23 18:15
Quite possibly, I'll be pushing out a release shortly that includes the fix.

**Comment by Arcanemagus** [comment] 2016-02-23 18:36
Can you try v6.1.0? It _should_ fix this.

**Comment by dijs** [comment] 2016-02-23 18:38
Looks like it works! Thanks for the help.

**Comment by Arcanemagus** [comment] 2016-02-23 18:40
Glad to hear it, marking this as closed.

**Closed by Arcanemagus** 2016-02-23 18:40 UTC
Labels: bug

**Comment by noahehall** [comment] 2016-08-08 22:37
updating worked for me
