### ISSUE TITLE
Invalid position given by 'flowtype-errors/show-errors'

### ISSUE THREAD

**Issue by joncursi** [AtomLinter/linter-eslint#1149] opened 2018-07-05 14:20 UTC
ESLint returned a point that did not exist in the document being edited.
Rule: `flowtype-errors/show-errors`
Requested start point: 776:4 - 776:10

Debug information:
```json
{
  "atomVersion": "1.28.0",
  "linterEslintVersion": "8.4.1",
  "linterEslintConfig": {
    "lintHtmlFiles": false,
    "useGlobalEslint": false,
    "showRuleIdInMessage": true,
    "disableWhenNoEslintConfig": true,
    "eslintrcPath": "",
    "globalNodePath": "",
    "advancedLocalNodeModules": "",
    "eslintRulesDirs": [],
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "fixOnSave": false,
    "scopes": [
      "source.js",
      "source.jsx",
      "source.js.jsx",
      "source.babel",
      "source.js-semantic"
    ],
    "rulesToSilenceWhileTyping": [],
    "rulesToDisableWhileFixing": [],
    "ignoreFixableRulesWhileTyping": false
  },
  "eslintVersion": "5.0.1",
  "hoursSinceRestart": 0.8,
  "platform": "darwin",
  "eslintType": "local project",
  "eslintPath": "/Users/joncursi/Sites/cheddur/core/node_modules/eslint",
  "editorScopes": [
    "source.js.jsx",
    "meta.brace.curly.js"
  ]
}
```

**Comment by Arcanemagus** [comment] 2018-07-05 15:51
This is caused by a bug in [`flowtype-errors/show-errors`](https://github.com/amilajack/eslint-plugin-flowtype-errors), you'll want to compare the point it requested with the document you were editing at the _exact_ state that it was in when this triggered. Once you've found that try to get a minimal reproduction figured out and file an issue on their repo.

If you are having trouble figuring that out or don't think it's an issue with that plugin please create a Gist (or repository) with the necessary files to reproduce this and we can take a look at it.

I'm going to close this issue for now as it's _extremeley_ unlikely to be a bug here, but if you feel that it is and have provided a way to reproduce it we can always re-open it. Thanks for taking the time to file an issue!

**Closed by Arcanemagus** 2018-07-05 15:51 UTC
