### ISSUE TITLE
Code is being linted despite eslint-disable and eslint-disable-line

### ISSUE THREAD

**Issue by MrSnappingTurtle** [AtomLinter/linter-eslint#903] opened 2017-05-08 20:10 UTC
## Issue Type
Bug

## Issue Description
Neither `eslint-disable` nor `eslint-disable-line`seem to be working. In the following example (using `eslint-disable-line`), it's still stating `Duplicate identifier 'enableProdMode'.`:

![screen shot 2017-05-08 at 1 27 10 pm](https://cloud.githubusercontent.com/assets/8148243/25823817/1cc677b4-33f2-11e7-9a80-a65e9499ebf1.png)

## Debug Output
```
Atom version: 1.16.0
linter-eslint version: 8.1.7
ESLint version: 3.19.0
Hours since last Atom restart: 0
Platform: darwin
Using bundled fallback ESLint from: /Users/dennissubachev/.atom/packages/linter-eslint/node_modules/eslint
Current file's scopes: [
  "source.ts",
  "meta.import.ts",
  "meta.block.ts",
  "punctuation.definition.block.ts"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by Arcanemagus** [comment] 2017-05-08 20:49
`import` doesn't work like `require`, all `import` statements are bundled together into a single run. I thought that could would actually error in the first place as I belive `import` statements _must_ come before any other statements.

I'm guessing that the reason ESLint is still warning you about them is due to this behavior of all `import` statements being grouped.

**Comment by Arcanemagus** [comment] 2017-05-08 21:07
Ah, tested this locally: The messages you are talking about are _parsing_ errors (going back to that being invalid code), handling of rule disabling is done after the code has been successfully parsed.

From the odd comments surrounding those `import`s it looks like the code this is from is meant to be handled by some sort of templating/transpiling engine which conditionally includes parts of the code. It sounds like you will need to disable ESLint on these "pre-parse" files.

Since this is reproducible with ESLint itself, and we are matching its behavior I'm marking this as closed: 
![image](https://cloud.githubusercontent.com/assets/427137/25825346/94714d7a-33f7-11e7-8d2a-20ee7fe9b32e.png)

If you have further questions though I'll try to help!

**Closed by Arcanemagus** 2017-05-08 21:07 UTC
