### ISSUE TITLE
Column start (1) greater than line length (0)

### ISSUE THREAD

**Issue by ericeslinger** [AtomLinter/linter-eslint#691] opened 2016-09-09 18:18 UTC
This may be the same as #689, or at least the same error reported at the end of it. Here's a screenshot: (click to enlarge)

<a href="https://cloud.githubusercontent.com/assets/255715/18397843/cfa21a78-767e-11e6-85b6-ba41017c5ef1.png"><img width="400" alt="screen shot 2016-09-09 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/255715/18397843/cfa21a78-767e-11e6-85b6-ba41017c5ef1.png"></a>

and I've attached the file that is causing the error. It looks like line 55- perhaps in the rule about having too many sequential blank lines.

[model.js.zip](https://github.com/AtomLinter/linter-eslint/files/464564/model.js.zip)

**Comment by Arcanemagus** [comment] 2016-09-09 18:21
Duplicate of #687, see that for a link to the root ESLint issue.

**Closed by Arcanemagus** 2016-09-09 18:21 UTC
Labels: duplicate
