### ISSUE TITLE
linter-eslint not run on file with extension .js.erb

### ISSUE THREAD

**Issue by thaichor** [AtomLinter/linter-eslint#854] opened 2017-03-20 07:13 UTC
## Issue Type
Bug

## Issue Description
When I open file with extension .js.erb, eslint doesn't run on it.

So in List of scopes to run ESLint on. I added ', source.js.erb' to default string. However it stills not run.

**Comment by IanVS** [comment] 2017-03-20 11:10
Can you please provide the output of the `Linter-eslint Eslint: debug` command when you have one of those files open? That will help us troubleshoot.

**Comment by thaichor** [comment] 2017-03-21 02:32
Sorry for inconvenience. How do I do ```Linter-eslint Eslint: debug```?

I open atom editor, then I open console with ```CMD + OPT + I``` and I pass ```Linter-eslint Eslint: debug```, But it got syntax error.

**Comment by thaichor** [comment] 2017-03-21 02:37
I run command in terminal, it works fine. ```eslint . --ext .js,.js.erb```

**Comment by IanVS** [comment] 2017-03-21 02:39
You need to run that command in the command palete. cmd+shift+p.

**Comment by thaichor** [comment] 2017-03-21 02:43
I got 'Error: Path must be a string. Received undefined' notification. and in console log

```
helpers.js:66 Uncaught (in promise) TypeError: Cannot read property 'atomVersion' of undefined(…)(anonymous function) @ helpers.js:66step @ helpers.js:204(anonymous function) @ helpers.js:204_tickCallback @ internal/process/next_tick.js:103
```

**Comment by IanVS** [comment] 2017-03-21 02:45
What version of linter-eslint are you using? Can you try upgrading to the
latest version?

**Comment by thaichor** [comment] 2017-03-21 02:46
linter-eslint version 8.1.4
eslint version 3.18.0
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

**Comment by thaichor** [comment] 2017-03-21 02:50
When I run ```linter debug```. I got this.

Current File scopes: 
  - *
  - source.js.rails source.js.jquery
  - 

So should I change source.js.erb to source.js.rails?

**Comment by thaichor** [comment] 2017-03-21 02:52
I got it to work now by replace 'source.js.erb' with 'source.js.rails source.js.jquery'. Is this normal?

**Comment by Arcanemagus** [comment] 2017-03-21 23:03
@thaichor `source.js.rails` should be sufficient, it sounds like you might have some odd language packages in there, but as long as you have that in the config it should be fine.

It's normal to need to configure it to run on that syntax as it isn't a standard one to run JS linters on. Note that this will run on _all_ files of that scope, including ones that you may not have configured the project for so be prepared for some potentially odd results on unconfigured projects.

**Comment by Arcanemagus** [comment] 2017-03-22 21:45
Closing this as it sounds like your situation is resolved. Report back if you are still having issues!

**Closed by Arcanemagus** 2017-03-22 21:45 UTC

**Comment by leggsimon** [comment] 2017-07-09 19:26
@Arcanemagus I'm getting the same issue here, this is a somewhat meaningful stacktrace. 
```
Path must be a string. Received undefined TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at Object.findESLintDirectory (/Users/simon.legg/.atom/packages/linter-eslint/src/worker-helpers.js:65:22)
    at process.<anonymous> (/Users/simon.legg/.atom/packages/linter-eslint/src/worker.js:60:26)
    ...
```
With lots of console logs (😏) I've traced it [this line in the `findESLintDirectory` function](https://github.com/AtomLinter/linter-eslint/blob/bb5321b25259740dcdfd40282a94adb14e358400/src/worker-helpers.js#L63) where `projectPath` is `null` (which is weird because I would've at least expected `undefined` not that that would work either) and so `path.join()` blows up.

**Comment by IanVS** [comment] 2017-07-10 02:06
@leggsimon, great find, that's definitely a bug, and I apologize that `Path to the local node_modules folder` is a confusing setting.  It's intended to be used by folks with a non-standard directory structure.  But as you discovered, it's broken when a relative path is used.  

I think the problem is that we are not passing `projectPath` into the [`findESLintDirectory` here](https://github.com/AtomLinter/linter-eslint/blob/master/src/worker.js#L58).  If you're willing to submit a PR with the fix and ideally a spec as well, that would be awesome!
