### ISSUE TITLE
Cascading is not working

### ISSUE THREAD

**Issue by piranna** [AtomLinter/linter-eslint#502] opened 2016-03-23 10:23 UTC
`linter-eslint` is not preserving [cascading](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy) and only use the project global `.eslintrc.json` file ignoring the path specific one.

**Comment by Eschon** [comment] 2016-03-23 10:50
This is probably a duplicate of #296

**Comment by Arcanemagus** [comment] 2016-03-23 18:53
Quite possibly, can you detail your exact structure? Or even better upload a .zip of a minimal reproduction case? None of the information in that thread lead to a reproduction so it's been undiagnosed so far...

**Comment by SpainTrain** [comment] 2016-03-27 19:42
I noticed that cascading was not quite working correctly in one of my projects.  I `git bisect`ed to find the guilty commit, and came up with 0a80eac3e0b514fe9dae0055493703b601e22461

I created a min reproduction that appears to work at https://github.com/SpainTrain/502-repro

**Comment by Spy-Seth** [comment] 2016-05-04 10:16
I confirm the issue. My sub `.eslintrc.js` file are ignored too. The upper file is correctly used (who is not on the root of my project):

```
foo
└── bar
    ├── .eslintrc.js        <-- Correctly used
    └── baz
        └── .eslintrc.js    <-- Ignored
        └── myfile.js
```

**Comment by suchipi** [comment] 2016-06-29 19:54
Running into this same issue.

**Comment by rajington** [comment] 2016-07-20 19:52
As a workaround, restarting atom fixed the issue for me.

**Comment by Arcanemagus** [comment] 2016-09-28 21:42
Marking this as closed, I'm unable to reproduce using the repo that @SpainTrain setup with `eslint@3.6.1`, which is essentially identical to the setup that @Spy-Seth proposes.

Interestingly, if I force `eslint@2.5.1`, which seems to have been current when this issue was first filed, it has _major_ issues and seems to actually use the ESLint worker from a different window I had open as it complains about config from _that_ project. So it seems around when this was filed _something_ funky was going on, but it is fixed now.

If anyone is still seeing this on current versions of `linter-eslint`, with `eslint@3.6.1` installed in the project please file a new issue with a zip attached of a folder where you can reproduce this in.

**Closed by Arcanemagus** 2016-09-28 21:42 UTC
