### ISSUE TITLE
Uncaught Error: spawn ENOMEM

### ISSUE THREAD

**Issue by zdiehlio** [AtomLinter/linter-eslint#930] opened 2017-06-02 01:35 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package 8.2.1

### Stack Trace

Uncaught Error: spawn ENOMEM

```
At internal/child_process.js:313

Error: spawn ENOMEM
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.fork (child_process.js:70:10)
    at new Task (/opt/atom/resources/app/src/task.js:43:1)
    at initializeESLintWorker (/packages/linter-eslint/main.js:136:21)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.1 
emmet 2.4.3 
intentions 1.1.2 
linter 2.0.0 
linter-eslint 8.2.1 
linter-ui-default 1.6.0 
```

**Comment by skylize** [comment] 2018-05-08 15:41
Closing as duplicate of #927. Let us know if you have any further info that shows this to be a different isssue.

**Closed by skylize** 2018-05-08 15:41 UTC
