### ISSUE TITLE
Support for eslint configuration file formats

### ISSUE THREAD

**Issue by Moeriki** [AtomLinter/linter-eslint#334] opened 2015-11-25 11:52 UTC
Since eslint 1.10.0 you can put your eslint config into different file formats.

http://eslint.org/blog/2015/11/eslint-v1.10.0-released/

> v1.10.0 introduces the ability to use configuration files in different formats. Instead of the regular .eslintrc file, you can use a JavaScript (.eslintrc.js), a YAML file (.eslintrc.yml or .eslintrc.yaml), or a JSON file (.eslintrc.json). We are formally deprecating use of the .eslintrc extensionless configuration file format in favor the format-specific versions. Don't worry, we'll still support .eslintrc files for a long time, but we'd like to encourage everyone to move to the new file formats as you'll get advantages such as syntax highlighting and error detection with many editors.

**Comment by steelbrain** [comment] 2015-11-25 13:26
Dupe of #327 and #317

**Comment by Arcanemagus** [comment] 2015-11-25 19:46
This should have been fixed in v5.2.2, you might want to make sure your `linter-eslint` install is up to date.

**Comment by Moeriki** [comment] 2015-11-26 09:04
When I tick off "Disable when ESLint config not found" it works with linter-eslint 5.2.4.

**Comment by IanVS** [comment] 2015-11-27 01:25
@Moeriki, what do you mean by "tick off"?  Check or uncheck?

**Comment by Moeriki** [comment] 2015-11-30 12:44
Sorry that wasn't clear indeed. I meant uncheck.

**Comment by Arcanemagus** [comment] 2015-11-30 16:01
So you're saying that it will read that format, but it only runs if that option is disabled?

It's this possibly related to https://github.com/AtomLinter/linter-eslint/pull/343?

**Comment by Spy-Seth** [comment] 2015-12-04 13:17
Yes I've use the same tricks to have the plugin working again after renaming my `.eslintrc` file to `.eslintrc.js`

**Comment by Arcanemagus** [comment] 2015-12-04 17:44
@Spy-Seth your issue is definitely related to #343.

@Moeriki were you having issues with a `.eslintrc.js` file?

**Comment by Moeriki** [comment] 2015-12-04 17:55
When `Disable when no ESLint config is found` is checked, linter-eslint is disabled.

When it is unchecked, linter-eslint is enabled.

**Comment by Arcanemagus** [comment] 2015-12-04 17:57
That would mean that it is unable to find a config in any format, how are you specifying your `eslint` config?

**Comment by Moeriki** [comment] 2015-12-04 17:58
Config file is in project root and called `.eslintrc.js`.

**Comment by Arcanemagus** [comment] 2015-12-04 18:03
Marking this as closed as that has been fixed in #343, I'll see if there is any reason a release hasn't been pushed out yet including that and push one out if not.

**Closed by Arcanemagus** 2015-12-04 18:03 UTC

**Comment by Arcanemagus** [comment] 2015-12-04 18:53
v5.2.5 is released that includes this fix.

**Comment by Moeriki** [comment] 2015-12-04 18:57
Awesome thanks a lot! Can confirm it's fixed :)

**Comment by stevgouws** [comment] 2017-03-28 09:08
Hi, just a question, does linter-eslint also support eslintrc.json? From what I could see it doesn't look like it, is that correct? Thanks.

**Comment by stevgouws** [comment] 2017-03-28 09:49
Nevermind, I see it does support it, sorry found the issue, it was conflicting with a .eslintrc.js file in a parent folder.
