### ISSUE TITLE
Column start greater than line length 2

### ISSUE THREAD

**Issue by vadirn** [AtomLinter/linter-eslint#690] opened 2016-09-09 17:04 UTC
Related to #689.

The issue is reproduced even with `"react/require-extension": 0` rule. I can reproduce the issue when entering new line after line 114:

![2016-09-09 23 02 56](https://cloud.githubusercontent.com/assets/195229/18395723/9f0a445e-76e1-11e6-8c1b-e7df5b010565.gif)

[eslintrc.txt](https://github.com/AtomLinter/linter-eslint/files/464438/eslintrc.txt)
[package.json.txt](https://github.com/AtomLinter/linter-eslint/files/464443/package.json.txt)
[index.js.txt](https://github.com/AtomLinter/linter-eslint/files/464445/index.js.txt)

**Comment by Arcanemagus** [comment] 2016-09-09 17:10
This is a duplicate of #687 😉.

**Closed by Arcanemagus** 2016-09-09 17:10 UTC
