### ISSUE TITLE
.eslintrc.js

### ISSUE THREAD

**Issue by iamstarkov** [AtomLinter/linter-eslint#327] opened 2015-11-22 19:44 UTC
eslint 1.10 [added new types of configuration](http://eslint.org/blog/2015/11/eslint-v1.10.0-released/#configuration-file-formats) files `.eslintrc.js`, `.eslintrc.yml` and `.eslintrc.json`. And `.eslintrc` will be deprecated in first major update.

I think linter-eslint should start support them too.

**Comment by steelbrain** [comment] 2015-11-22 19:45
Dupe of #317

**Closed by steelbrain** 2015-11-22 19:45 UTC

**Comment by iamstarkov** [comment] 2015-11-22 19:46
sorry, was looking into open issues
