### ISSUE TITLE
Files reformatted after save when linter-eslint is used with "JavaScript with JSX" or "JavaScript" syntax

### ISSUE THREAD

**Issue by joshdick** [AtomLinter/linter-eslint#219] opened 2015-09-29 16:05 UTC
I am using OS X Yosemite 10.10.5, Atom 1.0.19, linter-eslint 3.0.2, and linter 1.6.0.

When linter-eslint is used in conjunction with the "JavaScript with JSX" or "JavaScript" Atom syntax definitions, my files are corrupted upon saving them (indentation gets messed up, trailing commas sometimes get added, etc.)

The corruption marks the editor as dirty but doesn't end up getting saved to the file, so I have to do a ⌘-Z immediately after doing a ⌘-S to undo the corruption changes and restore my file to the point at which it was (just) saved.

The behavior stops if I independently disable linter-eslint, OR if I change the syntax definition away from "JavaScript with JSX" or "JavaScript" to "JavaScript by SubtleGradient", which I also have installed.

**Comment by steelbrain** [comment] 2015-11-14 01:02
Although the error is unclear, there's a good chance this has been fixed by v5.0.0

**Closed by steelbrain** 2015-11-14 01:02 UTC

**Comment by joshdick** [comment] 2015-11-16 18:47
The behavior didn't change with v5, but it appears that disabling `linter-jscs` (which I'm no longer actively using) also fixes this issue. There is some odd interaction with `linter-jscs`, the the JavaScript syntax definitions mentioned earlier, and `linter-eshint`, but since I have a workaround, I suppose this GitHub issue can remain closed.

**Comment by Arcanemagus** [comment] 2015-11-16 19:15
`linter-eslint` in no way modifies your files, so it's impossible for this to have been the cause, on the other hand `linter-jscs` _does_ have a "Fix on save" option that, if enabled, will attempt to automatically fix issues it finds so I would not be surprised at all that that is the source of this file changing.

**Comment by joshdick** [comment] 2015-11-21 19:17
@Arcanemagus That makes perfect sense, thanks for the clarification!
