### ISSUE TITLE
Linter trying to lint jade files

### ISSUE THREAD

**Issue by danqing** [AtomLinter/linter-eslint#747] opened 2016-11-11 06:10 UTC
## Issue Type

Bug

## Issue Description

ESLint jumps in for .jade files?

![screen shot 2016-11-10 at 10 10 18 pm](https://cloud.githubusercontent.com/assets/5134133/20206023/84ada542-a792-11e6-8f43-e499b9366db2.png)

**Comment by IanVS** [comment] 2016-11-11 13:13
It can if it is configured to.  Can you provide the info the issue template asked for? Specifically the output of the debug command.

**Comment by Arcanemagus** [comment] 2016-12-06 17:45
Closing due to a lack of response, if you are still having issues please start by including the debug information requested above, thanks!

**Comment by Nateowami** [comment] 2017-02-15 13:08
For the sake of anyone else who faces this issue, updating Atom and linter-eslint fixed this issue for me. Sounds obvious/trivial, but it isn't when Atom says all plugins are up to date (plugin updates were apparently incompatible with Atom 1.9.9, so it simply said they were up to date) and doesn't say it needs to update (Atom doesn't have automatic updates on Linux--though I thought it would say when it needed an update).

**Comment by Nateowami** [comment] 2017-02-15 13:18
Well nevermind. It seemed to go away, even after file saves, but it's back again. Here's the output from `LinterEslint: Debug`:
```
Atom version: 1.14.2
linter-eslint version: 8.1.1
ESLint version: 3.15.0
Hours since last Atom restart: 0.1
Platform: linux
Using bundled fallback ESLint from /home/nathaniel/.atom/packages/linter-eslint/node_modules/eslint
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```
And `Editor: Log Cursor Scope`:
```
source.pug
meta.first-class.pug
storage.type.import.include.pug
```

**Comment by IanVS** [comment] 2017-02-15 13:25
Thanks for the details, @Nateowami.  I'm not so familiar with Jade files, can you provide an example of a small jade file that reproduces the issue?

**Comment by Nateowami** [comment] 2017-02-15 13:28
It trips up on this (specifically the html in the doctype) saying "Parsing error: Unexpected token html":
```
doctype html
html
  head
    title=title
  body
    .post-wrapper
      block content
```
This file is named layout.pug -- just in case the file extension is used in detecting source type.

**Comment by Arcanemagus** [comment] 2017-02-16 18:08
@Nateowami I'm unable to reproduce this unfortunately.

What package are you using to provide support for the Jade language? I tried both `atom-jade` and `language-jade`, but both of those don't recognize `.pug` files, and `.jade` files are correctly marked with the scope of `source.jade` while you are saying you are getting `source.pug`.

**Comment by Nateowami** [comment] 2017-02-17 12:21
I have both `atom-jade` and `language-pug`. I didn't realize I had both though, so I'm disabling `atom-jade`.

It seems the bug is inconstant. It doesn't always try to lint it. At times in the past I've had it trying to lint the whole file, but I haven't been using it in a good while.

I think I may have figured something out. Using an `=` sign in the file makes it be detected as JS. Right where the equals sign is the cursor scope is (among other things) `source.js`. This makes *some* sense given that JavaScript can be embedded in Jade/Pug templates. A file as simple as `div=var` will trigger it.

However, after a file is no longer detected as JS, the linting errors don't go away. This can serve to mask the source of the problem.

**Comment by Arcanemagus** [comment] 2017-09-16 23:44
I'm closing this as an external bug, there really isn't anything we can do about this here. The language package you are using should be updated so that JavaScript code embedded in the file is marked as a particular embedded scope instead of the regular JavaScript scope.

**Closed by Arcanemagus** 2017-09-16 23:44 UTC
Labels: Unconfirmed Bug

**Comment by skylize** [comment] 2017-09-17 02:41
@Nateowami 
> I have both atom-jade and language-pug. I didn't realize I had both though, so I'm disabling atom-jade.

There's a good chance these 2 language packages are competing with each other to parse jade. The question of whether the bug arises is may depend on which one wins the race and gets to do your parsing. I'm guessing the pug plugin can handle jade files just fine? If so, it makes sense to just uninstall the jade plugin, which will probably fix this error for you as a side effect..

**Comment by Nateowami** [comment] 2017-09-18 01:51
@skylize I haven't been using Atom for a while, but when I was, I disabled atom-jade, and it didn't fix the problem. So I don't think they were not racing.
