### ISSUE TITLE
Massive memory leak

### ISSUE THREAD

**Issue by AlexKvazos** [AtomLinter/linter-eslint#347] opened 2015-12-03 04:58 UTC
Come on guys, this has to be addressed please. I don't know when but I bump a lot with "The worker has died, please wait" and i get no linter for some time. It is getting annoying and today my computer shows this "Your system is out of memory".

![screen shot 2015-12-02 at 22 52 04](https://cloud.githubusercontent.com/assets/4448627/11552271/3a5a74ec-9948-11e5-9db4-024f1360f0a5.png)

**Comment by steelbrain** [comment] 2015-12-03 05:00
Dupe of  #278 #290 #295 #301 #302 #303 #326 #341 and #345

**Comment by steelbrain** [comment] 2015-12-03 05:01
Also see https://github.com/AtomLinter/linter-eslint/issues/330

**Closed by steelbrain** 2015-12-03 05:00 UTC

**Comment by Arcanemagus** [comment] 2015-12-03 07:29
To sum up all those issues: It's an Atom bug that is fixed in the v1.3.0 betas.
