### ISSUE TITLE
eslintignore having no effect

### ISSUE THREAD

**Issue by DanPurdy** [AtomLinter/linter-eslint#495] opened 2016-03-21 11:30 UTC
Hi guys,

My `.eslintignore` is ironically seeming to be ignored by this plugin

Atom `v1.7.0-beta0`,
linter-eslint `7.1.1`

simplified app structure

```
app -
  |
   models
    |_ abstract-model.js
    |_ abstract-model.spec.js
.eslintrc
.eslintignore
```

eslintignore contents:
```
**/*.spec.js
dist/
karma.conf.js
```

The problem is that abstract-model.spec.js is still being linted in atom which i don't want to happen for now due to not currently using the linter friendly assertions from `chai-lint`.

When using from the command line though it is ignored,
`node_modules/eslint/bin/eslint.js app/core/model/**.*.js -c .eslintrc` It runs fine and ignores the file

when i strip out the eslintignore file and run
`node_modules/eslint/bin/eslint.js app/core/model/**.*.js -c .eslintrc --ignore-pattern **/*.spec.js` 
it's also fine.

I've tried clearing out linter-eslint's node_modules folder and reinstalled the dependencies too

My `.eslintrc` file is below too if that helps

```
---
  extends:
    - airbnb/base
    - angular
  # ============================================================================
  # Rules
  # ============================================================================
  rules:

    valid-jsdoc:
      - 1
      -
        requireParamDescription: true
        requireReturnDescription: true
        requireReturn: false
        prefer:
          return: "returns"
        preferType:
          String: "string"
          Number: "number"
          Boolean: "boolean"
          object: "Object"
    require-jsdoc:
      - 1
      -
        require:
          FunctionDeclaration: true
          MethodDefinition: true
          ClassDeclaration: true

  # ============================================================================
  # Angular Specific
  # ============================================================================

    angular/module-getter: 0 # buggy
    angular/module-setter: 0 # buggy
    angular/no-service-method: 0 # Service methods allow us to use es6 classes

  # ============================================================================
  # Environment
  # ============================================================================
  env:
    browser: true
    es6: true

  # ============================================================================
  # Parser
  # ============================================================================
  parser: 'babel-eslint'
```

linter-eslint in my config
```
"linter-eslint":
    globalNodePath: "/Users/danpurdy/.nvm/versions/node/v4.2.4"
```

But all the settings visible in the settings panel
<img width="824" alt="screen shot 2016-03-21 at 11 34 51" src="https://cloud.githubusercontent.com/assets/1386054/13917495/16922674-ef59-11e5-9065-61c5b3364803.png">

**Comment by IanVS** [comment] 2016-03-21 12:28
This appears to be a duplicate of #448, which was recently fixed and will be included in the next release.

Also, `.eslintignore` now behaves like `.gitignore`, so you should be able to replace `**/*.spec.js` with just `*.spec.js`.

**Closed by IanVS** 2016-03-21 12:28 UTC

**Comment by DanPurdy** [comment] 2016-03-21 12:55
Ah great, thanks.. The issue didn't show in my search oddly.. Oh well, thanks.

**Comment by Arcanemagus** [comment] 2016-03-21 17:44
@IanVS any reason not to push out a patch release with that fix?

**Comment by IanVS** [comment] 2016-03-21 18:32
Nope, I'm just not so familiar with the process and figured I'd leave it to you.  :smiley:

**Comment by Arcanemagus** [comment] 2016-03-21 18:35
https://github.com/AtomLinter/linter-eslint/blob/master/CONTRIBUTING.md#building

:stuck_out_tongue:

**Comment by IanVS** [comment] 2016-03-21 18:36
. . . also I was being lazy.

**Comment by Arcanemagus** [comment] 2016-03-21 18:37
I can do it if you want, but that section of the CONTRIBUTING.md file should be updated if there is something missing so it would be good to get a fresh set of eyes on it.

**Comment by IanVS** [comment] 2016-03-21 18:38
Alright, I'll do it tonight.  A bit swamped at the moment.

**Comment by IanVS** [comment] 2016-03-22 01:55
`v7.1.3` is published with the fix.
