### ISSUE TITLE
 Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by sr1994lu** [AtomLinter/linter-eslint#1025] opened 2017-09-18 06:12 UTC
## Issue Type
Bug

## Issue Description
There is always no problem.
However, introducing atom-beta 1.21.0 resulted in an error.
Perhaps it may be my mistake.

```
Error while running ESLint: Cannot convert undefined or null to object.
<div style="white-space: pre-wrap">Cannot convert undefined or null to object
<hr />TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at /Users/sr1994lu/.atom/packages/linter-eslint/src/worker.js:27:41
    at Map.forEach (native)
    at updateFixableRules (/Users/sr1994lu/.atom/packages/linter-eslint/src/worker.js:26:21)
    at lintJob (/Users/sr1994lu/.atom/packages/linter-eslint/src/worker.js:61:3)
    at process.<anonymous> (/Users/sr1994lu/.atom/packages/linter-eslint/src/worker.js:101:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)</div>
```

**Comment by sr1994lu** [comment] 2017-09-18 06:13
I am suffering from being unable to develop...

**Comment by Arcanemagus** [comment] 2017-09-18 06:36
Can you update to v8.3.1 and see if you are still hitting this issue? It's likely this is a different case of #1021.

**Comment by Arcanemagus** [comment] 2017-09-18 06:39
Duplicate of #1023

**Closed by Arcanemagus** 2017-09-18 06:39 UTC
