### ISSUE TITLE
Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by design1online** [AtomLinter/linter-eslint#833] opened 2017-03-01 16:30 UTC
I was able to fix this error by going into the plugin directory and installing the following packages:

`npm install eslint-plugin-react eslint-config-airbnb eslint-plugin-jsx-a11y eslint-plugin-import`

**Comment by Arcanemagus** [comment] 2017-03-01 17:23
I'm not sure where people keep getting this idea, but installing things in this package's folder is _not_ the way to fix this issue.

Can you post the debugging information as requested in the issue template? That will tell us if it is falling back to the ESLint bundled with this package, or attempting to use one in your current project.

**Comment by ctrom** [comment] 2017-08-16 17:42
After updating to Atom 1.19.1, the linter fails to run and I am getting this error in the console:


```
[Linter] Error running ESLint Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.load (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:134:29)
    at Array.forEach (native)
    at Object.loadAll (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config/plugins.js:162:21)
    at Object.load (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config/config-file.js:541:21)
    at loadConfig (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/config.js:260:26)
    at processText (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/Users/ctrom/.atom/packages/linter-eslint/node_modules/eslint/lib/cli-engine.js:754:26)
    at lintJob (/Users/ctrom/.atom/packages/linter-eslint/src/worker.js:14:20)
    at process.<anonymous> (/Users/ctrom/.atom/packages/linter-eslint/src/worker.js:52:22)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by petrdanecek** [comment] 2017-09-11 07:49
I'm experiencing the same issue inAtom 1.20.0-beta5 x64 on Windows7.
I'm using the Oracle VM with Centos6. The project home folder is exporte to windows via NFS. 
The eslint works properly in the CLI, the code is validated and I get bunch of errors and warnings. As the eslint works in CLI I'm pretty sure that the problem is related to Atom and the way how it loads the npm module.

ATOM is unable to load the eslint-plugin-react. The plugin is installed locally. It seems that the .eslintrc.json is found as trying to set the wrong path cause some other errors to Atom. So .eslintrc.json is detected, but the locally installed eslint-plugin-react is not loaded from project folder.
Maybe I would need to copy the module directly into the atom apm folder? Any thoughts.

(nodejs)(betaenv) []$ node -v
v7.7.1
(nodejs)(betaenv) []$ npm -v
4.1.2

**Comment by Arcanemagus** [comment] 2017-09-17 03:10
Without the debugging information requested above _and_ in the issue template, we can't even begin to diagnose whether this is an issue in this package or in your local system's setup.

Please post the output of running the `Linter Eslint: Debug` command, thanks!

**Comment by nikolaevigor** [comment] 2017-09-24 12:22
I have similar problem.

> Error while running ESLint: Failed to load plugin jsxa11y: Cannot find module 'eslint-plugin-jsx-a11y

Linter ESLint: Debug

```
linter-eslint debugging information
Atom version: 1.20.1
linter-eslint version: 8.3.2
ESLint version: 4.7.2
Hours since last Atom restart: 0.1
Platform: darwin
Using local project ESLint from: /.../node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "punctuation.terminator.statement.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by Arcanemagus** [comment] 2017-09-25 23:28
@nikolaevigor What does `npm ls eslint-plugin-jsx-a11y` show when run from your project folder?

**Comment by nikolaevigor** [comment] 2017-09-26 15:05
eslint-plugin-jsx-a11y@5.1.1
      react-scripts@1.0.10
        eslint-plugin-jsx-a11y@5.0.3

I was able to solve this issue with reinstalling atom package and configuring my dev dependencies this way:

    "devDependencies": {
      "babel-eslint": "^8.0.0",
      "eslint": "^3.19.0",
      "eslint-config-airbnb": "^15.0.1",
      "eslint-loader": "^1.8.0",
      "eslint-plugin-import": "^2.7.0",
      "eslint-plugin-jsx-a11y": "^5.0.1",
      "eslint-plugin-react": "^7.1.0",
      "husky": "^0.14.3",
      "react-scripts": "1.0.10"
    }

Key moment is that I downgraded ESLint to 3.19.0

**Comment by Arcanemagus** [comment] 2017-09-26 17:17
@nikolaevigor I tried replicating that with the following files, but was unable to get a broken state:
[linter-eslint_GH833-nikolaevigor.zip](https://github.com/AtomLinter/linter-eslint/files/1334088/linter-eslint_GH833-nikolaevigor.zip)

Note that `react-scripts` includes `eslint-config-react-app@1.0.5`, which requires `eslint@^3.19.0` _only_, so your dependency list doesn't allow `eslint@4` in the first place. Ignoring that though linting seems to work perfectly with the above files so I'll need your help getting a broken state to test with 😉.

**Comment by nikolaevigor** [comment] 2017-09-26 18:28
@Arcanemagus Sorry, didn't quite understand what you need to get a broken state.

I found my commit, that fixed everything:

![screenshot at sep 26 21-19-28](https://user-images.githubusercontent.com/3702281/30876822-6758179c-a300-11e7-8e3b-00724a6cdd73.png)

I reverted `devDependencies` to `"eslint": "^4.1.1",`, then I've run `npm ls eslint-plugin-jsx-a11y`

Output:

    react-scripts@1.0.10
      eslint-plugin-jsx-a11y@5.0.3

So, I think it's pretty clear, that it is related to `eslint-config-react-app@1.0.5` (I was not aware, that it works only with `eslint@^3.19.0`).

**Comment by Arcanemagus** [comment] 2017-09-26 19:27
If that's the commit that "fixed everything" then that is perfectly understandable. You previously didn't have `eslint-plugin-jsx-a11y` listed as a dependency, when it is a required `peerDependency` of `eslint-config-airbnb`.

I'm going to mark this issue as a configuration error and close it as @design1online and @ctrom have stopped responding and your issue wasn't related to `linter-eslint` at all. Thanks for the information!

**Closed by Arcanemagus** 2017-09-26 19:27 UTC
Labels: question

**Comment by Guichaguri** [comment] 2017-10-06 16:28
I also have the same issue. It starts with an error saying that I do not have `eslint-plugin-react`, if I install it, it says I don't have `babel-eslint`, then the same thing happens for `eslint-config-defaults/configurations/eslint`, etc

I'm using Atom 1.21.0 and linter-eslint 8.3.2

Also, the `Linter Eslint: Debug` command does not show up in the Command Palette list

**Comment by Arcanemagus** [comment] 2017-10-06 18:33
@Guichaguri please file a new issue, there's no reason to spam the others in this thread diagnosing what is wrong with your setup. 😉

**Comment by kimskovhusandersen** [comment] 2019-11-25 12:56
I added the two following dependencies to package.json: 
        "eslint": "^4.19.1",
        "eslint-plugin-react": "^7.12.4"

and then ran "npm install"
That solved the issue in atom.
