### ISSUE TITLE
How to configure eslint with eslint-plugin-wordpress?

### ISSUE THREAD

**Issue by junglized** [AtomLinter/linter-eslint#984] opened 2017-08-11 22:51 UTC
## Issue Type
Question

## Issue Description
Error in developers mode console
Error running ESLint Error: ENOENT: no such file or directory, scandir 'C:\XAMPP\htdocs\owl\js\rules'

## Installation and configuration steps taken
It seems I don't know how to configure eslint for Atom correctly. There are quite a few settings but am I setting everything up properly?

So, from the beggining:

I installed Atom: 1.19.0 on Windows 10 x64. Then I installed node.js 6.11.2 to create npm folder in c:\Users\USER\AppData\Roaming\, worked. Then I followed instructions on installing eslint globally:` npm i -g eslint`. I installed eslint-plugin-wordpress for Wordpress linting rules from [here](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress), also globally: `npm install -g eslint-plugin-wordpress`. And then I installed eslint for Atom and tried to configure it. After that I created `.eslintrc.json` file and ut it in c:\XAMPP\. According to Wordpress eslint plugin docs I should put below code into .eslintrc.json
```
{
	"extends": "plugin:wordpress/recommended",
	"plugins": [
		"wordpress"
	]
}
```
So I did. I keep my projects in c:\XAMPP\htdocs. Below is a screenshot of my configuration of eslint:

![image](https://user-images.githubusercontent.com/26525585/29234249-9b698746-7eed-11e7-8827-f54313915c97.jpg)
 
When I save the file with .js extension I see the following error in developers tools console:

![error](https://user-images.githubusercontent.com/26525585/29234321-11c33784-7eee-11e7-946e-7e3b4e37d067.jpg)

Where c:\XAMPP\htdocs\owl\ is one of the added project folders where linted file is being located. Due to lack of knowledge I think I don't know what I'm doing with the config. Has anyone got any idea how to make it running? Any help much appreciated. Best regards, Dan.

**Comment by Arcanemagus** [comment] 2017-08-16 18:05
* ESLint Rules Dir: This overrides any configuration specification of where rules are located and is generally a _very bad idea_ unless you know _exactly_ what you are doing and have a very odd edge case that needs this setting. In your case you definitely shouldn't need this.
* .eslintrc Path: This shouldn't be breaking anything, but also isn't needed as ESLint will search parent directories for a configuration by default. Leaving this blank should work for you know, and will keep it working when you eventually graduate to configuring your projects in the recommended way 😉.
* Global Node Installation Path: This likely isn't breaking anything either, but also shouldn't be necessary unless for some reason `linter-eslint` is unable to run `npm`.

All of that being said, I think your settings shouldn't be breaking things here. This looks to be a bug with the published version of `eslint-plugin-wordpress`, but the current state of that repository works _entirely_ different from the published version where this bug is happening, so you might want to file an issue [over there](https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/issues) about getting a release?

**Comment by Arcanemagus** [comment] 2017-08-16 18:11
Actually, looks like this has already been filed over there, please follow https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/issues/106 for more information.

**Comment by Arcanemagus** [comment] 2017-08-16 18:11
Duplicate of https://github.com/WordPress-Coding-Standards/eslint-plugin-wordpress/issues/106

**Closed by Arcanemagus** 2017-08-16 18:11 UTC
Labels: External

**Comment by junglized** [comment] 2017-08-19 17:57
**@Arcanemagus**, thanks to your hint I managed to sort the problem out. I installed eslint-config-wordpress along with eslint-plugin-wordpress and everything works like a charm.

Thank you and best regards.
