### ISSUE TITLE
"Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by atombender** [AtomLinter/linter-eslint#128] opened 2015-06-25 18:58 UTC
`linter-eslint` sometimes passes `undefined` to `TextEditor.indentationForBufferRow()`:

```
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:136 [Linter-ESLint] error while linting file
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:137 Cannot read property 'match' of undefined
/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:138 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:647:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2220:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2192:19)
  at /Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:108:44
  at Array.map (native)
  at /Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:104:18
  at exports.allowUnsafeNewFunction (/Users/alex/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:101:13)
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/alex/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/alex/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/alex/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

Atom 1.0, `linter-eslint@1.0.8` and `eslint@0.23.0`.

**Comment by scottcorgan** [comment] 2015-06-25 20:05
I can confirm this error with the same module versions. Disabling linter-eslint removed the error popping up in Atom.

**Comment by mcmouse** [comment] 2015-06-25 20:18
Confirming that this error is happening on all of my .es6 files.
OSX 10.9.5
Linter 1.0.4
Linter-ESLint 1.0.8

**Comment by atombender** [comment] 2015-06-25 20:28
Should have mentioned that it started happening after upgrading to Atom 1.0 today.

**Comment by iam4x** [comment] 2015-06-25 22:41
Could you please give me an example file and `.eslintrc` to reproduce?

**Comment by mcmouse** [comment] 2015-06-25 23:59
Trace:
```
[Linter-ESLint] error while linting file
/Users/tomlagie/.atom/packages/linter-eslint/lib/linter-eslint.coffee:137 Cannot read property 'match' of undefined
/Users/tomlagie/.atom/packages/linter-eslint/lib/linter-eslint.coffee:138 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:647:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2220:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2192:19)
  at /Users/tomlagie/.atom/packages/linter-eslint/lib/linter-eslint.coffee:108:44
  at Array.map (native)
  at /Users/tomlagie/.atom/packages/linter-eslint/lib/linter-eslint.coffee:104:18
  at exports.allowUnsafeNewFunction (/Users/tomlagie/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/tomlagie/.atom/packages/linter-eslint/lib/linter-eslint.coffee:101:13)
  at /Users/tomlagie/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /Users/tomlagie/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/Users/tomlagie/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/Users/tomlagie/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /Users/tomlagie/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

File:
~~~JS
/**
 * Set up cameras
 */

/* globals THREE, _ */

import ThreeHub from './threeHub.es6';

export default class ThreeCameras {
  constructor() {
    _.extend(this, {
      main: new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 1000),
      cube: new THREE.CubeCamera(1, 1000, 256)
    });

    this.setCameraPositions();
  }
  
  setCameraPositions() {
    this.main.position.set(0, 0, 50);
    this.main.lookAt(new THREE.Vector3(0, 0, 0));

    this.cube.renderTarget.minFilter = THREE.LinearMipMapLinearFilter;
  }

  setup() {
    ThreeHub.scene.addAll(this);
    ThreeHub.cameras = this;
  }
}
```

`.eslintrc`
```
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "rules": {
    "strict": 0,
    "quotes": [1, "single", "avoid-escape"],
    "complexity": [1, 3],
    "max-depth": [1, 4]
  }
}
```

**Comment by iam4x** [comment] 2015-06-26 10:39
The extension of your file is `.es6` @mcmouse ?

**Comment by atombender** [comment] 2015-06-26 14:39
I'm not @mcmouse, but I'll add that my files are `.js`. Here's my `.eslintrc`:

```
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "env": {
    "browser": true,
    "node": true,
    "es6": true
  },
  "settings": {
    "ecmascript": 6,
    "jsx": true
  },
  "ecmaFeatures": {
    "blockBindings": true,
    "jsx": true
  },
  "rules": {
    "strict": 1,
    "quotes": 0,
    "semi": 1,
    "no-unused-vars": 1,
    "camelcase": 0,
    "new-cap": 0,
    "handle-callback-err": 0,
    "no-empty": 0,
    "no-alert": 0,
    "no-underscore-dangle": 0,
    "no-unused-expressions": 1,
    "no-use-before-define": 0,
    "no-process-exit": 0,
    "no-constant-condition": 0,
    "no-loop-func": 0,
    "no-new": 0,
    "react/display-name": 0,
    "react/jsx-boolean-value": 1,
    "react/jsx-quotes": 1,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-props": 0,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 0,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/wrap-multilines": 1
  }
}
```

**Comment by nicosommi** [comment] 2015-06-26 16:20
+1 to this

This is my stack trace

```javascript
TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/tokenized-buffer.js:647:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/usr/share/atom/resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/usr/share/atom/resources/app.asar/src/text-editor.js:2220:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/usr/share/atom/resources/app.asar/src/text-editor.js:2192:19)
  at /home/intag/.atom/packages/linter-eslint/lib/linter-eslint.coffee:108:44
  at Array.map (native)
  at /home/intag/.atom/packages/linter-eslint/lib/linter-eslint.coffee:104:18
  at exports.allowUnsafeNewFunction (/home/intag/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/home/intag/.atom/packages/linter-eslint/lib/linter-eslint.coffee:101:13)
  at /home/intag/.atom/packages/linter/lib/editor-linter.coffee:79:24
  at /home/intag/.atom/packages/linter/lib/editor-linter.coffee:78:25
  at Set.forEach (native)
  at EditorLinter._lint (/home/intag/.atom/packages/linter/lib/editor-linter.coffee:72:26)
  at EditorLinter.lint (/home/intag/.atom/packages/linter/lib/editor-linter.coffee:66:18)
  at /home/intag/.atom/packages/linter/lib/editor-linter.coffee:22:37
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by mcmouse** [comment] 2015-06-26 16:55
@iam4x Correct, that particular file is `threeCameras.es6`

**Comment by Kureev** [comment] 2015-06-26 23:08
Same here. Highlighting first line of the file and throws subj error
```
├── linter@1.0.8
└── linter-eslint@1.0.8
```
eslint version `0.20.0`

**Comment by d4rkr00t** [comment] 2015-06-28 08:16
I think it happens when you use babel-eslint parser. I have had same issue and removing babel-eslint parser helped me.

**Comment by Kureev** [comment] 2015-06-28 10:49
@d4rkr00t But if I remove it, would eslint parse my ES6 syntax?

**Comment by d4rkr00t** [comment] 2015-06-28 11:25
It would work, except some cases like @decorators.

**Comment by Kureev** [comment] 2015-06-28 13:09
@d4rkr00t that's bad. Is there any other way to make it work?

**Comment by d4rkr00t** [comment] 2015-06-28 14:09
Hm, could you check if babel-eslint installed in your project? Because i've just reinstalled it and everything works fine for my now.

And could you just run eslint from cli:

```bash
./node_modules/.bin/eslint **/*.js
```

**Comment by iam4x** [comment] 2015-06-28 18:35
Oh, that's why I can't reproduce. Look on the README we added a note about using `babel-eslint` you have to install it localy to your project with `eslint`

I need to catch this and display a nice alert.

**Comment by atombender** [comment] 2015-06-28 18:36
Why is this a requirement? We don't want to pollute our projects with what are essentially personal settings. This coincidentally means you can't work on an open-source project unless everyone on the project also installs `eslint`, `babel-eslint` and all plugins (eg., `eslint-plugin-react`).

**Comment by Kureev** [comment] 2015-06-28 18:38
Agree with @atombender, I'd like to keep ESLint global, tell me where should I look?

**Comment by AsaAyers** [comment] 2015-06-28 18:40
Keeping it global is a bad idea. When the next developer checks out your code and runs eslint, whether from the command line or through his IDE it's going to blow up when they don't have it globally installed.

You should configure your *project*, not your *machine*

**Comment by iam4x** [comment] 2015-06-28 18:45
Do you use the `Use global eslint` option @atombender @Kureev ?

While I agree @AsaAyers, if the `use global eslint` option is used it should look for global plugins too.

**Comment by Kureev** [comment] 2015-06-28 18:47
@iam4x yes, I'm using global `eslint`

**Comment by iam4x** [comment] 2015-06-28 18:48
I'm talking about (last option):

![screen shot 2015-06-28 at 20 47 28](https://cloud.githubusercontent.com/assets/893837/8397754/02ba97f2-1dd7-11e5-935c-324fac37c157.png)

**Comment by Kureev** [comment] 2015-06-28 18:49
@iam4x Sure, it catches ESLint, but doesn't work with local `babel-eslint`

**Comment by iam4x** [comment] 2015-06-28 18:50
Oh that's normal, if you use global eslint option, `babel-eslint` should be installed globally too.

**Comment by Kureev** [comment] 2015-06-28 18:51
Yeah, the point is that if I run from console `eslint <some/folder/with/es6/files>` it works

**Comment by Kureev** [comment] 2015-06-28 18:51
But for some reason it doesn't work if I use this plugin

**Comment by atombender** [comment] 2015-06-28 18:52
@iam4x: Yes, I am. (`linter-eslint` (1.0.8) doesn't have such a settings page on my machine. I had to put it in Atom's `config.cson`.) I also have both `eslint` and `babel-eslint` installed globally.

@AsaAyers: That's like saying if the next developer checks out my code and wants to edit an icon his IDE is going to blow up because he doesn't have Photoshop installed.

If you want to use an _optional_ developer tool X with a project, it's perfectly appropriate to ask the user to install tool X themselves. Some of these choices are personal, and editor-dependent.

If a team of developers wants to institute some team-wide setting, they can install it into `package.json`. But everyone else should have the option of maintaining their toolchain globally installed.

I work on >10 Node projects. Upgrading ESLint and various Linter plugins would involve having to `npm install` them into each project, _then_ running `npm shrink`, _then_ committing, and _then_ either pushing or (if I'm not the owner) doing a pull request. That's just an unacceptable burden for something that's basically an editor setting.

**Comment by Kureev** [comment] 2015-06-28 18:56
@atombender :+1:

**Comment by AsaAyers** [comment] 2015-06-28 19:02
> wants to edit an icon his IDE is going to blow up because he doesn't have Photoshop installed

This is a really stupid comparison with no basis in reality. I have `eslint` installed, but I don't have `babel-eslint`, so it literally will not run when I checkout your code. If I attempt to edit an icon it will ask me which program I want to use.

> If you want to use an optional developer

This is our core disagreement. A linter is not an optional tool. It should be part of your project (with a .eslintrc) and ideally should be part of your build system.

I've never considered the "burden" to be a valid argument. The fact is that if your project doesn't contain it's dependencies you're doing it wrong. I belive if linting is optional you're doing it wrong. I've downloaded projects where they don't run at all because the original developer didn't like the "burden" of installing things into projects, so everything was global and undocumented.

**Comment by atombender** [comment] 2015-06-28 19:08
It's actually a very valid comparison. We are talking about tools that are used to develop a project. Some people might use Photoshop, others might use GIMP. These are tools that aren't needed to compile or run a project; they are not _dependencies_. They are part of a daily workflow that is highly individual.

Your ideological reasons for pushing people to pollute their `package.json` file are just that, ideological. Please don't dictate which tools I have to use.

If you want to push an ideology on a _team_, that's fine. Let them install the tools through `package.json`. Just don't foister such a policy on everyone.

Also: You're obviously not checking in `.eslintrc` with the project if you're not including it in `package.json`, so why would `eslint` actually _blow up_? It might not be able to parse your code, but that's a local configuration issue.

**Comment by AsaAyers** [comment] 2015-06-28 19:10
I'm not going to argue with you any further. This is already off topic.

**Comment by atombender** [comment] 2015-06-28 21:26
@iam4x, the "Use Global Eslint" setting suddenly appeared after I restarted Atom. A package reloading bug in Atom, perhaps?

**Comment by gyzerok** [comment] 2015-06-29 05:51
So is there a way to fix this issue?

**Comment by iam4x** [comment] 2015-06-29 08:13
@atombender We had similar issues with the update of Linter to 1.0 API, some users have a cache you have to reload / restart Atom after any updates.

**Comment by iam4x** [comment] 2015-06-29 08:20
Published a fix for globally installed plugins, it should correctly works now.

**Comment by gyzerok** [comment] 2015-06-29 10:40
@iam4x still doesnt works

**Comment by iam4x** [comment] 2015-06-29 10:46
@gyzerok 

Works for me:

* `$ npm install -g eslint babel-eslint`

Use the option `Use global eslint installed` and `.eslintrc`:

```
{
  "parser": "babel-eslint"
}
```

What's your use-case?

**Comment by gyzerok** [comment] 2015-06-29 10:55
@iam4x Both deps installed globally. In package setting checked global usage. Same error.

**Comment by budjizu** [comment] 2015-06-29 11:23
The same issue. Trace:
```
/Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:135 [Linter-ESLint] error while linting file
/Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:136 Cannot read property 'match' of undefined
/Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:137 TypeError: Cannot read property 'match' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:647:23)
  at DisplayBuffer.module.exports.DisplayBuffer.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:818:35)
  at TextEditor.module.exports.TextEditor.indentLevelForLine (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2220:33)
  at TextEditor.module.exports.TextEditor.indentationForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2192:19)
  at /Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:107:44
  at Array.map (native)
  at /Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:103:18
  at exports.allowUnsafeNewFunction (/Users/budjizu/.atom/packages/linter-eslint/node_modules/loophole/lib/loophole.js:25:14)
  at Object.provider.lint (/Users/budjizu/.atom/packages/linter-eslint/lib/linter-eslint.coffee:100:13)
  at /Users/budjizu/.atom/packages/linter/lib/editor-linter.coffee:85:24
  at /Users/budjizu/.atom/packages/linter/lib/editor-linter.coffee:84:25
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/budjizu/.atom/packages/linter/lib/editor-linter.coffee:78:26)
  at EditorLinter.lint (/Users/budjizu/.atom/packages/linter/lib/editor-linter.coffee:72:18)
  at /Users/budjizu/.atom/packages/linter/lib/editor-linter.coffee:26:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1183:25
```

**Comment by Kureev** [comment] 2015-06-29 11:39
@iam4x Maybe you just think that you're using global modules and in fact you're using local ones instead?

**Comment by iam4x** [comment] 2015-06-29 11:40
@Kureev I'm going to try it again, but it was in a brand new folder :+1:

**Comment by Kureev** [comment] 2015-06-29 12:03
@iam4x You know, for me it also works, so mb it's somebody's personal issues. Thanks for the patch :+1:

**Comment by Kureev** [comment] 2015-06-29 12:05
@iam4x haha wow, it doesn't work again :open_mouth:

**Comment by Kureev** [comment] 2015-06-29 12:06
![image](https://cloud.githubusercontent.com/assets/2273613/8407558/10d7af8c-1e68-11e5-86e0-49f3cfbc9a87.png)

**Comment by atombender** [comment] 2015-06-29 16:16
@iam4x: Same here, unfortunately. I added some debug output to `linter-eslint`, and apparently it gets `0` as the line, and the `message` is: `Cannot find module 'babel-eslint'`.

Is there any reason why `linter-eslint` doesn't check the line number in the `eslint` output? Since the line number is 0, that results in the `Cannot read property 'match' of undefined` error, since you're asking for line -1.

**Comment by atombender** [comment] 2015-06-29 16:17
Note: `eslint` works fine on the command line, and `babel-eslint` is installed globally:

```
# npm list -g babel-eslint  
/usr/local/lib
└── babel-eslint@3.1.15 
```

**Comment by dcrockwell** [comment] 2015-06-30 00:05
+1

Like others, I have `eslint` and `babel-eslint` installed globally, but I'm getting the exact same output as @Kureev

**Comment by dcrockwell** [comment] 2015-07-02 00:35
The problem for me seemed to be that I didn't have local versions of `eslint` and `babel-eslint` installed.

Here are the steps I took to resolve the issue:

1. apm uninstall linter linter-eslint
2. npm i --save-dev eslint babel-eslint
3. apm install linter linter-eslint

**Comment by Kureev** [comment] 2015-07-02 12:20
@dcrockwell the point is that I don't want to install them locally just because plugin doesn't support it

**Comment by iam4x** [comment] 2015-07-05 17:51
Guys, I've published a new version which fixes the issue for me. Could you tell if it works for you?

https://github.com/AtomLinter/linter-eslint/commit/fff94ce250e5364eaddb2ed4154a859b4592bf07

**Comment by atombender** [comment] 2015-07-05 18:01
Uninstalled and reinstalled, and now it can't find NPM:

```
Error: Command failed: npm config get prefix
/bin/sh: npm: command not found
  at checkExecSyncError (child_process.js:1334:13)
  at execSync (child_process.js:1374:13)
  at Object.module.exports.findGlobalNPMdir (/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:191:21)
  at Object.module.exports.activate (/Users/alex/.atom/packages/linter-eslint/lib/linter-eslint.coffee:36:31)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

`npm` is installed via Homebrew:

```
# which npm
/usr/local/bin/npm
```

This is run via `/bin/sh`, which does have the right `PATH`:

```
# /bin/sh
sh-3.2$ which npm
/usr/local/bin/npm
```

Not sure why your change would cause this, though, as it just uses `execSync` instead of `exec`.

If I symlink `npm` and `node` into `/usr/bin`, everything works correctly. (Thanks!)

**Comment by iam4x** [comment] 2015-07-05 18:26
@atombender Do you start Atom with cli `atom .` ?

**Comment by atombender** [comment] 2015-07-05 18:32
No, from the dock.

**Comment by iam4x** [comment] 2015-07-05 18:33
That's why there's an issue with Atom, the correct bin path won't be set without starting atom from CLI.

**Comment by atombender** [comment] 2015-07-05 18:35
Well... why did it ever work before? Isn't this a problem that affects every single package that wants to shell out to some command?

**Comment by iam4x** [comment] 2015-07-05 18:36
@atombender No error was thrown because it was in a async call, but it should have happen.

And yes it affects every package from Atom, I should maybe add an option to set the path to ESLint. This will resolve everything in a nicer way.

**Comment by atombender** [comment] 2015-07-05 18:41
Adding a path setting would work, although this sounds like something that should be solved by Atom itself, otherwise every single package needs to solve it independently. Is there an open issue for it, do you know?

**Comment by iam4x** [comment] 2015-07-05 18:47
https://github.com/atom/atom/issues/3018#issuecomment-98505051

**Comment by iam4x** [comment] 2015-07-05 18:47
It's more an OSX issue I didn't know about.

**Comment by budjizu** [comment] 2015-07-05 19:11
Also npm not not found. Started atom cli `atom .`
```
Command failed: npm config get prefix
/bin/sh: npm: command not found
```

**Comment by iam4x** [comment] 2015-07-05 20:09
Pushed new version with `Global Node Path`, use `$ npm config get prefix` to find the good value.

**Comment by atombender** [comment] 2015-07-05 20:11
Super. That worked. Many thanks!

**Comment by budjizu** [comment] 2015-07-05 20:26
That works fine. Thanks!

**Comment by iam4x** [comment] 2015-07-05 20:28
I'll clean a bit the `README` and will close this so :)

**Closed** 2015-07-05 21:52 UTC
Labels: bug

**Comment by Jackong** [comment] 2015-11-14 06:10
cd ~/.atom/packages/linter-eslint && npm i babel-eslint

**Comment by Arcanemagus** [comment] 2015-11-14 08:12
@Jackong if you need additional plugins you should be installing `eslint` in your project or globally, _not_ modifying the version installed in this package.
