### ISSUE TITLE
[Linter-ESLint] Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.

### ISSUE THREAD

**Issue by csaintc** [AtomLinter/linter-eslint#154] opened 2015-07-10 15:15 UTC
getting the error: 

`[Linter-ESLint] Local/Global ESLint binary not found. Fallback to packaged one. Set binary in preferences.`

console output:

`Uncaught Error: write EPIPE`

`linter-eslint.js:126 [Linter-ESLint] no output from CLI`

`linter-eslint.js:127 eslint binary: /Users/cresten-admin/.atom/packages/linter-eslint/node_modules/.bin/eslint`

`linter-eslint.js:129 cwd: /Users/cresten-admin/.atom/packages/linter-eslint/lib`

**Comment by mnquintana** [comment] 2015-07-10 15:24
:+1: I've been getting this too since updating to 2.4.1.

**Comment by vramana** [comment] 2015-07-10 15:47
This is just duplicate of #149.( dont way about the name 2.3.0 ) @csaintc You can close this.

**Comment by joseluisq** [comment] 2015-07-10 17:30
`linter-eslint v2.4.1`

![image](https://cloud.githubusercontent.com/assets/1700322/8624652/2833de5e-26ff-11e5-96e1-66491ae2631c.png)

**Comment by dominicbarnes** [comment] 2015-07-10 21:04
This is happening for me too

**Comment by nkt** [comment] 2015-07-10 22:07
I've installed `1.x` version and it's still working fine, maybe it helps someone:
```sh
$ apm install linter-eslint@1.0.18
```

**Comment by iam4x** [comment] 2015-07-10 22:55
There's an issue with $PATH bin env not set correctly in Atom when it's not run from CLI. Let's keep the discussion into #149

**Closed by iam4x** 2015-07-10 22:55 UTC
