### ISSUE TITLE
Keep throw error and crash after v5.2.0

### ISSUE THREAD

**Issue by ZheFeng** [AtomLinter/linter-eslint#290] opened 2015-11-17 00:39 UTC
Keep throw error and crash after v5.2.0, below is the info I got from console:
<img width="1437" alt="screen shot 2015-11-17 at 11 38 54 am" src="https://cloud.githubusercontent.com/assets/1264113/11199221/dabb12fa-8d1f-11e5-8421-8e3132ecb0a1.png">

"(42104,0x7fff76106000) malloc: *** error for object 0x7fb4bd248ce0: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug "

**Comment by Arcanemagus** [comment] 2015-11-17 00:43
Duplicate of #278. See there for the resolution (update to electron in Atom, due in v1.3.0).

**Closed by Arcanemagus** 2015-11-17 00:43 UTC

**Comment by ZheFeng** [comment] 2015-11-17 00:45
Thanks

**Comment by Arcanemagus** [comment] 2015-11-17 00:46
If you don't mind using that beta release, that should fix this for you.
