### ISSUE TITLE
Lint xml files

### ISSUE THREAD

**Issue by onemen** [AtomLinter/linter-eslint#525] opened 2016-04-02 09:49 UTC
How do i configure linter-eslint to lint xml files using eslint-plugin-mozilla
i can do ti from the command line but it does not work from Atom

**Comment by Arcanemagus** [comment] 2016-04-04 22:40
Marking as a duplicate of #254, looks like that has more and more reason to be implemented...

**Closed by Arcanemagus** 2016-04-04 22:40 UTC
