### ISSUE TITLE
Worker died unexpectedly

### ISSUE THREAD

**Issue by Andreyco** [AtomLinter/linter-eslint#302] opened 2015-11-18 17:00 UTC
I experience this quite a lot, actually on 2 Mac machines, both running on 10.11.1.

I get 
```
[Linter-ESLint] Worker died unexpectedly
Check your console for more info. A new worker will be spawned instantly.
```
The only info found in console is this
```
ESLint Worker Info Object {
    stderr: "(2402,0x7fff7c1c6000) malloc: *** error for object 0x7fd4e843d980: pointer being freed was not allocated↵*** set a breakpoint in malloc_error_break to debug↵"
    stdout: ""
    __proto__: Object
}
```

Is anyone else experiencing this problem?

**Comment by steelbrain** [comment] 2015-11-18 17:08
Dupe of #301 https://github.com/AtomLinter/linter-eslint/issues/295 https://github.com/AtomLinter/linter-eslint/issues/290 and https://github.com/AtomLinter/linter-eslint/issues/278

**Closed** 2015-11-18 17:08 UTC
