### ISSUE TITLE
spawn calls from linter-eslint are slowing atom way down

### ISSUE THREAD

**Issue by jedwards1211** [AtomLinter/linter-eslint#1224] opened 2019-01-21 19:53 UTC
## Issue Type

Bug

## Issue Description

Atom was going so slow that it would take a second or two to respond to each keystroke.  I opened up the dev tools and profiled and found that `spawn` calls from `linter-eslint` were hogging the CPU.

Restarting generally seems to fix this, but it's frustrating.

[linter-eslint-slowness-profile.json.zip](https://github.com/AtomLinter/linter-eslint/files/2780329/linter-eslint-slowness-profile.json.zip)

![image](https://user-images.githubusercontent.com/1448194/51495944-b8cee980-1d83-11e9-869c-dd9e20f674e8.png)

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here
```

```
Atom version: 1.34.0
linter-eslint version: 8.4.1
ESLint version: 4.19.1
Hours since last Atom restart: 28.7
Platform: darwin
Using local project ESLint from: /Users/andy/clarity/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function-call.js",
  "string.quoted.single.js",
  "punctuation.definition.string.end.js"
]
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": [],
  "ignoreFixableRulesWhileTyping": false
}
```

**Comment by IanVS** [comment] 2019-01-22 17:39
Thanks for looking into this!  Would you like to take a crack at improving the performance?  It would be very welcome.

**Comment by jedwards1211** [comment] 2019-01-22 17:47
Yeah next time it happens I'll try to dig deeper into what's happening.  (It seems to happen after Atom has been running a long time?)  I'm really wondering why an async spawn call would take so long.  Not even sure if it's even linter-eslint's fault.  But I could at least make linter-eslint spawn less frequently if the spawn calls are slow to return.

**Comment by Arcanemagus** [comment] 2019-01-22 17:52
`linter-eslint` should only be spawning something _once_ per project. The trace you show above only shows that the `sb-exec` instance located in `linter-eslint` was being used... not that `linter-eslint` was the one using it. I would guess that that usage is a different provider you have installed that is also running on the same files.

**Comment by stadelmanma** [comment] 2019-02-19 19:13
I can also confirm the same behavior *appearing* to come from linter-eslint but only after Atom has been running for a day or two. This isn't a new problem, for awhile now I've had to restart Atom if it's been running too long but I didn't think to profile anything until today (which lead me here). 

For more context, I was editing Python source code when Atom began to lag as described above so perhaps that indicates something else is causing the actual problem.  did have a JS project collapsed in the treeview but no buffers were open to it.

**Comment by jedwards1211** [comment] 2019-02-19 19:17
Yeah Atom is rife with slowness problems...  I typically work with multiple project directories and after awhile right-clicking on one of them takes forever for the menu to come up, as does removing one of them.  I've also had issues with text operations being slow on large files because of flaws with `TextBuffer`.  I wish everything could perform as well as Eclipse IDE does these days...

**Comment by Arcanemagus** [comment] 2019-02-19 19:21
> For more context, I was editing Python source code when Atom began to lag as described above so perhaps that indicates something else is causing the actual problem.

That _definitely_ sounds like it was another package, probably one of the Python related linter packages. `linter-eslint` is one of the few providers that does the work in a separate process so it would be rare for it to be causing problems even if it was the issue here.

**Comment by stadelmanma** [comment] 2019-03-27 18:43
@Arcanemagus I have ran into this again, and took some screen shots. This time I was editing C source code. I do have linter-clang installed and active. The problem seems so initially come from the linter package within the lodash module. Something is abusing eslint and slowing things down, but I don't know what it would be.  I have attached two screen shots showing the trace. Do you have any further advice on how to track down the real  issue? 

![trace1](https://user-images.githubusercontent.com/16710141/55103388-b009d500-509e-11e9-89c0-6147e906441b.png)

![trace2](https://user-images.githubusercontent.com/16710141/55103405-b5ffb600-509e-11e9-9372-e5948f371b0b.png)

**Comment by jedwards1211** [comment] 2019-03-27 19:19
The real odd thing about that is that a `spawn` call would take a whole second.  It doesn't wait for the child process it finish, it just spawns it, so normally `spawn` should return very quickly.  So I wonder if `linter-eslint` is passing a huge list of arguments to `spawn`?

**Comment by jedwards1211** [comment] 2019-03-27 19:37
@Arcanemagus 
> linter-eslint should only be spawning something once per project.

I can't tell much from looking at the code but it seems like `linter` is probably in control of spawning the subprocess?  In any case the profiler output clearly shows that some child process related to eslint is being spawned frequently, and the fact that it's wrapped in `debounce` (again, maybe `linter` does this?) would seem to indicate that it's being spawned every time the user stops editing the file for some amount of time.

**Comment by Arcanemagus** [comment] 2019-03-27 20:14
> The real odd thing about that is that a spawn call would take a whole second. It doesn't wait for the child process it finish, it just spawns it, so normally spawn should return very quickly. So I wonder if linter-eslint is passing a huge list of arguments to spawn?

The **only** part of that trace that relates to `linter-eslint` is that it has `sb-exec` as a dependency. **Nothing else**!

Whatever project is triggering that (A linter for C source code?) _also_ happens to have `sb-exec` as a dependency, and Atom is simply using the instance from `linter-eslint` since it already had it in memory.

> I can't tell much from looking at the code but I'm guessing linter is probably in control of spawning the subprocess?

Not quite, `linter` requests new results from a provider by calling it's `lint()` method. How those results are obtained is entirely up to the provider. In the case of most providers they do call out to an external linter tool to get updated results, parse them, and send them back. `linter-eslint` however will check if it already has a worker process running for that project, if it already has one sitting idle in the background it just requests that worker to run a new lint and return updated results. If it doesn't have one running then it will spawn a new one, which is the only time it will do so (hence "once per project").

> ... it's wrapped in debounce (again, maybe linter does this?) would seem to indicate that it's being spawned every time the user stops editing the file for some amount of time.

Yes, `linter` has its own control over how often it will request results from providers (implemented using `debounce`).

**Comment by Arcanemagus** [comment] 2019-03-27 20:17
I'm closing this issue since it has nothing to do with `linter-eslint`, however I'm happy to keep helping you dig further into what might be the cause of this. It might be simpler to chat on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638).

**Closed by Arcanemagus** 2019-03-27 20:17 UTC

**Comment by stadelmanma** [comment] 2019-03-27 22:41
@Arcanemagus I didn't realize that Atom would call into a separate module if it had it loaded in memory, (which makes perfect sense). I have disabled linter-eslint since I can just run it from the command line and maybe that will give me the true culprit by not having it exist in memory.

The slack channel appears to be down for maintenance, but I can make an issue somewhere more appropriate if you would prefer (just point me in the right direction). 

Anyways, what is the best way to go about debugging this? The traceback is woefully uninformative and it only appears after Atom has been running for awhile is another kicker.

**Comment by Arcanemagus** [comment] 2019-03-27 22:57
> what is the best way to go about debugging this?

The key here is context: What were you doing when you noticed this?

You mention you saw this while working on C++ code, is it repeatable when you save a file there?

If you run the `Linter: Debug` command from the Command Palette what providers are active for the file? Does disabling them one by one make the issue go away?

> The slack channel appears to be down for maintenance

Thanks for mentioning that, I've let the appropriate people know 😉.
