### ISSUE TITLE
Handle missing module errors more gracefully

### ISSUE THREAD

**Issue by callumlocke** [AtomLinter/linter-eslint#739] opened 2016-10-20 10:58 UTC
Problem: often I clone a repo just to explore the code in Atom (and I don't want to bother doing `npm install`, because I'm not actually going to be developing in the repo, I'm just viewing the code). But if the repo uses ESLint, this fires up linter-eslint, and every time I click on a JS file, an error pops up:

![image](https://cloud.githubusercontent.com/assets/250617/19556911/451fe8c8-96bb-11e6-9ec4-74bf95c6f042.png)

A new error appears for every file you view. They keep accumulating until you close them manually. I don't want to have to run `npm install` just to keep my linter happy in someone else's repo I'm just browsing.

It would be great if linter-eslint could catch this kind of error and just display a small notification in the status bar instead of allowing big intrusive errors to overlap my code.

**Comment by IanVS** [comment] 2016-10-20 11:22
We have talked about putting other common error messages in the status bar (https://github.com/AtomLinter/linter-eslint/issues/735#issuecomment-254647063),  and I like the idea of doing the same thing for these messages as well.

**Comment by Arcanemagus** [comment] 2017-02-10 23:21
Closing as a duplicate of #387.

**Closed by Arcanemagus** 2017-02-10 23:21 UTC
Labels: enhancement
