### ISSUE TITLE
linter-eslint disabled when used global config in home directory.

### ISSUE THREAD

**Issue by NTMan** [AtomLinter/linter-eslint#729] opened 2016-10-07 14:17 UTC
linter-eslint disabled when used global config in home directory.

Here possible using workaround if unchecked option "Disable when no ESLint config is found (in package.json or .eslintrc)" but expected that  plugin would know about config in home directory.

https://github.com/eslint/eslint/issues/3677#issuecomment-138090285

**Comment by Arcanemagus** [comment] 2016-10-07 17:10
This plugin follows the behavior outlined in [the documentation](http://eslint.org/docs/user-guide/configuring#using-configuration-files), I'm not sure where that person got the idea that it will fallback to a file in the home directory. If it does, that's not documented.

**Comment by NTMan** [comment] 2016-10-07 18:13
This behaviour described in documentation here: http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

> Note: If you have a personal configuration file in your home directory (~/.eslintrc), it will only be used if no other configuration files are found.

**Comment by Arcanemagus** [comment] 2016-10-07 18:50
In the context of the rest of that quote, they are talking about projects under the home directory, which would be covered by the "search up in directories" rule. I'm trying to find the actual code since there is conflicting information here...

**Comment by Arcanemagus** [comment] 2016-10-07 18:55
Looks like [the code](https://github.com/eslint/eslint/blob/v3.7.1/lib/config.js#L155) follows the comment in the issue, and part of the documentation, marking this as a bug.

**Comment by IanVS** [comment] 2016-10-08 00:14
Right, if there's an .eslintrc in the home directory, ESLint will normally use that for any project anywhere.

**Comment by OtterCode** [comment] 2016-10-13 17:11
Not entirely sure if my issue is the same or different, but when I used relative paths in the linter-eslint configuration, it failed silently.

To be exact: `~/.eslintrc` fails, but `/home/user/.eslintrc` succeeds. That's highly annoying, since it reduces the portability of configs, and it fails to say anything about the error.

**Comment by OtterCode** [comment] 2016-10-13 17:13
At minimum, the settings panel should include a note mentioning that absolute paths are required.

**Comment by IanVS** [comment] 2016-12-03 16:39
So, to clarify the state of this issue, the proposed change seems to be for linter-eslint to treat an eslint config file in the user's home directory as satisfying the requirement for `Disable when no ESLint config is found (in package.json or .eslintrc)`, causing linting to happen if that option is checked and the only config is in the home directory.  Is that accurate?

**Comment by oleander** [comment] 2016-12-03 17:11
@IanVS Not entirely sure what you're referring to. Is everything outside the current project directory treated as satisfying the requirement for `Disable when no ESLint config is found (in package.json or .eslintrc)`? I.e; a config file found in `~` or `/`, but not the current project directory disables `linter-eslint` when `Disable when no ESLint config is found (in package.json or .eslintrc)` is checked . Is that correct?

**Comment by IanVS** [comment] 2016-12-04 02:20
`linter-eslint` has no concept of a "current project directory", so it will search up to root looking for a config.  

If it doesn't find one, and the `Disable when no ESLint config is found` option is checked, then it does not do any linting.  

I believe the proposed change is to also check the home directory for a config.

**Comment by oleander** [comment] 2016-12-04 03:43
@IanVS `eslint` already checks the users home directory :) See: https://github.com/eslint/eslint/blob/master/lib/config.js#L147 Like you said, it stats with the current directory and moves up towards root. Then, if nothing is found it tries the users home directory.

How about using the option `Disable when no ESLint config is found...` for when no config is found in the project directory? That would make it possible to disable the linter for a specific project by not using a `.eslintrc` file, even if a *global one exist. I understand no such feature exist today, but that would be a possible use case without having to disable `eslint-linter` in Atom settings panel.

*parent directories or home dir

**Comment by IanVS** [comment] 2016-12-04 03:49
@oleander Yes I know that is what ESLint does.  But, there is no API for ESLint to tell us whether it found a config file for a given file, so we also crawl the filesystem ourselves looking for a config file.  The bug is that we do not check the home directory like ESLint does.  

It would be nice to have a feature like you suggest, but how would you suggest determining which folder is the "project root"?  It isn't as simple as you might think, and we would inevitably get it wrong for some exotic folder structures.

**Comment by oleander** [comment] 2016-12-04 03:57
Something like this should work.

``` javascript
import {CLIEngine} from "eslint";
const cli = new CLIEngine({/* ... */});
const Config = require("eslint/lib/config");
const paths = new Config(cli.options).findLocalConfigFiles("/a/b/c.js");
```

``` javascript
/* All possible config files, i.e `.eslintrc.yaml` */
const {CONFIG_FILES} = require("eslint/lib/config/config-file");
```

Then use `chokidar` to watch existing and upcoming configs using your OS filesystem watcher.

``` javascript
chokidar.watch(possibleConfigFile, {/* ... */});
```

**Comment by oleander** [comment] 2016-12-04 03:58
Project root; `atom.workspace.getPaths()`

**Comment by IanVS** [comment] 2016-12-04 04:02
>Project root; atom.workspace.getPaths()

That only works if the user has not opened an individual file or subfolder of the project.  Perhaps a rare case, but it _can_ happen, and personally I think changing whether a file is linted or not based on how the file was opened in the editor would be confusing and unexpected behavior.

**Comment by oleander** [comment] 2016-12-04 04:04
`atom.project.onDidChangePaths(function(paths) {});` should work.

**Comment by oleander** [comment] 2016-12-04 04:44
@IanVS That was a bit mean, sorry. 

The reason I know this is b/c I worked on the problem a few weeks back, due to old hardware. My hard drive couldn't for some reason manage the amount of I/O operations (at least that's what atom's profiler told me. I wanted so see if it was possible to move from fs `pull` to `push` and at the same time implement `linter`s push Indie API.

Spent about 2 weeks researching ESLint, `linter` and this lib to figure out an alternative solution. It works really well and is considerable faster (on my old MBP '09), mainly as almost no I/O operations are performed during linting.

The new (?) pusher linter API also lets me "reload" linter errors whenever a config or `.eslintignore` changes, without having to check with the file system.

Currently running a fork of this project with these "features", all specs passing and some added. I haven't had the time to share any code yet, but I'm happy to do so if you and your team are interested.

Also decided to write a small testing framework on-top of Jasmine to simplify the current specs as I had difficulties understanding the ranges being used.

``` javascript
describe("linter", function() {
  it("handles the bad", function() {
    lint("files/bad.js", function(handle) {
      handle.forRule("semi", function(message) {
        expect(message.type).toBe("Error");
        expect(message.text).toBeNull();
        expect(message.html).toContain("href");
        expect(message.highlight).toEqual(";");
      });

      handle.forRule("no-undef", function(message) {
        expect(message.type).toBe("Error");
        expect(message.text).toBeNull();
        expect(message.html).toContain("href");
        expect(message.highlight).toEqual("foo");
      });
    });
  });
});
```

**Comment by IanVS** [comment] 2016-12-04 16:37
We've gotten a bit off-topic for this issue.  Would you mind opening a new issue, @oleander, with all the details of what you're suggesting?

**Comment by oleander** [comment] 2016-12-05 18:36
@IanVS Sure! I'll create a pr later this week with my suggestions.

**Comment by IanVS** [comment] 2017-01-05 04:44
Closing this issue as a bit of a duplicate of https://github.com/AtomLinter/linter-eslint/issues/773.  Let's move any other discussion over to that issue.

**Closed by IanVS** 2017-01-05 04:44 UTC
Labels: bug
