### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by joma74** [AtomLinter/linter-eslint#921] opened 2017-05-23 20:05 UTC
## Issue Type
Bug

## Issue Description
Since linter-eslint 8.2.0 execution of ```exec cross-env NODE_ENV=test mocha -t 5000 --colors  --compilers js:babel-core/register --require babel-polyfill``` via `platformio-ide-terminal` fails constantly (see stacktrace).

Deinstalling linter-eslint, restarting atom and reexecution gives no such error. Also starting from terminal(outside of atom) gives no such error.

Reinstalling and some steps - error again.

## Bug Checklist

```
joma@kopernikus-u:~/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team$ yarn run test
yarn run v0.22.0
$ ./makejs test --
--- test:run ---
exec cross-env NODE_ENV=test  mocha -t 5000 --colors  --compilers js:babel-core/register --require babel-polyfill src/test/js/*.spec.js
/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/src/test/js/syncsettle.spec.js:3
import { describe, it } from 'mocha';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at loader (/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/babel-register/lib/node.js:154:7)

    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/joma/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team/node_modules/mocha/bin/_mocha:460:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
Done in 1.27s.
```

**Comment by joma74** [comment] 2017-05-23 20:12
Just noted that - for a workaround - downgrading works.
```joma@kopernikus-u:~/entwicklung/nodews/vuejs-laracasts/episode-vuerouter-team$ apm install linter-eslint@8.1.7```

**Comment by IanVS** [comment] 2017-05-24 02:15
This looks like it could be related to https://github.com/AtomLinter/linter-eslint/issues/920.  Can you try upgrading to `8.2.1`?

**Comment by Arcanemagus** [comment] 2017-05-24 05:08
I don't think v8.2.1 will help here, my guess is that somehow the process above is using the `babel` version that is getting installed as a dependency here. There really isn't anything we can do about that, you'll need to bring this up with `platform-ide-terminal` as to how it is polluting its "CLI" environment with the Atom internal environment.

**Comment by joma74** [comment] 2017-05-24 09:52
@IanVS Upgrading to `8.2.1` still gives `SyntaxError: Unexpected token import`.

If reevaluated need support to describe a bug report against `platform-ide-terminal`. Like pondering what kind of leak/pollution this can be.
Given that linter-eslint  8.1.7 does not show this behaviour and i kept `platform-ide-terminal` and `atom core` at the same version - what' the diff key point between `8.1.7` and `8.2.1` in this regard?

**Comment by Arcanemagus** [comment] 2017-05-24 19:57
v8.2.0 brings in `babel` as a sub-dependency (of `atom-babel6-transpiler`), for some reason from what I can tell of what you posted the processes you are running is using this version of `babel`, which looks to be causing problems?

I'm still not entirely sure what your issue even is since you provided no steps to reproduce and mention nothing about `linter-eslint` other than it being installed.

**Comment by modosc** [comment] 2017-05-24 20:04
i'm seeing the same thing (see also #923). when i upgrade to >=`8.2.0` my `.eslintrc.js` isn't being used at all, hence these warnings. downgrading to `8.1.7` seems to resolve it.

**Comment by Arcanemagus** [comment] 2017-05-24 20:12
@modosc This issue (at least as described so far) has _nothing_ to do with `linter-eslint`, other than it being installed. Please keep further discussion related to #923 in #923 😉.

**Comment by joma74** [comment] 2017-05-25 11:30
I am inclined to blame https://github.com/atom/atom-babel6-transpiler/blob/v1.1.1/lib/index.js#L15 for this issue. Please bare with me the next lines for concluding.

Prior to this line in https://github.com/atom/atom-babel6-transpiler/blob/v1.1.1/lib/index.js#L8  -
 as BABEL_ENV is unset in my case - gives undefined. Then BABEL_ENV is set as environment var to literally "undefined" at this very line https://github.com/atom/atom-babel6-transpiler/blob/v1.1.1/lib/index.js#L15. The following screenshot is an atom debug session while on atom window reload at those lines.
![atom-linter-eslint-issues-921-001](https://cloud.githubusercontent.com/assets/5314859/26447666/cf860446-4149-11e7-9561-54a488b4e58c.png)

The next screenshot is right after that atom window reloaded. You can see that the terminal got the BABEL_ENV variable inherited.
![atom-linter-eslint-issues-921-002](https://cloud.githubusercontent.com/assets/5314859/26447667/cf89d40e-4149-11e7-8bf5-e88ddf55c977.png)

For consequences see https://github.com/babel/babel/blob/v6.24.1/packages/babel-core/src/transformation/file/options/build-config-chain.js#L165 :  
```const envKey = process.env.BABEL_ENV || process.env.NODE_ENV || "development";```
At this point `BABEL_ENV ===  'undefined'` get's the named babel conf. Which get's - not existing in my babel.rc - defaulted (and, well, thinking of it to be in any other babel.rc a rare name too :smiling_imp:). 

Default in my babelrc is to not transpile es6 modules. mocha 3.3.0 is not prepared for es6 module format in it's user-written unit tests, so gives the mentioned SyntaxError.

If you landed at the same conclusion consider to forward this bug to atom-babel6-transpiler. For reproduction i think that installing `linter-eslint` is sufficent.

_P.S._ As proof of said for myself i executed under `8.2.1` with an additional  BABEL_ENV=test parameter sucessfully. Because my babel.rc is configured to be activated by an env named 'test' to then transpile es6 modules. So `exec cross-env NODE_ENV=test BABEL_ENV=test mocha -t 5000 --colors --compilers js:babel-core/register --require babel-polyfill ...` worked.

**Comment by joma74** [comment] 2017-05-25 11:43
P.S.2 Reconsider my previous comment in context of #923 too. Maybe applicable, not sure.

**Comment by Arcanemagus** [comment] 2017-07-21 21:28
That looks extremely likely to be the issue, thanks for figuring this out and tracking it down @joma74 and sorry for the delay in getting back to this issue. I'll put up a PR on `atom-babel6-transpiler` and try to get it merged ASAP.

**Comment by Arcanemagus** [comment] 2017-07-21 21:39
It looks like in the meantime till that gets merged and released, forcing the `setBabelEnv` option to `false` here can work around the issue and I don't _think_ it is being used.

**Closed** 2017-07-22 00:59 UTC
Labels: External

**Comment by Arcanemagus** [comment] 2017-09-18 04:18
Looks like this finally got released in v8.3.0, sorry it took so long!

**Comment by modosc** [comment] 2017-09-20 16:35
i tried the update, still seeing the issue.

**Comment by IanVS** [comment] 2017-09-20 17:08
@modosc, would you mind opening a new issue and filling out the issue template?  That will help us troubleshoot.

**Comment by modosc** [comment] 2017-09-20 17:10
@IanVS it's still the same issue, see also #923 where i provided a repo to reproduce it. i'll update the repo with notes about the newest version.

**Comment by Arcanemagus** [comment] 2017-09-20 17:16
@modosc #923 is an _entirely_ different issue that has no relation to this. 😕

If you are still seeing _this_ issue, can you open a new issue as requested above?

**Comment by modosc** [comment] 2017-09-20 17:21
@Arcanemagus you're right, sorry for the noise. i'll pipe up on the other issue instead.
