### ISSUE TITLE
[Linter-ESLint] Worker died unexpectedly

### ISSUE THREAD

**Issue by mattsawyer77** [AtomLinter/linter-eslint#345] opened 2015-12-01 19:38 UTC
Lately I've been seeing this:
```
[Linter-ESLint] Worker died unexpectedly
Check your console for more info. A new worker will be spawned instantly.
```
In the console I see:
```
(92067,0x7fff79b40000) malloc: *** error for object 0x7fdbd3c2cc50: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```
Is this a harmless error message? If so I'd expect it to go away on its own. 

If not, would it seem environmental? And what info from me would you need? Here are my current eslint settings:
```
  "linter-eslint":
    disableWhenNoEslintrcFileInPath: true
    eslintPath: "/Users/sawyer/.nvm/versions/node/v0.12.7/bin/eslint"
    globalNodePath: "/Users/sawyer/.nvm/versions/node/v0.12.7"
    disableWhenNoEslintConfig: false
```
I'm running eslint 1.5.1 globally.

**Comment by Arcanemagus** [comment] 2015-12-01 20:22
Duplicate of: #278, #290, #295, #301, #302, #303, #326, #341.

Update to the v1.3.0 beta to get the fix from Atom, or wait until stable is updated to that branch if you can't use the beta for some reason.

**Closed by Arcanemagus** 2015-12-01 20:22 UTC
