### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by devm-ru** [AtomLinter/linter-eslint#679] opened 2016-08-24 11:22 UTC
Hi everyone
```
$ atom --version
Atom    : 1.9.9
Electron: 1.3.3
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1326:5)
    at Object.getESLintInstance (/home/max/.atom/packages/linter-eslint/lib/worker-helpers.js:87:35)
    at /home/max/.atom/packages/linter-eslint/lib/worker.js:62:24
    at Emitter.emit (/home/max/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/max/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:22:23
    at /home/max/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/max/.atom/packages/linter-eslint/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/max/.atom/packages/linter-eslint/node_modules/sb-communication/lib/main.js:63:18)
    at process.messageCallback (/home/max/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```
I'm use global ESLint installation.
Please help

**Comment by IanVS** [comment] 2016-08-24 12:47
Hm, thanks for the report.  What do your `linter-eslint` settings look like?

**Comment by IanVS** [comment] 2016-08-24 12:55
Actually, this seems to be a duplicate of https://github.com/AtomLinter/linter-eslint/issues/580.  Closing, but let me know if you think this is a different issue.

**Closed by IanVS** 2016-08-24 12:55 UTC
Labels: duplicate

**Comment by jvanveen** [comment] 2016-08-28 10:16
Same issue here:

Atom    : 1.9.9
Electron: 1.3.4
Chrome  : 52.0.2743.82
Node    : 6.3.0

**Comment by jolyonruss** [comment] 2016-11-23 12:38
For others having this issue, try updating linter-eslint

`apm update linter-eslint`

Package Updates Available (1)
└── linter-eslint 7.2.2 -> 8.0.0

**Comment by PalermoD** [comment] 2017-03-05 17:28
Updating worked for me, thanks
