### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by jasonkuhrt** [AtomLinter/linter-eslint#39] opened 2015-03-08 16:34 UTC
Open a JavaScript project.

**Atom Version**: 0.186.0
**System**: Mac OS X 10.10.2
**Thrown From**: [linter-eslint](https://github.com/AtomLinter/linter-eslint) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'ecmaFeatures' of undefined

```
At /Users/jasonkuhrt/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:344

TypeError: Cannot read property 'ecmaFeatures' of undefined
  at /Users/jasonkuhrt/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:344:34
  at Array.forEach (native)
  at prepareConfig (/Users/jasonkuhrt/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:343:33)
  at EventEmitter.module.exports.api.verify (/Users/jasonkuhrt/.atom/packages/linter-eslint/node_modules/eslint/lib/eslint.js:568:18)
  at LinterESLint.lintFile (/Users/jasonkuhrt/.atom/packages/linter-eslint/lib/linter-eslint.coffee:69:21)
  at /Users/jasonkuhrt/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /Users/jasonkuhrt/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:100:15)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mocha-test-runner",
      "Zen"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-eslint": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atomatigit, v1.2.3
autocomplete-plus, v2.4.1
autosave, v0.20.0
color-picker, v1.4.4
language-docker, v1.1.2
language-elm, v0.4.1
language-haskell, v1.0.0
language-jade, v0.3.0
language-purescript, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-eslint, v0.4.1
linter-hlint, v0.3.1
project-manager, v1.15.5
seti-syntax, v0.3.3
seti-ui, v0.6.3
toggle-tabs, v0.1.8
travis-ci-status, v0.11.2
vim-mode, v0.36.0

# Dev
No dev packages
```

**Comment by jasonkuhrt** [comment] 2015-03-08 16:44
This may be related https://github.com/eslint/eslint/issues/1972

**Comment by jasonkuhrt** [comment] 2015-03-08 19:46
Nope, I've downloaded the new version of `eslint 0.6.1` and its working just fine again on the CLI. `atom` is the odd one out now.

**Comment by xadh00m** [comment] 2015-03-19 14:30
I get the same issue in multiple files in atom as soon as I add ```"console": 1``` to my .eslintrc file:

```
{
  "env": {
    "browser": 1,
    "es6": 1,
    "console": 1,
    "amd": 1,
  }
}
```

Without the console command the error does not occur.

**Comment by iansinnott** [comment] 2015-03-22 08:04
Same issue here. I've found that removing the es6 line from the configuration makes the error disappear. Not sure why it causes an error

**Comment by robertbaker** [comment] 2015-04-09 19:18
I had this error after adding a sub eslintrc file that just uses node as the env.

**Comment by jasonkuhrt** [comment] 2015-04-09 19:44
I am no longer using Atom so will stop following this issue. Feel free to close at will.

**Comment by iansinnott** [comment] 2015-04-09 22:17
I got this error while using Vim, so I don't think it's editor-specific. @robertbaker Any idea why that was an issue? I have the same setup, i.e. a sub `.eslintrc` that specifies node as the env.

**Comment by robertbaker** [comment] 2015-04-09 22:25
No idea why. My theory is eslint config changed on a global level and file
level and the package was still referencing the old config pattern.

**Comment by jfaissolle** [comment] 2015-04-10 06:47
There recently has been a large number of issues related to errors coming from eslint code. This is caused by eslint moving really fast, especially with features related to es6. For now, the only way to work reliably with eslint and linter-eslint is to have a project local eslint version. linter-eslint will pick your local eslint so you can control exactly what version is used by the plugin. As a reminder, linter-eslint does not support globally installed eslint. Closing.

**Closed by jfaissolle** 2015-04-10 06:47 UTC

**Comment by cssetian** [comment] 2015-08-25 19:18
FWIW, if anyone is still experiencing this I was recently getting the same issue, and ended up fixing it by installing eslint globally, checking the use global option, and properly setting my npm prefix in Atom - I had a specific version of npm specified as my default version using nvm, which I'm guessing was related to the root of the problem.
