### ISSUE TITLE
Enabling this plugin with platformio/platformio-atom-ide-terminal together spoils eslint configuration

### ISSUE THREAD

**Issue by krrishh-org** [AtomLinter/linter-eslint#928] opened 2017-05-30 08:29 UTC
## Issue Type
Bug

## Issue Description
I'm using [platformio/platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) and linter-eslint packages within atom. When I have the linter-eslint plugin enabled and start a webpack-dev-server (which includes babel, eslint loaders in the configuration) from the platformio-atom-ide-terminal, It fails (eslint loader throws the following error)
 
![error](https://cloud.githubusercontent.com/assets/19912501/26574141/df29a162-453d-11e7-8d7c-5dfc9fba4a8d.png)

This doesn't happen when the linter-eslint plugin is disabled.

Here's the actual contents of the file:

```javascript
//...truncated
class LoginScreen extends BaseComponent {

    constructor(props) {
        super(props);
        this.__finalEventMap = {};
        this.__userAddedEvents = {};
        this.__actionMap = {};
        this.__extVarValidations = {};
        this.__compPropDefaults = {};
        this.__compDefaults = {};
    }


    componentWillMount = function() {
        defaults.componentWillMount.call(this);
        document.body.className = '';
    }
//... truncated
}
```

PS: I'm really not sure what title should I give for this issue. Suggestions are welcome.
## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
//Linter Eslint: Debug output here
Atom version: 1.18.0-beta2
linter-eslint version: 8.2.1
ESLint version: 3.18.0
Hours since last Atom restart: 0.1
Platform: linux
Using local project ESLint from: /mnt/7ffabd4b-17a0-47e8-a1c9-04fde352984e/workspace/Phoenix-Studio/node_modules/eslint
Current file's scopes: [
  "source.js",
  "comment.block.documentation.js",
  "punctuation.definition.comment.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

### .eslintrc file

``` json
{
  "parser": "babel-eslint",
  "extends": [
    "eslint:recommended",
    "plugin:import/errors",
    "plugin:import/warnings"
  ],
  "plugins": [
    "react"
  ],
  "env": {
    "es6": true,
    "browser": true,
    "node": true,
    "jquery": true,
    "mocha": true
  },
  "rules": {
    "quotes": 0,
    "no-mixed-spaces-and-tabs": 0,
    "no-console": 1,
    "no-debugger": 1,
    "no-var": 1,
    "semi": [1, "always"],
    "no-trailing-spaces": 0,
    "eol-last": 0,
    "no-unused-vars": 0,
    "no-underscore-dangle": 0,
    "no-alert": 0,
    "no-lone-blocks": 0,
    "jsx-quotes": 1,
    "react/display-name": [ 1, {"ignoreTranspilerName": false }],
    "react/forbid-prop-types": [1, {"forbid": ["any"]}],
    "react/jsx-boolean-value": 1,
    "react/jsx-closing-bracket-location": 0,
    "react/jsx-curly-spacing": 1,
    "react/jsx-indent-props": 0,
    "react/jsx-key": 1,
    "react/jsx-max-props-per-line": 0,
    "react/jsx-no-bind": 0,
    "react/jsx-no-duplicate-props": 1,
    "react/jsx-no-literals": 0,
    "react/jsx-no-undef": 1,
    "react/jsx-pascal-case": 1,
    "react/jsx-sort-prop-types": 0,
    "react/jsx-sort-props": 0,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-danger": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-direct-mutation-state": 1,
    "react/no-multi-comp": 1,
    "react/no-set-state": 1,
    "react/no-unknown-property": 1,
    "react/prefer-es6-class": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "import/extensions": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 1,
    "react/jsx-wrap-multilines": 1
  }
}

```

**Comment by joma74** [comment] 2017-06-15 22:43
@krrishh-org Same as https://github.com/AtomLinter/linter-eslint/issues/921, have a look at my comments.

**Comment by Arcanemagus** [comment] 2017-07-21 21:25
Closing as a duplicate of #921, I'm sure @joma74 has the issue figured out in https://github.com/AtomLinter/linter-eslint/issues/921#issuecomment-303988518 😉.

**Closed by Arcanemagus** 2017-07-21 21:25 UTC
