### ISSUE TITLE
Updated package through atom-updater and I now get an error that the plugin is unable to find 'babel-eslint'

### ISSUE THREAD

**Issue by kedano** [AtomLinter/linter-eslint#457] opened 2016-02-24 11:19 UTC
`Error: Cannot find module 'babel-eslint' from '~/.atom/packages/linter-eslint/node_modules'`

**Comment by jthomson-act** [comment] 2016-02-24 14:45
I have the same issue but for the eslint-plugin-angular

**Comment by IanVS** [comment] 2016-02-24 14:49
This happens if you do not have eslint installed locally or globally.  Linter-eslint falls back to the version bundled with itself, which was just updated to `2.2.0`.  Can you tell us a little more about your situations (applicable settings, where you have ESLint installed, where you have plugins installed, etc.)?

**Comment by kedano** [comment] 2016-02-25 07:38
This plugin previously worked on my setup, but broke after the latest update. I see the module missing in the package.json `dependencies` list but it is listed in `devDependencies`. If it is required for the plugin to work, doesn't it have to be in `dependencies `?

I temporarily fixed this by going into the linter-eslint folder on machine and did a `npm install` to install all the `devDependencies`.

**Comment by vladimir-tikhonov** [comment] 2016-02-25 08:36
`npm install` in `~/.atom/packages/linter-eslint` also works for me, but now I got an error, because `eslint-plugin-react` v.4.0.0 (from `linter-eslint`'s `package.json` ) is incompatible with v.3.16.1, which I use in my project

**Comment by Arcanemagus** [comment] 2016-02-25 18:42
@kedano @vladimir-tikhonov That is the wrong way to solve this issue, the problem (as @IanVS already stated) is that for some reason `linter-eslint` is unable to find the version of `eslint` installed to your project itself.

Can you please provide the information he requested, as well as a directory structure (like https://github.com/AtomLinter/linter-eslint/issues/294 did), so we can attempt to reproduce and diagnose this.

**Comment by vladimir-tikhonov** [comment] 2016-02-26 07:45
@Arcanemagus `eslint` was installed as `grunt-eslint` dependency and located in `node_modules/grunt-eslint/node_modules/eslint` (not sure, how it even worked before with this path). I installed `eslint` explicitly in `node_modules/eslint` and plugin starts to work correctly.

> the problem (as @IanVS already stated) is that for some reason linter-eslint is unable to find the version of eslint installed to your project itself.

I think that it will be better to show appropriate error message instead of throwing some weird exception.

**Comment by dckesler** [comment] 2016-02-27 22:59
I went to `.atom/packages/linter-eslint` and I installed babel-eslint via npm in there and that fixed this problem for me.

**Comment by IanVS** [comment] 2016-02-28 02:12
@dckesler That will silence the warnings, but the better approach is to `npm i --save-dev eslint babel-eslint` inside of your project.

**Comment by dckesler** [comment] 2016-02-28 21:10
Well that was my first strategy, but the error persisted until I installed babel-eslint inside of the linter-eslint module.

**Comment by sethkinast** [comment] 2016-03-09 18:41
I have the same problem with my app. I ran `npm install` inside the linter-eslint module to stop getting the error.

I have babel-eslint installed as a devDependency of my project already. My app structure is very standard:

```
app/
node_modules/
test/
package.json
```

**Comment by sallar** [comment] 2016-03-11 12:11
I’ve also had the same problem and it goes away with `npm install` in `~/.atom/packages/...`. Even though I have the correct versions of `babel-eslint` and `eslint` installed locally and globally and I still had to do npm install after updating.

**Comment by IanVS** [comment] 2016-03-11 13:29
@Arcanemagus I think we should find some way to clearly show users what `eslint` is being used, whether local, global, or packaged.  At the very least it would help us debug these kinds of issues.  What do you think?

**Comment by henrytseng** [comment] 2016-03-11 14:53
I also have the same problem, but my local `package.json` already does have `babel-eslint`

```
"devDependencies": {
    "babel-eslint": "~4.1.8",
    "browserify": "~13.0.0",
    "del": "~2.2.0",
    "eslint": "~2.0.0",
```

**Comment by Arcanemagus** [comment] 2016-03-11 21:30
What method were you thinking @IanVS? A `console.log` whenever the loaded `eslint` is changed?

**Comment by dwelle** [comment] 2016-04-11 13:59
For others -- note that there have been some changes from ESLlint 2.0.0, such as putting [ES6 globals](http://eslint.org/docs/user-guide/migrating-to-2.0.0#built-in-global-variables) under `es6` `env` flag. This is the reason I thought `babel-eslint` also isn't working for me, while it was.

**Comment by timini** [comment] 2016-04-12 15:39
Was also experiencing this issue, 

use @sallar method to fix

**Comment by nathanmalishev** [comment] 2016-06-30 10:19
@dckesler fix worked for me!

**Comment by Arcanemagus** [comment] 2016-10-07 17:22
I'm closing this issue, nobody experiencing this has bothered to provide a directory structure that shows this, other than ones where it _shouldn't_ work as `eslint` was installed as a sub-dependency inside another module.

If you are running into this ensure that ESLint and all plugins are properly installed locally in your project OR they are _all_ installed globally and you have the option enabled for that. You _can't_ mix and match!

@IanVS's idea for a debug command is being handled elsewhere, and isn't relevant to the initially reported issue.

**Closed by Arcanemagus** 2016-10-07 17:22 UTC
Labels: question
