### ISSUE TITLE
Disable error messages

### ISSUE THREAD

**Issue by RyanMitchellWilson** [AtomLinter/linter-eslint#975] opened 2017-08-07 21:09 UTC
Whenever I try to just use atom for something other than my main project I get these errors every single time I press a key in file. Can these be removed or given an option to disable them?

<img width="614" alt="screen shot 2017-08-07 at 3 06 26 pm" src="https://user-images.githubusercontent.com/11371200/29045895-6132f152-7b82-11e7-8d4a-b5954980f79e.png">

**Comment by Arcanemagus** [comment] 2017-08-07 21:12
Can you open Developer Tools and check on the error it's reporting on? It should only be giving you that if something is very broken with the setup.

**Comment by RyanMitchellWilson** [comment] 2017-08-07 21:15
I'm getting `Cannot find module 'babel-eslint' Error: Cannot find module 'babel-eslint'`

**Comment by Arcanemagus** [comment] 2017-08-07 21:17
That means you have a configuration somewhere for the open file that is specifying `babel-eslint` as the parser, you can see which configuration it's using from the `Linter ESLint: Debug` command.

**Comment by RyanMitchellWilson** [comment] 2017-08-07 21:29
I have the `Disable when no ESLint config is found (in package.json or .eslintrc)` checked and it is still showing up.
I'm trying to run the `react-native-video` example and from what I can tell. It doesn't have an `.eslintrc` file or anything specifying `babel-eslint` anywhere. And the `package.json` looks just like this:
```
{
  "name": "VideoPlayer",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "^0.42.0",
    "react-native-video": "file:../"
  }
}
```
Is there a way to just disable them completely so that I never see messages like this pop up?

**Comment by Arcanemagus** [comment] 2017-08-08 22:22
As I said, if it's showing up you have an ESLint configuration file _somewhere_, either in a parent directory to this project, or at `~/.eslintrc`.

**Comment by RyanMitchellWilson** [comment] 2017-08-08 22:33
Ok, I've looked around and I don't have a `.eslintrc`, yet it is still happening. Can an option to just turn off those kind of errors in general? Because it literally opens a new error message for every single key that I press.

Also why would this be looking in any parent directories? If it is not in my project currently opened it shouldn't be looking elsewhere for it. Because say I'm working on two different projects, I don't want the linter for one project interfering with my other project.

**Comment by Arcanemagus** [comment] 2017-08-08 22:36
ESLint has a complex set of rules for determining the configuration, you can find details [here](http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy).

**Comment by bl00mber** [comment] 2017-09-05 01:11
This errors always showing up when node_modules dependencies not installed yet. Would be great if this errors (or this plugin completely) will be auto-disabled for projects without this folder, because with this errors this plugin is unusable.

**Comment by Arcanemagus** [comment] 2017-09-17 01:57
Duplicate of #387

**Comment by Arcanemagus** [comment] 2017-09-17 01:58
Looks like this was already filed before, marked as a duplicate of that issue, and I've got a PR incoming that handles this in a _much_ cleaner way 😉.

**Closed by Arcanemagus** 2017-09-17 01:57 UTC
