### ISSUE TITLE
8.2.0 -- Atom-Beta 1.18 High memory usage

### ISSUE THREAD

**Issue by philipchmalts** [AtomLinter/linter-eslint#925] opened 2017-05-25 20:55 UTC
## Issue Type
Bug

## Issue Description

Since updating to 8.20 in atom beta 1.18 - beta1 linter-eslint-helper eats up a ton of memory and basically gets stuck linting files sometimes taking over 30s per file. It was working well before updating to the newest version. Has anyone else encountered this issue?

![screen shot 2017-05-25 at 4 49 20 pm](https://cloud.githubusercontent.com/assets/14876812/26470190/d14bdd20-416a-11e7-9b5c-ddf88564f731.png)

## Bug Checklist
- Restart Atom
- Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Linter Eslint: Debug output here

Atom version: 1.18.0-beta1
linter-eslint version: 8.2.1
ESLint version: 3.19.0
Hours since last Atom restart: 0.3
Platform: darwin
Using local project ESLint from: /Users/philipchmalts/Documents/Development/if-client/node_modules/eslint
Current file's scopes: [
  "source.js.jsx",
  "meta.function.js",
  "punctuation.terminator.statement.js"
]
linter-eslint configuration: {
  "disableWhenNoEslintConfig": false,
  "fixOnSave": true,
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": [],
  "rulesToDisableWhileFixing": []
}
```

**Comment by cbranch101** [comment] 2017-05-28 15:40
This is pretty much rendering this plugin unusable for me

**Comment by nielsvanmidden** [comment] 2017-06-02 08:19
Same. Anyone has a solution?

**Comment by IanVS** [comment] 2017-06-12 03:27
I assume that downgrading back to linter-eslint version `8.1.7` 

I'm not sure why some users are seeing this and others aren't.  If there is any other information you can share about your configurations or setup, that would be helpful.  Does it happen for you on all projects, or only certain ones?  Also, does it still happen if you disable `fixOnSave`?

**Comment by elliottrisby** [comment] 2017-09-28 00:49
Im getting this problem on 8.3.2. 

![image](https://user-images.githubusercontent.com/8551287/30944354-94c89d56-a43a-11e7-9a39-26807c687ecb.png)

**Comment by elliottrisby** [comment] 2017-09-28 01:00
**Update:** Uninstalling & Reverting to 7.2.3 is much more stable for me:
apm install linter-eslint@7.2.3

**Comment by preco21** [comment] 2018-03-28 03:44
@IanVS  I was getting the issue while using the options as following:

```cson
"linter-eslint":
  disableFSCache: true
  fixOnSave: true
```

Now it's solved by downgrading the package to `8.2.7`.

**Comment by skylize** [comment] 2018-05-08 15:07
@preco21 
the `disableFSCache` setting will *massively* increase the amount of I/O the package needs to do, because it needs to reload the `eslint` binary along with any plugins, *every single time* it lints the file.

You should set `disableFSCache` to `false`. That setting is only there to help plugin developers, and in the rare case you actually need it set to `true`, you should probably set `fixOnSave` to `false`, and just lint when you save the file.

**Comment by skylize** [comment] 2018-05-08 15:30
This Issue seems to be a less-clear description of the more specific Issue described in #927. Closing as a duplicate of #927. We can reopen if someone provides info that differentiates this Issue.

**Closed by skylize** 2018-05-08 15:30 UTC
Labels: bug

**Comment by Arcanemagus** [comment] 2018-05-08 16:09
> because it needs to reload the eslint binary along with any plugins, every single time it lints the file.

That's not actually what that setting does, it only controls whether the file tree is scanned every time a search is performed, or whether cached results can be returned. It's only useful when you are moving where things are quite often.
