### ISSUE TITLE
.eslintignore not work

### ISSUE THREAD

**Issue by willin** [AtomLinter/linter-eslint#494] opened 2016-03-21 01:23 UTC
![image](https://cloud.githubusercontent.com/assets/1890238/13908831/838e5832-ef46-11e5-84b1-2da4e8c2fcbc.png)

.eslintignore:

```
dist/
example/
```

**Comment by IanVS** [comment] 2016-03-21 01:26
This appears to be a duplicate of https://github.com/AtomLinter/linter-eslint/issues/448, which was recently fixed and will be included in the next release.

**Closed by IanVS** 2016-03-21 01:26 UTC
