### ISSUE TITLE
eslint not found

### ISSUE THREAD

**Issue by marcopiraccini** [AtomLinter/linter-eslint#328] opened 2015-11-23 11:34 UTC
I have node installed using NVM on my Ubuntu 15-10 box. 
eslint is installed globally and is on the PATH: 

```bash
$ which eslint
/usr/local/bin/eslint`
```

"Use global ESLint installation" is checked

...but I have the error "Error: ESLint not found"

**Comment by IanVS** [comment] 2015-11-23 13:55
What version of linter-eslint are you using?

**Comment by marcopiraccini** [comment] 2015-11-23 14:25
v5.2.3, the last one.

**Comment by Arcanemagus** [comment] 2015-11-23 17:38
Can you run `npm get prefix`, then see if there is a `node_modules/eslint` folder in the path you get from that command?

----
On my Ubuntu VM I somehow have the output of `npm get prefix` being `/usr/lib`, which `npm -g` properly affects, but `which eslint` shows `/usr/local/bin/eslint` which leads to a different installation. I'm guessing when I setup the latest node repo it changed paths from the system installed one, so at this point it has two different global `eslint` installs and I'm wondering if you are in a similar situation.

**Comment by marcopiraccini** [comment] 2015-11-23 18:32
No, there's no `node_modules`:
``` 
$ npm get prefix
/home/marco/.nvm/versions/node/v5.0.0

$ ls /home/marco/.nvm/versions/node/v5.0.0
bin  CHANGELOG.md  etc  include  lib  LICENSE  README.md  share
```

However I'm not sure it's wrong, all the "global" modules are in `/usr/local/lib/node_modules`, indeed:
```
/usr/local/bin/eslint -> ../lib/node_modules/eslint/bin/eslint.js
```

**Comment by Arcanemagus** [comment] 2015-11-23 22:58
That's not a "standard" way of setting up node, although it seems my VM previously did something similar...

If you manually set the `Global Node Installation Path` to `/usr/lib` it should work for you, the issue is that your prefix path isn't set correctly (or not being used correctly by node) so the plugin was unable to set things up properly for you.

I'm marking this as closed but feel free to keep commenting here if you need more help getting this working.

**Closed by Arcanemagus** 2015-11-23 22:58 UTC

**Comment by montogeek** [comment] 2015-12-07 22:57
I am using NVM too, and getting the same error.
```
montogeek ~ [05:56 PM]→ 👾  💣  npm get prefix
/Users/montogeek/.nvm/versions/v4.1.0
montogeek ~ [05:56 PM]→ 👾  💣  cd /Users/montogeek/.nvm/versions/v4.1.0
montogeek ~/.nvm/versions/v4.1.0 [05:56 PM]→ 👾  ((HEAD detached at v0.17.2)) 💣  ls
total 1200
drwxr-xr-x  11 montogeek  staff   374B Nov 24 17:44 .
drwxr-xr-x   6 montogeek  staff   204B Nov  7 19:30 ..
-rw-r--r--   1 montogeek  staff   524K Sep 16 23:26 CHANGELOG.md
-rw-r--r--   1 montogeek  staff    52K Sep 16 23:26 LICENSE
-rw-r--r--   1 montogeek  staff    15K Sep 16 23:26 README.md
drwxr-xr-x  12 montogeek  staff   408B Dec  7 17:44 bin
drwxr-xr-x   2 montogeek  staff    68B Sep 23 15:23 etc
drwxr-xr-x   3 montogeek  staff   102B Sep 16 23:26 include
drwxr-xr-x   4 montogeek  staff   136B Sep 16 23:26 lib
drwxr-xr-x   5 montogeek  staff   170B Sep 16 23:26 share
lrwxr-xr-x   1 montogeek  staff    37B Nov 24 17:44 v4.1.0 -> /Users/montogeek/.nvm/versions/v4.1.0
montogeek ~/.nvm/versions/v4.1.0 [05:56 PM]→ 👾  ((HEAD detached at v0.17.2)) 💣  which eslint
/Users/montogeek/.nvm/versions/v4.1.0/bin/eslint
montogeek ~/.nvm/versions/v4.1.0 [05:56 PM]→ 👾  ((HEAD detached at v0.17.2)) 💣
```

**Comment by Arcanemagus** [comment] 2015-12-07 23:04
@montogeek If you set `Global Node Installation Path` to the folder which contains `eslint/lib/cli.js` does it work for you?

(For example: `/usr/lib/eslint/lib/cli.js`)

**Comment by montogeek** [comment] 2015-12-07 23:17
It did. Thanks @Arcanemagus :)

Is there a way to make do this automatic?

**Comment by Arcanemagus** [comment] 2015-12-07 23:20
Nope, it should already be working properly :disappointed:.

The problem is that for some reason on your system (all `nvm` systems?) `npm get prefix` is returning the wrong value. That _should_ be the path that the code for all the globally installed modules resides, but on some systems it seems to be the location the _binaries_ reside, which is completely wrong. So when this package tries to use `npm get prefix` to guess where the global `eslint`'s code is, it gets a completely wrong folder.

**Comment by montogeek** [comment] 2015-12-08 00:31
How I can debug it to check what `npm get prefix` returns on my machine?

**Comment by Arcanemagus** [comment] 2015-12-08 00:34
You already ran it in your output up there, the next step to check why it wasn't working for you would be to find out where `/Users/montogeek/.nvm/versions/v4.1.0/bin/eslint` actually points to.

**Comment by montogeek** [comment] 2015-12-08 00:35
I was talking about Atom debugging, but any way:
```
montogeek ~ [07:35 PM]→ 👾  💣  ls -alh  /Users/montogeek/.nvm/versions/v4.1.0/bin/
total 43512
drwxr-xr-x  12 montogeek  staff   408B Dec  7 17:44 .
drwxr-xr-x  11 montogeek  staff   374B Nov 24 17:44 ..
lrwxr-xr-x   1 montogeek  staff    40B Dec  1 18:49 eslint -> ../lib/node_modules/eslint/bin/eslint.js
lrwxr-xr-x   1 montogeek  staff    39B Nov  9 14:59 grunt -> ../lib/node_modules/grunt-cli/bin/grunt
lrwxr-xr-x   1 montogeek  staff    33B Dec  7 17:44 nf -> ../lib/node_modules/foreman/nf.js
-rwxr-xr-x   1 montogeek  staff    21M Sep 16 23:26 node
lrwxr-xr-x   1 montogeek  staff    38B Sep 16 23:26 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x   1 montogeek  staff    35B Nov 29 22:02 peercast -> ../lib/node_modules/peercast/bin.js
lrwxr-xr-x   1 montogeek  staff    35B Nov 29 22:04 peerflix -> ../lib/node_modules/peerflix/app.js
lrwxr-xr-x   1 montogeek  staff    40B Nov 24 18:19 rctapp -> ../lib/node_modules/rctapp/lib/rctapp.js
lrwxr-xr-x   1 montogeek  staff    44B Nov 24 18:19 rctapp-dev -> ../lib/node_modules/rctapp/lib/rctapp-dev.js
lrwxr-xr-x   1 montogeek  staff    45B Nov 11 21:01 react-native -> ../lib/node_modules/react-native-cli/index.js
```

**Comment by Arcanemagus** [comment] 2015-12-08 00:42
You would have to stick a console.log in the `worker.js` file to get that from within Atom, but it should be identical.

Now here is the odd thing... it should be working on your system.
`npm get prefix` is returning `/Users/montogeek/.nvm/versions/v4.1.0`, and in [es5-helpers.js](https://github.com/AtomLinter/linter-eslint/blob/v5.2.6/lib/es5-helpers.js#L27) we append `/lib/node_modules/eslint` to that to get to the source folder for `eslint`. On your system that would get `/Users/montogeek/.nvm/versions/v4.1.0/lib/node_modules/eslint`, which seems to be correct so I am not sure why it wasn't working properly...

What did you put into your `Global Node Installation Path` setting to get it working?

**Comment by montogeek** [comment] 2015-12-08 01:41
`/Users/montogeek/.nvm/versions/v4.1.0` and it worked :)
