### ISSUE TITLE
Reload eslint configuration

### ISSUE THREAD

**Issue by stackptr** [AtomLinter/linter-eslint#349] opened 2015-12-03 19:32 UTC
Maybe it's just an improperly configured linter on my part, but I find that any change I make to the eslint configuration (embedded in `package.json`) will not take effect until I completely quit Atom and then open the project again. I'm wondering if this is by design, my own error, or a bug?

**Comment by Arcanemagus** [comment] 2015-12-03 20:06
It's certainly not by design, and it _should_ be grabbing the config on every lint.

**Comment by iam4x** [comment] 2015-12-03 20:30
@stackptr Do you have two projects at the same time open on different windows?

**Comment by stackptr** [comment] 2015-12-03 20:49
I don't have two projects open. I have a local and globally installed eslint (both latest, with the linter Use Global option turned off). Using `babel-eslint` parser

**Comment by Arcanemagus** [comment] 2015-12-03 21:05
Looks like I can reproduce this (with this package's source code) using the following steps:

0. Open Atom
0. Open a javascript file and lint it
0. Open `package.json` and edit a rule in the `eslintConfig` object.
0. Switch back to the javascript file and lint it

**Comment by Arcanemagus** [comment] 2015-12-03 21:09
Killing the worker process (so that it respawns) causes it to reload the configuration, so something is caching it somehow that shouldn't be.

**Comment by IanVS** [comment] 2015-12-04 13:28
@Arcanemagus, the comment you linked to is inaccurate in regards to ESLint caching. ESlint will not cache unless the `--cache` flag is used, which we are not doing.

**Comment by SpainTrain** [comment] 2015-12-04 16:00
@Arcanemagus is correct that it is caching.  It is node module caching.  We see here https://github.com/eslint/eslint/blob/756b2790bf54e9f2df9a93dcfd40b8153a814e6a/lib/config/config-file.js#L150 that eslint loads `package.json` using `require`.  Loading json by that method caches it just like node caches every `require`d module.

A PR to fix upstream should be pretty straightforward.

**Comment by stackptr** [comment] 2015-12-04 21:38
I'm skeptical that it is node module caching, simply because prior to using Atom I was using Sublime Text + the SublimeLinter eslint plugin. The source for that plugin is on [github](https://github.com/roadhump/SublimeLinter-eslint) and it does not appear to do anything special to handle caching. When using ST+eslint, the new config file is used when the file is saved.

To expand, this is the flow in Sublime: open project, open file passing current `.eslintrc`, then change the `.eslintrc` to enforce a new rule (I turned on no-strict), then refer back to the open file. Saving the file will reveal the new linting error.

This process in Atom will result in no new linting error until I restart the entire editor.

**Comment by Arcanemagus** [comment] 2015-12-04 21:42
@stackptr the Sublime plugin you linked launches a new `eslint` instance for every lint request, thus the caching issue would not be exposed.

**Comment by stackptr** [comment] 2015-12-04 21:43
Ah, okay, thanks for clearing that up

**Comment by stackptr** [comment] 2015-12-04 21:44
I'm assuming that this plugin does not launch a new `eslint` instance for every new lint for performance reasons?

**Comment by Arcanemagus** [comment] 2015-12-04 21:49
That's the idea, there is talk over in #278 about potentially moving to a different model that may or may not involve a new process being launched.

**Comment by SpainTrain** [comment] 2015-12-04 22:16
If you require further proof that this is node module caching, here it is in the debugger:

![selection_044](https://cloud.githubusercontent.com/assets/380032/11602740/8b8e3f3e-9aaa-11e5-91d5-a7202a7a0910.png)

**Comment by Fenntasy** [comment] 2015-12-11 15:48
It could be simpler to provide an option to reload the config if there is a performance catch.

**Comment by IanVS** [comment] 2015-12-11 16:03
It's been fixed upstream in ESLint (thanks to @SpainTrain!), so after the newest version is released (2.0.0 beta should be released today), we should see this issue be resolved.

**Comment by mjomble** [comment] 2015-12-24 20:26
I tested with eslint v2.0.0-alpha-2 and am still having an issue with the conf not being reloaded from an edited `.eslintrc`

I suppose the issue has only been fixed for `package.json`

**Comment by albertosantini** [comment] 2016-01-24 21:58
I tested this issue with `linter-eslint 6.0.0` and `eslint 2.0.0-beta.2`.

Changing the config file, for instance `.eslintrc.yml`, and linting again the file, the new config takes effect, without quitting Atom, opening the project or the file again.

Closing?

**Comment by mjomble** [comment] 2016-01-24 22:21
It seems to work with `.eslintrc.yml` but not with `.eslintrc.js`.

I'm guessing the YAML markup is re-parsed every time, but the JavaScript code is cached in memory.

**Comment by albertosantini** [comment] 2016-01-26 10:49
https://github.com/eslint/eslint/issues/5067

Next eslint beta should contain that fix.

**Comment by MethodGrab** [comment] 2016-02-19 18:42
The `.eslintrc.js` fix landed in ESLint v2.2.0

**Comment by Arcanemagus** [comment] 2016-02-19 18:58
Awesome, thanks for the heads up (and fixing it in ESLint :wink:). Marking this as closed since the issue is resolved upstream (and wasn't a bug in this package in the first place).

**Closed by Arcanemagus** 2016-02-19 18:58 UTC
Labels: bug, upstream
