### ISSUE TITLE
[Linter-ESLint] Worker died unexpectedly

### ISSUE THREAD

**Issue by josebalius** [AtomLinter/linter-eslint#326] opened 2015-11-22 17:54 UTC
`Check your console for more info. A new worker will be spawned instantly`

Console

```
stderr: "(19989,0x7fff7d24e300) malloc: *** error for object 0x7fa3c0600e10: pointer being freed was not allocated↵*** set a breakpoint in malloc_error_break to debug↵"
stdout: ""
```

Happens quite often, running Atom 1.2.0 and linter-eslint 5.2.3, it started to happen once I upgraded to Atom 1.2.0, any ideas?

**Comment by steelbrain** [comment] 2015-11-22 17:56
Dupe of #303 #302 #301 #295 #290 and #278

**Closed** 2015-11-22 17:56 UTC
