### ISSUE TITLE
Error: Line number (409) greater than maximum line (408)

### ISSUE THREAD

**Issue by darkred** [AtomLinter/linter-eslint#359] opened 2015-12-08 11:09 UTC
Just updated linter-eslint from 5.2.5 to 5.2.6 (usint Atom 1.3.0 beta 6 with eslint 1.10.3 in win10 x64)
and I got this error once, right after the package update, when (I closed and reopened Atom
and) I opened a file to lint: _(I couldn't reproduce it afterwards, though)_

```
Error: Line number (409) greater than maximum line (408)
Error: Line number (409) greater than maximum line (408)
    at Object.rangeFromLineNumber (C:\Users\Kostas\.atom\packages\linter-eslint\node_modules\atom-linter\lib\helpers.js:141:11)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:170:35
    at Array.map (native)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:169:27
```

**Comment by Arcanemagus** [comment] 2015-12-08 17:12
If you can get a reproducible case that would be great!

**Comment by Arcanemagus** [comment] 2015-12-10 22:58
@darkred do you have a file that we can reproduce this with?

**Comment by darkred** [comment] 2015-12-10 23:04
Yes, it just occured: (Atom 1.4.0 beta 0 )

[Firefox_for_desktop_-_list_fixed_bugs_in_Mercurial.user.zip](https://github.com/AtomLinter/linter-eslint/files/58844/Firefox_for_desktop_-_list_fixed_bugs_in_Mercurial.user.zip)

How it just occurred:
- open the file (unzip it). You'll get `Info: Workers not initialized yet, please try again shortly`
- Close the file, and then re-open it. Rather quickly mark a few lines (22 and 23) and then press Del to delete them.

I got this error:

```
Error: Line number (420) greater than maximum line (419)
Error: Line number (420) greater than maximum line (419)
    at Object.rangeFromLineNumber (C:\Users\Kostas\.atom\packages\linter-eslint\node_modules\atom-linter\lib\helpers.js:141:11)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:170:35
    at Array.map (native)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:169:27
```

**Comment by Arcanemagus** [comment] 2015-12-10 23:44
The message you list there was last written like that in v5.2.4, are you _sure_ you are using v5.2.6?
Also the file in the `.zip` has 423 lines which is a tad longer than that error is claiming the file ends at so something else is up there.

I'm unfortunately not able to reproduce this so we'll have to work through trying to debug it :stuck_out_tongue:.

For starters let's make sure you are on the latest version of everything:

0. Close _all_ instances of Atom
0. Open a shell and type `apm uninstall linter-eslint; apm install linter-eslint`
0. Open Atom and Atom's dev tools
0. Place a breakpoint at [main.js:170](https://github.com/AtomLinter/linter-eslint/blob/v5.2.6/lib/main.js#L170)
0. Trigger the error and check the values of `line` and `textEditor.getBuffer().getLineCount()`

**Comment by darkred** [comment] 2015-12-11 00:06
[**@Arcanemagus**](https://github.com/Arcanemagus) commented on [Dec 11, 2015, 1:44 AM GMT+2](https://github.com/AtomLinter/linter-eslint/issues/359#issuecomment-163788209 "2015-12-10T23:44:28Z - Replied by Github Comment Enhancer"):
> The message you list there was last written like that in v5.2.4, are you _sure_ you are using v5.2.6?  
> 
> Also the file in the `.zip` has 423 lines which is a tad longer than that error is claiming the file ends at so something else is up there.
> 
> I'm unfortunately not able to reproduce this so we'll have to work through trying to debug it ![:stuck_out_tongue:](https://assets-cdn.github.com/images/icons/emoji/unicode/1f61b.png ":stuck_out_tongue:").
> 
> For starters let's make sure you are on the latest version of everything:
> 
> 1.  Close _all_ instances of Atom
> 2.  Open a shell and type `apm uninstall linter-eslint; apm install linter-eslint`
> 
> 3.  Open Atom and Atom's dev tools
> 4.  Place a breakpoint at [main.js:170](https://github.com/AtomLinter/linter-eslint/blob/v5.2.6/lib/main.js#L170)
> 
> 5.  Trigger the error and check the values of `line` and `textEditor.getBuffer().getLineCount()`

First of all, about linter-eslint version, see attachment: ![2015-12-11_014858](https://cloud.githubusercontent.com/assets/723651/11732085/93ca3398-9fa9-11e5-84dc-32490a660403.jpg)
Second, there's only Atom beta installed, and all this time, the error occurred while having just 1 instance of Atom running.

Also, after running `apm install linter-eslint`
I got:

```
Installing linter-eslint to C:\Users\Kostas\.atom\packages done

C:\Users\Kostas\AppData\Local\atom\app-1.4.0-beta0\resources\app.asar\src\compile-cache.js:163
let prepareStackTrace = prepareStackTraceWithSourceMapping
^^^
```

Also, setting the breakpoint the the line you said,
right after I open the file, the execution is paused in debugger,
and even as I press F8 to resume script execution,
the focus is not switched to the .js file so I can't delete lines 22,23 in order to re-create the issue.

On the other hand, based on your comments, maybe the installation of linter-eslint had become corrupted, as I describe [here](https://github.com/atom/atom/issues/9793)
and so, that's why this occured?

**Comment by Arcanemagus** [comment] 2015-12-11 00:11
The `apm install` bug is fixed in v1.3.1 of Atom (and should presumably be fixed in the next beta build), it doesn't affect package installation though so that's not an issue.

Something definitely sounds like it is having issues with what you reported over there. Can you go through the following to ensure you have a clean install of the plugin?

0. Close Atom
0. Run `apm uninstall linter-eslint`
0. Make sure `C:\Users\Kostas\.atom\packages` does _not_ contain a `linter-eslint` folder.
0. Delete the `C:\Users\Kostas\.atom\compile-cache` folder
0. Run `apm install linter-eslint`
0. Launch Atom and see if you can reproduce the issue, if so try to work through the troubleshooting steps outlined earlier.

**Comment by darkred** [comment] 2015-12-11 16:08
I've decided to clean re-install Atom and it's packages,
so I uninstalled it+packages (then also deleted the 'Atom' folders in Roaming and Local and the `C:\Users\Kostas\.atom` )
and eventually I re-installed it+packages.

The issue doesn't seem to re-occur. 
I'm closing this, because it seems like the `linter-eslint` package installation had been corrupted.
If it reoccurs, I'll inform you. Thanks for your time.

**Comment by Arcanemagus** [comment] 2015-12-11 16:56
Awesome, glad to hear you got it cleared up. Please do let us know if you see it again.

**Comment by leonelfreire** [comment] 2015-12-11 18:09
I'm experiencing the same problem, but in my case if I disable the atom-beautify extension the error disappears.

**Comment by leonelfreire** [comment] 2015-12-11 18:13
Both extensions are configured to execute only on file save.

**Comment by Arcanemagus** [comment] 2015-12-11 18:24
Do you still see the error if you disable atom-beautifies "on save" functionality? Atom really has no clean way to handle multiple packages attempting to use the buffer on the save event so it's possible that eslint grabs the text, sends if off to be linted, and then when it gets the text back atom-beautify is in the middle of re-writing it so there is nothing in the buffer (hence the maximum of 0 lines).

**Comment by leonelfreire** [comment] 2015-12-11 19:10
No. So that's the problem. :(

I'll disable the atom-beautify "on save" functionality for now.

Thanks.

**Comment by darkred** [comment] 2015-12-12 12:42
[**@darkred**](https://github.com/darkred) commented on [Dec 11, 2015, 1:04 AM GMT+2](https://github.com/AtomLinter/linter-eslint/issues/359#issuecomment-163781059 "2015-12-10T23:04:01Z - Replied by Github Comment Enhancer"):
> @Arcanemagus: yes, it just occured once more: 
> _(currently using Atom 1.4.0 beta 0, linter-eslint 5.2.6, eslint 1.10.3, win10 x64 build 10586)_
> 
> [Firefox_for_desktop_-_list_fixed_bugs_in_Mercurial.user.zip](https://github.com/AtomLinter/linter-eslint/files/58844/Firefox_for_desktop_-_list_fixed_bugs_in_Mercurial.user.zip)
> 
> How it just occurred:
> - open the file in Atom (unzip it first). _You'll get `Info: Workers not initialized yet, please try again shortly`_
> - Close the file, and then re-open it via File|'Reopen last item'. Rather quickly mark a few lines (22 and 23) and then press Del to delete them.
> I got this error:
> 
> ```
> Error: Line number (420) greater than maximum line (419)
> Error: Line number (420) greater than maximum line (419)
>     at Object.rangeFromLineNumber (C:\Users\Kostas\.atom\packages\linter-eslint\node_modules\atom-linter\lib\helpers.js:141:11)
>     at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:170:35
>     at Array.map (native)
>     at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:169:27
> ```

It just occured again (having clean re-installed Atom), by following the above steps. The error message:


```
Error: Line number (408) greater than maximum line (407)
    at Object.rangeFromLineNumber (C:\Users\Kostas\.atom\packages\linter-eslint\node_modules\atom-linter\lib\helpers.js:141:11)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:170:35
    at Array.map (native)
    at C:/Users/Kostas/.atom/packages/linter-eslint/lib/main.js:169:27
```

**Comment by Arcanemagus** [comment] 2015-12-13 10:54
@AtomLinter/linter-eslint Is anyone able to reproduce this? I am unable to on both of my active computers.

**Comment by Arcanemagus** [comment] 2015-12-13 11:00
@darkred what configuration are you using with `eslint`? It's possible this is something unique to that.

If you can determine which `atom-linter` helper module Atom is launching you can put a breakpoint in the `rangeFromLineNumber()` function where it triggers this and see what the values are that are causing issues.

**Comment by darkred** [comment] 2015-12-13 11:53
Based on http://eslint.org/docs/user-guide/migrating-to-1.0.0.html
Ι have the following `.eslintrc` in `C:\Users\user`
(FWIW, of which some lines have comments -a few of which are long- in the form of `// comment`)



```
{
    "rules": {
		"no-alert": 1,
        "no-array-constructor": 2,
        "no-caller": 2,
        "no-catch-shadow": 2,
        "no-empty-label": 2,
        "no-eval": 2,
        "no-extend-native": 2,
        "no-extra-bind": 2,
		"no-implied-eval": 2,
        "no-iterator": 2,
        "no-label-var": 2,
        "no-labels": 2,
        "no-lone-blocks": 2,
        "no-loop-func": 2,
		"no-multi-spaces": 1,
        "no-multi-str": 2,
        "no-native-reassign": 2,
        "no-new": 2,
        "no-new-func": 2,
        "no-new-object": 2,
        "no-new-wrappers": 2,
        "no-octal-escape": 2,
        "no-process-exit": 2,
        "no-proto": 2,
        "no-return-assign": 2,
        "no-script-url": 2,
        "no-sequences": 2,
        "no-shadow": 2,
        "no-shadow-restricted-names": 2,
        "no-spaced-func": 2,
        "no-trailing-spaces": 1,
        "no-undef-init": 2,
        "no-underscore-dangle": 2,
        "no-unused-expressions": 2,
        "no-use-before-define": 1,
        "no-with": 2,
        "camelcase": 2,a
        "comma-spacing": 1,
        "consistent-return": 2,
        "curly": [1, "all"],
        "dot-notation": [2, { "allowKeywords": true }],
        "eol-last": 1,
        "no-extra-parens": [2, "functions"],
        "eqeqeq": 1,
        "key-spacing": [2, { "beforeColon": false, "afterColon": true }],
        "new-cap": 2,
        "new-parens": 2,
        "quotes": [1, "single"],
        "semi": 2,
        "semi-spacing": [2, {"before": false, "after": true}],
        "space-infix-ops": 1,
        "space-return-throw-case": 2,
        "space-unary-ops": [2, { "words": true, "nonwords": false }],
        "strict": [2, "global"],
        "yoda": [2, "never"],
		"comma-dangle": [1, "always-multiline"],
		"no-console": 1,
		"no-extra-semi": 1,
		"no-mixed-spaces-and-tabs": 1,
		"no-unused-vars": 1,
    },
    "env": {
        "es6": true,
        "node": true,
		"browser": true,
		"jquery": true
    },
    "extends": "eslint:recommended",
}
```

**Comment by Arcanemagus** [comment] 2015-12-13 12:36
You need to use an alternative parser (like `babel-eslint`) to get ES6 support, simply setting "env:es6" to true doesn't quite cut it.

**Comment by IanVS** [comment] 2015-12-13 12:45
@Arcanemagus ESLint will handle all ES6 with its native parser. Babel-eslint is only needed for ES7+.

**Comment by arturparkhisenko** [comment] 2016-01-19 13:03
I getting this error almost a month with Win7 and Win10, Atom 1.2.1-1.4.0, atom-eslint 5.2.7, eslint 1.10.3. my message (i tried to reinstall with removing compiled):
```
Error: Line number (369) greater than maximum line (353)
    at Object.rangeFromLineNumber (C:\Users\User\.atom\packages\linter-csslint\node_modules\atom-linter\lib\helpers.js:160:11)
    at C:/Users/User/.atom/packages/linter-eslint/lib/main.js:151:35
    at Array.map (native)
    at C:/Users/User/.atom/packages/linter-eslint/lib/main.js:150:27
```

**Comment by Arcanemagus** [comment] 2016-01-25 21:15
@arturparkhisenko I don't see the error on https://gist.github.com/Arcanemagus/922fad78fbf03106e944, so obviously "an HTML file which contains js code" isn't a full reproduction case :stuck_out_tongue:

If you are still seeing this issue in v6.0.0 can you expand on that gist till you can reproduce this issue?

**Comment by arturparkhisenko** [comment] 2016-01-26 07:32
@Arcanemagus env(Win10, Atom1.4.1, linter-eslint6.0.0) my test html file:
```html
<!-- try to add or remove emptylinebreaks between scipt and dom-module -->
<dom-module id="test">
  <template></template>
</dom-module>
<!-- try to add or remove emptylinebreaks between scipt and dom-module -->
<script>
  Polymer({
    // place a cursor in JS and click save (lint-on-save)

    is: 'test', //this comma is important!

  });
</script>
```
Bug disappears when i removing: comma / dom-module tag / template tag inside dom-module.

**Comment by Arcanemagus** [comment] 2016-01-26 08:14
If `eslint-plugin-html` is reporting the incorrect value that would trigger this error, do you see the incorrect values when running it from a terminal?

**Comment by arturparkhisenko** [comment] 2016-01-26 08:29
@Arcanemagus i launched `eslint test.html` and got only error about comma-dangle.

**Comment by BenoitZugmeyer** [comment] 2016-01-26 21:40
Hi, `eslint-plugin-html` here, I can confirm the issue spotted by @arturparkhisenko is a bug in my plugin, I'll fix this really soon. Thank you @arturparkhisenko for your thorough investigation.

**Comment by Arcanemagus** [comment] 2016-01-26 22:22
FYI @arturparkhisenko you can turn on invisibles in Atom's settings to show the same in Atom :wink:.

Great to hear @BenoitZugmeyer, especially since we integrate that plugin in here :stuck_out_tongue:.

**Comment by BenoitZugmeyer** [comment] 2016-01-26 22:33
> especially since we integrate that plugin in here :stuck_out_tongue:.

I was really pleased to see this when I tested this issue! Thank you for your trust.

**Comment by arturparkhisenko** [comment] 2016-01-27 07:42
@Arcanemagus @BenoitZugmeyer Thanks! So we can close it now :) At least we have open issue in a plugin and fix already commited!

**Closed** 2016-01-27 18:03 UTC
Labels: upstream

**Comment by kentcdodds** [comment] 2016-08-02 21:45
So this just popped up again for me. I'm not sure how. I don't believe that any of my packages or anything were updated. Just randomly started happening. A restart doesn't fix the problem.

Interestingly, this seems to coincide with an issue I'm experiencing with Atom's auto tab detection (in a file with hard tabs, it's using soft tabs). Really, this just happened while working normally in the middle of nowhere...

Anyone else experiencing this?

**Comment by kentcdodds** [comment] 2016-08-02 22:01
I think I worked around the problem by using [editorconfig](https://atom.io/packages/editorconfig) and specifying my tab indentation for the project. Still not sure what's going on, but doing that worked for me.
