### ISSUE TITLE
Worker died unexpectedly

### ISSUE THREAD

**Issue by eventhough** [AtomLinter/linter-eslint#303] opened 2015-11-18 18:57 UTC
I'm on Atom `1.2.1`, linter `1.11.2`, and linter-eslint `5.2.0`. I just recently started seeing this error:

![worker died unexpectedly](https://photos-6.dropbox.com/t/2/AABC8CIWFekiSVPIGHFZ6elozThZNTIo5CV1wHiVcs8HLQ/12/187143/png/32x32/3/1447887600/0/2/Screenshot%202015-11-18%2010.52.45.png/EK6-LRjL_NSiBSACKAI/azwSOLIfpwvrVtFLc-F72MnUpZUFV5SITdWS54YvP-A?size_mode=2&size=1280x960)

Console error shows:

```
.atom/packages/linter/lib/message-registry.js:65 Uncaught (in promise) Error: Given editor is not really an editor(…)

ESLint Worker Info Objectstderr: "(8615,0x7fff79d89300) malloc: *** error for object 0x7ff9aad053e0: pointer being freed was not allocated↵*** set a breakpoint in malloc_error_break to debug↵"stdout: ""__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
```

I'm not sure if anybody else is seeing this error not.

**Comment by steelbrain** [comment] 2015-11-18 19:02
Dupe of #302 #301 #295 #290 and #278

**Closed** 2015-11-18 19:02 UTC
