### ISSUE TITLE
Multiple package.json files in subdirectories disable eslint if there's no config defined

### ISSUE THREAD

**Issue by piteer1** [AtomLinter/linter-eslint#768] opened 2016-12-14 09:17 UTC
## Issue Type
Bug

## Issue Description
Linter-eslint will not lint files if there's a `package.json` file in a subdirectory which does not define 
eslint configuration. I would expect that until there's no `eslintConfig` key in a `package.json` parent config will be taken into consideration.

For e.g. let's assume such directory structure:

![dir-structure](https://d17oy1vhnax1f7.cloudfront.net/items/0N1N0s2b0I282y3c1l14/Zrzut%20ekranu%202016-12-14%20o%2010.10.35.png?v=04885c00)

```json
// package.json
{
  "private": true,
//...
  "eslintConfig": {
    "parser": "babel-eslint",
    "extends": "airbnb",
    "globals": {
      "__DEV__": true
    },
    "env": {
      "browser": true
    },
    "rules": {
      "arrow-parens": "off",
      "generator-star-spacing": "off",
      "import/extensions": "off",
      "import/no-extraneous-dependencies": "off",
      "react/forbid-prop-types": "off",
      "react/jsx-filename-extension": "off",
      "react/no-danger": "off",
      "react/no-unused-prop-types": "off",
      "react/prefer-stateless-function": "off"
    }
  }
}
```

```json
// withPackageJson/package.json
{
  "main": "./eslint.js"
}
```

Then the file `index.js` will be linted, but `wont-lint.js` will be not.

Additionally, adding an empty `eslintConfig` in `withPackageJson/package.json` from above example will enable linting back.

I'm using `linter-eslint@8.0.0` / OSX

**Comment by IanVS** [comment] 2016-12-14 13:52
I'm not able to reproduce this behavior, all files are linted as expected when I replicate your directory structure.  Are you able to provide an example repo?

**Comment by piteer1** [comment] 2016-12-14 13:54
@IanVS Hello, did you restart Atom after adding new package.json with no ```eslintConfig```? I've forgot to add it into the description.

**Comment by IanVS** [comment] 2016-12-14 13:57
Hm, yes I've tried restarting and the nested file continues to be linted. I think a minimal reproducible case would really help here.

Also, have you checked the behavior of eslint on the cli?  We do not actually do any config resolution within this package, that is done by eslint itself.

**Comment by piteer1** [comment] 2016-12-14 14:06
Yes, I've tried invoking locally installed eslint from cli and it was working ok.

I'll try to prepare something later but I had the same behaviour editing any component (from `src/components` in https://github.com/kriasoft/react-starter-kit whether the linting is working fine for any component under `src/routes`

**Comment by IanVS** [comment] 2016-12-14 14:20
Ah, that helps, yep I'm seeing the same behavior you mention in that project.  Marking as a bug.

**Closed** 2017-03-14 19:07 UTC
Labels: bug
