### ISSUE TITLE
Fix errors on save, resets scrolling upon save.

### ISSUE THREAD

**Issue by rokyed** [AtomLinter/linter-eslint#774] opened 2016-12-29 08:04 UTC
## Issue Type

Bug

## Issue Description

enable **Fix errors on save**

upon save it resets scrolling of the file, this becomes annoying when file has many lines.
in other words it goes to the beginning of the file when saving.

**Comment by IanVS** [comment] 2017-01-05 05:07
Duplicate of https://github.com/AtomLinter/linter-eslint/issues/620.  It seems to be an Atom issue of replacing the entire buffer when a file changes.  Unfortunately there's nothing we can do in `linter-eslint`.

**Closed by IanVS** 2017-01-05 05:07 UTC
