### ISSUE TITLE
Ability to set node-version in process that runs eslint

### ISSUE THREAD

**Issue by foxtree** [AtomLinter/linter-eslint#870] opened 2017-04-03 15:40 UTC
## Issue Type

Feature Request

## Issue Description

I'm not sure how Atom handles the Node.js `process.version` it uses for each apm plugin, but:

Is it possible for `linter-eslint` to have the version of Node it uses be configurable?  (e.g.: via Atom's Settings, or read from `.nvmrc` or `.node-version` ?)

For example, if a repo I'm in attempts to lock-down Node's `process.version` (e.g.: for any build or linting process):
![image](https://cloud.githubusercontent.com/assets/3383704/24617303/895bff22-1861-11e7-9969-c903aadfa043.png)

...It seems that Atom wants to use (its built-in?) version of Node, that is `v6.5.0`.  
(I'd rather not have to globally-set this Node version  that Atom uses when it launches -- assuming that's even possible.)

**Comment by Arcanemagus** [comment] 2017-04-03 15:48
Unfortunately for your case, the only way to easily run ESLint is using the Node.js process running in Atom. It's technically possible to build a package that uses an external Node.js process to run it, but it would require a re-write of this package to make it work in that manner, it would also create a dependency on the system having a compatible version of Node.js installed which isn't necessarily true.

As for "just" changing `process.version`, I'm not entirely sure of the implications of that and how much it would break.

**Comment by foxtree** [comment] 2017-04-03 16:00
> having a compatible version of Node.js installed which isn't necessarily true

I guess if such a feature existed, it would need to be opt-in. This hurdle regarding having a a particular version of Node installed (and activated) is already the case, for anyone attempting to use NVM, NodeEnv, or some other system.  

I wonder if `Linter` (or something else in Atom, more generally?) would need to support delegating such tasks to a sub-process.

**Comment by Arcanemagus** [comment] 2017-04-03 16:23
ESLint is already being ran in a worker process, otherwise it would be blocking the main thread quite often 😉. The issue is that we are using Atom to run the process.

**Comment by Arcanemagus** [comment] 2017-09-17 06:47
I'm going to mark this as `wontfix` here as running with a customizable version of Node.js would require a major rewrite for very little benefit. If you want to test just changing `process.version` and can somehow show that it isn't going to break anything feel free to submit a PR for that.

**Closed by Arcanemagus** 2017-09-17 06:47 UTC
