### ISSUE TITLE
linter-eslint not using local installed eslint

### ISSUE THREAD

**Issue by maraujop** [AtomLinter/linter-eslint#740] opened 2016-10-20 10:59 UTC
Hi there,

Thanks for this great Atom package 👍 

Today I'm working in fixing an issue in one eslint plugin. 

After fixing it, I've discovered that my Atom is still raising errors, while if I run eslint (`./node_modules/eslint/bin/eslint.js`) from the cli the output shows no errors. So I'm afraid that linter-eslint is using its shipped version, instead of mine. Is there any way I can check this or disable this behavior?

Thanks, cheers
Miguel

**Comment by IanVS** [comment] 2016-10-20 11:09
Yes the best way to check is with the `Linter Eslint: debug` command.

**Comment by maraujop** [comment] 2016-10-20 14:46
thanks @IanVS Ok, I've just checked and it says `Using local project eslint from /Users/map/repos/rpms/node_modules/eslint`

But I've got a file with 9 errors, that when I run eslint cli manually only has one error, after my plugin modifications. So I'm not sure this is the truth.

Cheers,
Miguel

**Comment by IanVS** [comment] 2016-10-20 15:48
What command are you using to run eslint on the cli? Is it possible you're using a global eslint from the CLI?

**Comment by maraujop** [comment] 2016-10-20 16:32
I'm running from the root folder of my project:

```
./node_modules/eslint/bin/eslint.js App/cars/CarDetail.js
```

AFAIK I don't have an `eslint` globally installed. The plugin i've modified is `eslint-import-resolver-node` which is used by `eslint-import`. Maybe this package is using its own resolver ?

Thanks again, cheers,
Miguel

**Comment by IanVS** [comment] 2016-10-20 16:44
Can you paste the output of the debug command here?

Where do you have `eslint-import-resolver-node` installed?

**Comment by maraujop** [comment] 2016-10-20 16:47
Sure, `eslint-import-resolver-node` is within `node_modules/`

The output of the debug is:

```
atom version: 1.11.2
linter-eslint version: 8.0.0
eslint version: 3.7.1
hours since last atom restart: 6.3
platform: darwin
Using local project eslint from /Users/map/repos/rpms/node_modules/eslint
linter-eslint configuration: {
  "lintHtmlFiles": false,
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToSilenceWhileTyping": []
}
```

**Comment by IanVS** [comment] 2016-10-22 01:35
It looks like you tried restarting atom before filing this issue, didn't you?  Honestly, I'm a bit stumped why this would be happening.  Are you using `npm link` by chance?

**Comment by Arcanemagus** [comment] 2016-10-22 02:01
Are you able to share the code this isn't working on so we can try to reproduce this locally?

**Comment by maraujop** [comment] 2016-10-24 07:43
@IanVS that's right, I tried to restart it several times. I also don't have a clue what's going on here. I haven't done any `npm link` myself.

@Arcanemagus this is the patch I've done to eslint-plugin-import https://github.com/benmosher/eslint-plugin-import/pull/638 and you can easily trigger this behavior in any React Native project with absolute imports. 

I've been trying to find if there was an eslint-plugin-import in `~./atom/packages` maybe it's somewhere else ?

Cheers,
Miguel

**Comment by illumimari** [comment] 2016-11-06 23:11
+1

When using the Atom linter-eslint plugin, version 7.3.2 operates without issue.  Version 8.0.0 does not provide any feedback (and appears to not be recognizing my local eslintrc file).

Very grateful for all the work this team does.

**Comment by IanVS** [comment] 2016-11-07 01:13
I admit I'm still stumped on this one.  @illumimari are you able to provide the output of running the `Linter Eslint: Debug` command?

**Comment by tildebyte** [comment] 2016-11-11 20:10
Same

```json
atom version: 1.13.0-beta1
linter-eslint version: 8.0.0
eslint version: 3.9.1
hours since last atom restart: 0
platform: win32
Using global eslint from C:\Users\foo\AppData\Roaming\npm\node_modules\eslint
linter-eslint configuration: {
  "eslintrcPath": "C:\\Users\\foo\\.eslintrc.yaml",
  "fixOnSave": true,
  "globalNodePath": "C:\\Users\\foo\\AppData\\Roaming\\npm",
  "rulesToSilenceWhileTyping": [
    "no-trailingspaces"
  ],
  "useGlobalEslint": true,
  "lintHtmlFiles": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "advancedLocalNodeModules": "",
  "eslintRulesDir": "",
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ]
}
```

In the source file I'm currently working on:
- linter-eslint is *only* highlighting 52 issues - all symbols I've marked as reserved using `global`
- Standalone eslint, as noted from the above config, is correctly noting 41 (total) issues, including 9 instances where I missed some symbols I meant to reserve.

Although the debug trace above says that linter-eslint is using the global eslint and config file, it's clear that at the *least* it's not using the global config.

**Comment by SOSANA** [comment] 2016-11-29 05:51
1+ same problem as others on here

**Comment by SOSANA** [comment] 2016-11-29 17:43
Here is how I solved it via #459
```npm i -D eslint``` or ```yarn add -D eslint```

**Comment by IanVS** [comment] 2016-11-29 18:06
@tildebyte, can you try `eslint --print-config <path to one of your files>`, and verify if it is the same config as `C:\Users\foo\.eslintrc.yaml`?

**Comment by tildebyte** [comment] 2016-11-29 18:18
It is inexplicably working on Win 10 now. I noticed it working as expected on OSX some time last week, but didn't think to try again on Windows until this morning.

In answer to your question, though; yes they're the same, and it also works as expected with different config file locations.

IIRC, there have been a couple of updates to the `linter` base package recently, but I don't remember anything in the changelogs which looked it would have effected this.

**Comment by IanVS** [comment] 2016-11-29 18:27
Strange.  Well, glad it's working for you at least.  I still don't know what's going on with @maraujop though. 😕

**Comment by bobbypriambodo** [comment] 2016-12-19 08:32
Okay this is so weird. I'm also having the same issues as @maraujop where standalone eslint run via cli (`./node_modules/.bin/eslint <file>`) is only reporting one error while Atom linter gives 4.

`Linter Eslint: Debug` gives the right path of eslint, and if I try to change one other rule (say, `no-console` from `off` to `error`) and lint the file again through Atom, the linter picks it up, so I think there are no caching issues involved.

It was `eslint-import-resolver-node` for @maraujop; for me, the culprit library I think is [`eslint-import-resolver-webpack`](https://github.com/benmosher/eslint-plugin-import/tree/master/resolvers/webpack). It adds the following config settings for resolving to my `.eslintrc.yml`:

```yaml
settings:
  import/resolver:
    webpack:
      config: ./webpack/dev.config.js
```

If I comment out those settings, running from Atom and cli both gives the same result (cannot resolve some modules, which is expected). However, when those settings are in place, cli correctly resolved the modules while Atom fails. This is kind of frustrating 😅 

What makes it weird is that it used to work before, but sadly I wasn't able to remember what version I was using back then, I always update my packages when they come out...

Perhaps there is something wrong with resolving webpack config from Atom?

**Comment by bobbypriambodo** [comment] 2016-12-19 08:51
I tried looking into Atom's console and found this error message:

```
[Linter-ESLint] STDERR { Error: ENOENT: no such file or directory, open '.env'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Object.config (/Users/bobbypriambodo/Projects/projectname/node_modules/dotenv/lib/main.js:30:37)
    at Object.<anonymous> (/Users/bobbypriambodo/Projects/projectname/webpack/dev.config.js:1:98)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32) errno: -2, code: 'ENOENT', syscall: 'open', path: '.env' }
```

It seems like Atom did fail to parse my webpack config due to it failing to find `.env` file on my project. Which is weird, because it's there... Maybe it's due to the linter's execution context not being from my project's root (or is it?). I'll try digging further.

**Comment by deitch** [comment] 2017-02-08 10:40
I think I am having the same issue on my Mac. Running latest linter-eslint 8.1.0. I have eslint installed both globally `/Users/adeitcher/.npm/bin/eslint` and locally to my project `$PWD/node_modules/.bin/eslint`. They are different versions.

As soon as I open a js file with imports, I get the `AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.` that is known to be caused by mismatched eslint and babel-eslint versions.

I know I have good versions locally, but a mismatched version in my global npm. 

Config says it should use the local eslint if available, but it doesn't. The error message even shows:

```
AssertionError: ImportDeclaration should appear when the mode is ES6 and in the module context.
    at Referencer.ImportDeclaration (/Users/adeitcher/.npm/lib/node_modules/eslint/node_modules/escope/lib/referencer.js:591:34)
```

... clearly coming from the global eslint.

Is it misconfigured on my end? My understanding was that enabling `Use global ESLint installation` means, "use local in project else use global", while disabling it means, "use local on project else do nothing."

How can I help debug?

**Comment by deitch** [comment] 2017-02-08 11:02
Hmm, maybe not. I did manage to resolve the declaration, so perhaps this really is a global vs local issue?

**Comment by IanVS** [comment] 2017-02-08 13:29
>Maybe it's due to the linter's execution context not being from my project's root (or is it?).

Unless you have a `.eslintignore` file in your project root (even an empty one), we cannot detect the project root and use it for cwd.   You can try adding a `.eslintignore` file and see if that changes anything.

**Comment by IanVS** [comment] 2017-02-08 13:31
>My understanding was that enabling Use global ESLint installation means, "use local in project else use global", while disabling it means, "use local on project else do nothing."

Sorry, but that's not correct.  `Use global` will always use the global eslint install.  (We need to improve our docs).

To check what version is being used, you can run `Linter Eslint: debug`.

**Comment by deitch** [comment] 2017-02-08 13:33
> Sorry, but that's not correct.

Ah, and there is my issue. OK, so the question is, what mode is there that works like `PATH`: use first (local) then second (global)?

**Comment by IanVS** [comment] 2017-02-08 13:37
We don't have such an option, and ESLint itself does not support that either.  `linter-eslint` _will_ fall back to its own bundled version of ESLint if it cannot find any others to use, but we encourage people not to rely on that.

Honestly, you're best off not using a global version at all, and make sure that all of your projects have their own eslint installed and configured.

**Comment by deitch** [comment] 2017-02-08 13:38
> Honestly, you're best off not using a global version at all

No argument there for real projects. But sometimes I have a few individual files that I am editing, not part of a whole project, so good to have the global fallback.

**Comment by IanVS** [comment] 2017-02-08 13:54
For that, I'd suggest checking out https://atom.io/packages/project-manager.  

I'll do a little thinking about whether we should support falling back to global if a local eslint is not found.  We already fall back to the bundled eslint, so it's not too big of a stretch to check for a global install first, then fall back to bundled.  If we did that, I think we would make that the default behavior, and `use global` would be renamed to something like, `force global`.

@Arcanemagus, what do you think?  I'm going to need to think about it for a while, personally.

**Comment by Arcanemagus** [comment] 2017-02-08 17:12
@IanVS that sounds like better behaviour than what we currently do at least. My only concern with it is potentially an ancient version of ESLint being installed globally, but I doubt that we will be running into that as I think it would need to go all the way back to ESLint v1 to start having issues.

**Comment by Arcanemagus** [comment] 2017-09-17 06:17
@bobbypriambodo `eslint-import-resolver-webpack` is known to be problematic, see https://github.com/AtomLinter/linter-eslint/issues/610 for more details on issues with that.

As nobody that was reporting issues with `eslint-import-resolver-node` ever provided a way to reproduce this I'm going to mark this as closed since we have no way to test if this is still an issue, and track it down if it is. @maraujop or any others if you are still seeing this a minimal reproduction case would be great!

**Closed by Arcanemagus** 2017-09-17 06:17 UTC
