### ISSUE TITLE
Multiple node_modules folders cause exception.

### ISSUE THREAD

**Issue by lijunle** [AtomLinter/linter-eslint#314] opened 2015-11-20 18:50 UTC
Here is my project files:

```
/project/package.json
/project/.eslintrc
/project/index.js
/project/node_modules/{eslint}/... // eslint and config is installed in this folder
/project/test/case1/node_modules/fake_module // <--- no eslint or related files
/project/test/case1/code.js
```

When open `/project/index.js`, **everything works fine**. However, when open `/project/test/case1/code.js`, it throws exception:

```
Error: Cannot find module 'eslint-config-airbnb/base'
Referenced from: C:\project\.eslintrc
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at readConfigFromFile (C:\Users\lijunle\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:155:44)
    at loadConfig (C:\Users\lijunle\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:176:22)
    at C:\Users\lijunle\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:207:46
    at Array.reduceRight (native)
    at loadConfig (C:\Users\lijunle\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:191:36)
    at new Config (C:\Users\lijunle\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:385:38)
```

My `/project/.eslintrc` file, with `eslint-config-airbnb` package installed in `/project` folder.

```json
{
  "parser": "babel-eslint",
  "extends": "airbnb/base"
}
```

**Comment by Arcanemagus** [comment] 2015-11-20 19:12
Duplicate of #294.

**Closed by Arcanemagus** 2015-11-20 19:12 UTC
