### ISSUE TITLE
Tooltip text has dark color against dark background when using one-light-ui theme

### ISSUE THREAD

**Issue by elliottsj** [AtomLinter/linter-eslint#605] opened 2016-06-12 19:31 UTC
From https://github.com/steelbrain/linter/issues/1180

I've noticed that the linter tooltip label and the rule name have a dark text color when using the One Light UI theme, which is a bit hard to read again the dark background. For example:

<img width="682" alt="screenshot 2016-06-12 13 56 07" src="https://cloud.githubusercontent.com/assets/2177366/15993034/d0f48f12-30a8-11e6-9d30-353293c932ce.png">

In this case, the label "ESLint" and rule name "import/no-unresolved".

Using:
- Atom@1.8.0
- one-light-ui@1.3.1
- one-light-syntax@1.2.0
- linter@1.11.8
- linter-eslint@7.2.2

Is this something that should be fixed in linter-eslint? Or maybe it's an issue with https://github.com/atom/one-light-ui?

**Comment by Arcanemagus** [comment] 2016-06-13 17:08
This is certainly a bug, I just don't know where the fault lies... this package is merely using the theme's ["selected"](https://github.com/AtomLinter/linter-eslint/blob/v7.2.2/styles/atom-text-editor.less#L4) color there, but it's possible there is a better color to use (or none at all?).

**Comment by Arcanemagus** [comment] 2016-09-28 23:03
Marking this as a duplicate of #482.

**Closed by Arcanemagus** 2016-09-28 23:03 UTC
Labels: bug
