### ISSUE TITLE
Error: Cannot find module 'babel-eslint'

### ISSUE THREAD

**Issue by trusktr** [AtomLinter/linter-eslint#1186] opened 2018-10-15 23:51 UTC
Re-opening https://github.com/AtomLinter/linter-eslint/issues/556 (it is not resolved)

@yataras said

> I've fixed it with running npm install babel-eslint in ~/.atom/packages/linter-eslint/

then @Arcanemagus said

> @yataras As has been stated many times in this thread, that is not the way to fix this.

Until https://github.com/AtomLinter/linter-eslint/issues/845 is fixed, this is the best solution. (I want linter-eslint to fallback to global eslint _only when one is not found in the current project_.)

I have my entire `~/.atom` folder under source control, so if something breaks the brittle workaround that @yataras mentioned, I can easily revert it.

I would rather not install `eslint` dependencies into all of my personal projects because it is easier to install `eslint` dependencies in one place and for it to work everywhere.

**Comment by IanVS** [comment] 2018-10-16 01:47
It sounds like this is a duplicate of #845, perhaps?  As you say, you want to be able to use global eslint in some projects, and local eslint in others.  You didn't say, but implied, that you don't want to change any settings.  Because currently you can still turn the `Use global eslint installation` setting on and off depending on what project you're in, if you're using a mix of global and local eslint installations.  Just make sure to have `babel-eslint` installed globally as well, if your global linting settings rely upon it.

**Comment by trusktr** [comment] 2018-10-16 04:49
Yeah, that's what I meant.

I wonder if we can do this:

- Use eslint in a project if it exists. Done, no further steps.
- If no project eslint, then if a global eslint is installed, use that.
- If no global eslint, use the one from linter-eslint
   - I'm not sure the one from linter-eslint should ever be used anyway, because it has no config or packages like babel-eslint installed, and the latest eslint comes with zero rules, so it is useless.

This way if we want our own outside-of-projects config, we simply just install eslint and related packages globally, and edit `~/.eslintrc.js` without having to worry about the `Use global eslint installation` checkbox.

**Comment by IanVS** [comment] 2018-10-16 19:52
Yes, I mostly agree, except that we also need to consider folks who do not want to run any linting at all in projects where there is no `.eslintrc` file.  Right now we have the setting `Disable when no ESLint config is found (in package.json or .eslintrc)`, but https://github.com/AtomLinter/linter-eslint/pull/1068 is going to change behavior slightly such that we'll also look in a user's home directory for a config file (just like eslint does).  

My guess is that we will end up with a single option of "Allow fallback to global ESLint", so that your use case can be satisfied, as well as those who do not want to lint their files if the project they're in does not have its own configuration set up.

**Comment by trusktr** [comment] 2018-10-18 05:11
How about a simple GUI button? f.e., prettier has the following button to toggle it on/off (look at the bottom of the window):

![screen shot 2018-10-17 at 10 07 12 pm](https://user-images.githubusercontent.com/297678/47132514-14577b80-d259-11e8-8528-90b146136f66.png)

This way we don't have to open Atom settings and go find the package and then the setting in the package README.

That would be enough I think:

- We just install whatever we like globally for situation when a project doesn't have eslint.
- If we don't want to lint a project that doesn't have eslint, we just turn it off at the click of a button.
- It basically just maps to the `Use global eslint installation` setting.

I bet the main reason this issue has come up before is because of how tedious it is to look for the setting. The button would basically solve that.

**Comment by trusktr** [comment] 2018-10-18 05:15
Also Prettier has an option to show or not show the button in the bottom status bar.

**Comment by Arcanemagus** [comment] 2018-10-18 16:52
As you have written this issue so far, this is just a duplicate of #845.

#1068 _will_ break this scenario for what you are asking... but that's because it will match what ESLint itself would do. I would rather follow ESLint here since the "global user config" would only be used if your current project has no configuration. If that isn't behavior that you want then you _shouldn't have a global config_.

Your proposed button should be brought up with the consumers of the service `linter-eslint` provides. We aren't in control over when lint results are requested.

----

Since it seems like you may not have read #845, the tl;dr of the solution for that is what you have already proposed in https://github.com/AtomLinter/linter-eslint/issues/1186#issuecomment-430099639, with the exception that the bundled version is being removed so there would _only_ be the project local install, with a fallback to the global install if available.

**Closed** 2021-03-14 06:44 UTC
