### ISSUE TITLE
Linter-ESLint worker died unexpectedly

### ISSUE THREAD

**Issue by eyalw** [AtomLinter/linter-eslint#301] opened 2015-11-18 11:59 UTC
While normally editing a JS file on Atom, linter ESLint crashes (see photo)
any ideas?

![screen shot 2015-11-18 at 1 57 49 pm](https://cloud.githubusercontent.com/assets/608669/11240539/60cfe046-8dfc-11e5-833a-bfe638a61e8f.png)

![screen shot 2015-11-18 at 2 00 22 pm](https://cloud.githubusercontent.com/assets/608669/11240595/c39d7792-8dfc-11e5-9d8a-6c512dbb90fc.png)

**Comment by 5an1ty** [comment] 2015-11-18 12:04
I have the same issue with the following stderr:

"(6586,0x7fff76b48000) malloc: *** error for object 0x7fc5f8511c40: pointer being freed was not allocated *** set a breakpoint in malloc_error_break to debug "

**Comment by steelbrain** [comment] 2015-11-18 13:06
Dupe of https://github.com/AtomLinter/linter-eslint/issues/295 https://github.com/AtomLinter/linter-eslint/issues/290 and https://github.com/AtomLinter/linter-eslint/issues/278

**Closed by steelbrain** 2015-11-18 13:06 UTC
